### ISSUE TITLE
In 1.7.6 pins aren't being given on default

### ISSUE THREAD

**Issue by tony** [django-extensions/django-extensions#1006]
Requirements:

```
django-extensions==1.7.6 # Updated from 1.7.5
werkzeug==0.11.15
django-storages==1.5.2
boto==2.45.0
django_libsass==0.7
django-mptt==0.8.7
django-debug-toolbar==1.6
Django==1.10.5 # Updated from 1.8
six==1.10.0
sqlparse==0.2.2
django_compressor==2.1
django_compressor_autoprefixer==0.1.0
django-easy-pjax==1.3
```

Python 3.6

I am prompted for a console pin on Werkzeug, but no pin is given anymore in 1.7.6

![screen shot 2017-01-31 at 10 11 10 am](https://cloud.githubusercontent.com/assets/26336/22473184/9cba419a-e79d-11e6-9a05-1afc0ef63518.png)
![screen shot 2017-01-31 at 10 10 31 am](https://cloud.githubusercontent.com/assets/26336/22473183/9cb6dec4-e79d-11e6-87fa-5af6edbbc604.png)

**Comment by trbs** [comment]
This is fixed afaik
