### ISSUE TITLE
Metadata gives incorrect Documentation URL

### ISSUE THREAD

**Issue by bignose-debian** [django-extensions/django-extensions#1008]
The PyPI page for this distribution, https://pypi.python.org/pypi/django-extensions/1.7.6, has links to the documentation.

The links use the wrong URL, http://pythonhosted.org/django-extensions/, which does not lead to the documentation for this distribution.

Please correct the metadata (and all links), and upload a new version to PyPI with the correct documentation links.

**Comment by kevgathuku** [comment]
@bignose-debian When I tried accessing http://pythonhosted.org/django-extensions/, I was redirected to https://django-extensions.readthedocs.io/en/latest/
