### ISSUE TITLE
The sqldiff command doesn't recognize GeoDjango and JSON fields

### ISSUE THREAD

**Issue by imagescape** [django-extensions/django-extensions#1010]
The sqldiff is a great tool.  However, I'm noticing that it does not recognize less common fields, such as PointFields from GeoDjango and JSON fields from the django-jsonfield project. Even if I run the alter statements that sqldiff suggests, sqldiff still reports difference in the output. 

### The sqldiff command doesn't seem to recognize geography columns from GeoDjango:  

Code Sample:

    from django.contrib.gis.db import models as geomodels
    class Location(models.Model):
        ...
        point = geomodels.PointField(editable=False, geography=True, null=True)

Sqldiff output:

    -- Application: eventcalendar
    -- Model: Location
    -- Comment: Unknown database type for field 'point' (130253)
    ALTER TABLE "eventcalendar_location"
    	ALTER "point" TYPE geography(POINT,4326);

### The sqldiff command doesn't seem to recognize geometry columns from GeoDjango:  

Code Sample:

    from django.contrib.gis.db import models as geomodels
    class Office(models.Model):
        ...
        point = geomodels.PointField(editable=False)

Sqldiff output:

    -- Application: physicians
    -- Model: Office
    -- Comment: Unknown database type for field 'point' (129699)
    ALTER TABLE "physicians_office"
	ALTER "point" TYPE geometry(POINT,4326);
    COMMIT;

### The sqldiff command doesn't seem to recognize jsonfields (from django-jsonfield). I haven't tried with the newer built-in jsonfields yet, so maybe it will work with that? 

Code Sample:
https://github.com/ImaginaryLandscape/django_site_config/blob/master/site_config/backends/model_backend/models.py#L110

Sqldiff output:

    -- Application: site_config
    -- Model: WebsiteApplication
    -- Comment: Unknown database type for field 'options' (114)
    ALTER TABLE "site_config_websiteapplication"
    	ALTER "options" TYPE text;

**Comment by trbs** [comment]
Regretfully I did not have the time in the last year to properly continue to develop `sqldiff` :(

Probably recent versions of Django ORM also have better introspection tools for `sqldiff` to do the comparisons. I will leave this open and hopefully I or somebody else has time to continue making `sqldiff` better and more compatible with fields.

**Comment by xavfernandez** [comment]
The part about JSONFieldis not fixed though.

**Comment by t-book** [comment]
Any updates on JSONField support?

**Comment by trbs** [comment]
Can we open a new issue for this ? 

Think for both `JSONField`'s the type is `TEXT` is the right answer is it not ?

**Comment by t-book** [comment]
exactly. The problem happens when some app uses the JSONField type of postgresql.
