### ISSUE TITLE
AutoSlugField for foreignkey relationships

### ISSUE THREAD

**Issue by YPCrumble** [django-extensions/django-extensions#1011]
Thanks for this great library! I use it on every Django project.

I was looking to use foreignkey relationships in my autoslugfield. Something like:

```
class TeamMember(models.Model):
    name = CharField
    team = FK(Team)
    slug = AutoSlugField(populate_from=("team__name", "name")

class Team(models.model):
    name = CharField
```

Would a PR for this be desirable? I was thinking of using something like this StackOverflow answer to lookup the foreignkey relationship: http://stackoverflow.com/questions/20235807/how-to-get-foreign-key-values-with-getattr-from-models

**Comment by trbs** [comment]
Thanks !

Sounds good, happy to accept a PR for this.

Maybe you can reuse (some) of the code inside the django ORM for the foreignkey lookup ?
