### ISSUE TITLE
shell plus autoload DRS serializers ?

### ISSUE THREAD

**Issue by amineparis** [django-extensions/django-extensions#1013]
when debugging Django rest framework serializers using shell life would be much easier if we can use shell plus to auto-load serializers. is this possible right now ?

**Comment by trbs** [comment]
Not automatically right now.

Happy to accept a PR for this.

(In or after a PR for this, I will probably want to make that code more generic / plugin style so it's easy to add support for "autoloading" other common cases besides Django ORM and DRS)

**Comment by yakupadakli** [comment]
https://github.com/django-extensions/django-extensions/pull/1024

**Comment by trbs** [comment]
PR 1024 congratulations 👍 

Thanks for the PR !
Could you please add some tests for this ?

**Comment by domandinho** [comment]
@trbs
Ticket and PR is to close because this functionality can be realized using feature from https://github.com/django-extensions/django-extensions/issues/1158
`SHELL_PLUS_SUBCLASSES_IMPORT = ['rest_framework.serializers.Serializer']`
