### ISSUE TITLE
--filter-list doesn't work properly for sync_s3

### ISSUE THREAD

**Issue by khirstinova** [django-extensions/django-extensions#1019]
In previous versions, --filter-list would exclude the entire directory and subdirectories if a directory name were included.  In the "sync_s3" function, it used this for loop

        for directory in self.DIRECTORIES:
            os.path.walk(directory, self.upload_s3, (bucket, key, self.AWS_BUCKET_NAME, directory))

Now it uses this for loop

        for directory in self.DIRECTORIES:
            for root, dirs, files in os.walk(directory):
                self.upload_s3((bucket, key, self.AWS_BUCKET_NAME, directory), root, files)

The problem is that os.walk is called on all subdirectories of an excluded directory.  The effect being that, for example, the "static/mezzanine" directory itself is excluded, but static/mezzanine/chosen" is not excluded.

**Comment by khirstinova** [comment]
I got this to run locally by changing the loop to

        for directory in self.DIRECTORIES:
            for root, dirs, files in os.walk(directory):
                self.upload_s3((bucket, key, self.AWS_BUCKET_NAME, directory), root, files, dirs)

And upload_s3 to 

    def upload_s3(self, arg, dirname, names, dirs):
        """
        This is the callback to os.path.walk and where much of the work happens
        """
        bucket, key, bucket_name, root_dir = arg

        # Skip directories we don't want to sync
        if os.path.basename(dirname) in self.FILTER_LIST:
            # prevent walk from processing subfiles/subdirs below the ignored one
            del dirs[:]
            return

Essentially changed "del names" to "del dirs" since that prevented the walking.  I tried to push a branch, but I am forbidden.

**Comment by khirstinova** [comment]
Ran through a bunch of test cases.  Didn't work in every case, so we needed to change the code in uploads_s3 to

    def upload_s3(self, arg, dirname, names, dirs):
        """
        This is the callback to os.path.walk and where much of the work happens
        """
        bucket, key, bucket_name, root_dir = arg

        # Skip directories we don't want to sync, only in directories directly below the root
        if os.path.basename(dirname) in self.FILTER_LIST and os.path.dirname(dirname) in self.DIRECTORIES:
            # prevent walk from processing subfiles/subdirs below the ignored one
            del names[:]
            return

**Comment by trbs** [comment]
Please create a PR for the solution :)

**Comment by khirstinova** [comment]
I have done so, and added a good unit test.

**Comment by trbs** [comment]
I assume this one is merged already 👍
