### ISSUE TITLE
Unable to graph_models when specifying apps

### ISSUE THREAD

**Issue by jmerkow** [django-extensions/django-extensions#1021]
I am trying to graph models for selected apps with the following command: `./manage.py graph_models foo.bar > my_project.dot` , I get this error: `manage.py graph_models: error: unrecognized arguments: foo.bar`.
I have also tried `./manage.py graph_models bar > my_project.dot`.  Same error.
Using --all-applications works fine, but this is not what I want.

My project layout has apps in a subdirectory (same as django cookiecutter):
foo
```
├── config
│   ├── settings
│   │   ├── common.py
│   │   ├── local.py
│   │   ├── production.py
    ...
...
├── foo
│   ├── bar
│   │   ├── apps.py
│   │   ├── models.py
        ...
...
```
Apps are load via a config:
```
INSTALLED_APPS = [
...
'foo.bar.apps.BarConfig',
...
]
```

foo.bar.apps.BarConfig looks like:
```
class BarConfig(AppConfig):
    name = 'foo.bar'
    verbose_name = 'Bar'
    label = 'bar'
```

**Comment by trbs** [comment]
As per the thread on the mailinglist, I cannot seem to reproduce this.

Creating a reproducible test case would give us a starting point and make sure that future regressions will not occur.

**Comment by jmerkow** [comment]
Ok, Thank you.
I will work on getting a reproducible example to you.

In the meantime, could it be a version mix-match:
```
django-extensions==1.6.7
django==1.10.3
```
