### ISSUE TITLE
pipchecker wrongly reports "release is not on pypi "

### ISSUE THREAD

**Issue by karyon** [django-extensions/django-extensions#1025]
`process_line` called in this line here: https://github.com/django-extensions/django-extensions/blob/1ee95685873ea2c01b86967cf42f10eeac2ea10e/django_extensions/management/commands/pipchecker.py#L80

returns package names where e.g. underscores have been replaced by dashes. however, `package_releases` here: https://github.com/django-extensions/django-extensions/blob/1ee95685873ea2c01b86967cf42f10eeac2ea10e/django_extensions/management/commands/pipchecker.py#L139 does only accept the unaltered name of the project, which might include underscores. 

so, if my requirements.txt contain e.g. `django_compressor` or `model_mommy`, pipchecker will report `model-mommy 1.3.1                release is not on pypi (check capitalization and/or --extra-index-url)`, although my installation is perfectly fine as far as i am aware :)

**Comment by nicolasmendoza** [comment]
@trbs can you assign me this task, please?

**Comment by trbs** [comment]
@nicolasmendoza please create a PR and we can merge that to fix this.

**Comment by nicolasmendoza** [comment]
Work in progress...

**Comment by trbs** [comment]
Thanks

**Comment by trbs** [comment]
Not sure if this is still an issue ? if it is please submit a PR with a fix.

**Comment by karyon** [comment]
just tested with 1.9, yes it's still an issue.

**Comment by karyon** [comment]
can you reopen this?

**Comment by trbs** [comment]
@karyon could you please submit a PR (with tests if possible) and we can track and resolve the issue there. Thanks.

**Comment by karyon** [comment]
no, sorry. may i ask why you are closing a valid bug report?
