### ISSUE TITLE
Any way to activate IPython autoreload module with command line arguments

### ISSUE THREAD

**Issue by rkpatel33** [django-extensions/django-extensions#1044]
I would like to be able to activate the IPython autoreload module that I usually do this way:

```
%load_ext autoreload
%autoreload 2
```

By adding arguments into the Django shell_plus call that I usually make:
```
python manage.py shell_plus --ipython
```

Is this at all possible? I know it's possible to do this using IPython directly.

**Comment by trbs** [comment]
You can set `IPYTHON_ARGUMENTS` in `settings..py` which you can probably use to set `--profile=foo` and then use the profile's `startup` directory to activate the autoreload module of IPython.

Hope this helps.

P.S. If you get this to work, please consider submitting a PR for the documentation describing how to set this up so other people can learn from it :-)
