### ISSUE TITLE
Use text/plain for foreign key autocomplete admin

### ISSUE THREAD

**Issue by jpnauta** [django-extensions/django-extensions#1056]
My admin site uses `ForeignKeyAutocompleteAdmin`. One day, our autocomplete fields started looking like this:

<img width="816" alt="screen shot 2017-05-18 at 3 25 59 pm" src="https://cloud.githubusercontent.com/assets/3439947/26224142/5551f812-3bde-11e7-8c23-74bec868f7f5.png">

The full HTML response looked like this:

`<html><head></head><body>My Venue</body></html>`

This issue was that we are using `htmlmin.middleware.HtmlMinifyMiddleware`, and since the response's content type is `text/html`, the response was 'minified' to include HTML tags

I solved this issue by doing this in my admin class:

```
    def foreignkey_autocomplete(self, request):
        response = super(BaseModelAdmin, self).foreignkey_autocomplete(request)
        # HtmlMinifyMiddleware does not play nicely with ForeignKeyAutocompleteAdmin - force response to plain text
        response['Content-Type'] = 'text/plain'
        return response
```

Though this code solved my issue, I suggest that the content type of `foreignkey_autocomplete` response should be set to `text/plain` instead of using the default `text/html` to avoid more issues like this.

**Comment by trbs** [comment]
Could you please make a PR for this ?

**Comment by jpnauta** [comment]
Finally remembered to do this :smile: P/R here: #1100

**Comment by trbs** [comment]
Thanks !
