### ISSUE TITLE
New Debian/Ubuntu/pip release please ...

### ISSUE THREAD

**Issue by bernd-wechner** [django-extensions/django-extensions#1057]
I just installed this via apt on a Debian based system and it fails to run. I reinstalled it with pip and still fails to run. Turns out the reason is here:

https://github.com/django-extensions/django-extensions/commit/f3d80be6964b8498e15e40e8348c4398cf7439a5

As in a fix mad in Jan 2016 is needed for Django 1.11 the current Django release but D.deb and pip packages don't work with it. It's way time for new packages to be put into the distros.

**Comment by trbs** [comment]
I'm not totally sure what you mean from this ticket nor the action to be taken but I will try to respond as best as I can.

The latest pip release was a couple of weeks ago and should work according to the Django versions policy. (If there is an issue with that people open a specific ticket per issue with reproducible test case and even better PR and tests for fixing it 👍 )

The version in Debian packaging is relatively old.  I cannot quickly see an easy way to nudge the python modules team for updating to a newer version in unstable. If you want it would help if you could add an issue there to update to a newer version.

https://packages.qa.debian.org/p/python-django-extensions.html
https://packages.debian.org/unstable/python3-django-extensions

Thanks !

**Comment by bernd-wechner** [comment]
Sorry for the lack clarity, but I tried installing from the ubuntu repository and and the extension di not work because of the issue fixed in Jan 2016 described above. To wit concluded the Ubuntu repository had not had a new package update since the fix well over a year ago. 

The suggested action is to update the ubuntu repositories with a package that works with the current version of Django there (1.11).

The pip repository I assumed was also dated because I installed it with pip and also did not work. But it may be that this was because I had the dated ubuntu.deb package installed already. I wasn't looking too closely. The fix I made locally was to fully remove the ubuntu package then download from git here and install and I'm rolling. So it might be the pip repository has the update already and I bungled the install.

All I was observing was if on Ubuntu you install django and django-extensions then django extensions does not work. But the break was fixed in Jan 2016 and the ubuntu repository not updated yet.

**Comment by trbs** [comment]
Thanks for the reply !

I have not found an easy way yet (in the limited time I had available) to nudge the maintainers and ask them to update. I did see that the Ubuntu/Debian development system automatically nudges them when new versions become available and that it shows newer versions are indeed available.

If the versions of Django and Django-Extensions in the Ubuntu/Debian package list are out of sync it's probably best to raise a ticket with them so they can update Django-Extensions.

Would be very happy with a closer relationship with those maintainers to make sure something like this does not happen in the future or that packages like ours can be updated more frequently.
