### ISSUE TITLE
manage.py show_urls not working with Django 1.7

### ISSUE THREAD

**Issue by benzid-wael** [django-extensions/django-extensions#1068]
I run into a problem using `show_urls` command on my mac with Django 1.7. For both these commands `python manage.py show_urls` and ` python manage.py show_urls --format=dense`, I got this error:

> (env) wael.benzid$ python manage.py show_urls
CommandError: Format style 'None' does not exist. Options: ['dense', 'verbose', 'pretty-json', 'json', 'table', 'aligned']

## Environment:
* OS: macOS Sierra
* Python: cPython 2.7.9
* django-extensions==1.7.9
* Django==1.7.10

**Comment by trbs** [comment]
Regretfully Django 1.7.10 is not supported anymore.

If there is a simple fix for this that does not hinder maintenance then please submit a PR.
