### ISSUE TITLE
shell_plus: plain: change default for loading Python startup file

### ISSUE THREAD

**Issue by blueyed** [django-extensions/django-extensions#1082]
Django's `shell` command will load `PYTHONSTARTUP` or `~/.pythonrc.py` by default for the `plain` interpreter.
You can specify `--no-startup` to skip this, but only for the `plain` interpreter: with `-i bpython` or `-i ipython` this has no effect - it gets loaded there through the embedment always.

With `shell_plus` however you need to explicitly enable loading of the startup file (via `--use-pythonrc`) for the `plain` interpreter, which is a bit annoying when you're used to have your `readline` history being configured through `PYTHONSTARTUP`.

It is not an issue once you've installed ipython/bpython etc, since they will also handle the `PYTHONSTARTUP` file with `shell_plus` then.

**Comment by trbs** [comment]
Could you please test if this change works as expected for you ? https://github.com/django-extensions/django-extensions/commit/73d6826fa6e1aa32833380fd10832454881b832b

**Comment by blueyed** [comment]
Works, thanks!

**Comment by trbs** [comment]
Great thanks for testing.

I will try to get a new release out shortly.
