### ISSUE TITLE
Serializer/validator to catch in case of JSONDecodeError

### ISSUE THREAD

**Issue by ishankhare07** [django-extensions/django-extensions#1086]
In case of invalid json being posted for a `JSONField`, I get an HTTP 500. It would be very helpful to provide a way to write a validator for this field that catches the error can returns the provided error message.

**Comment by trbs** [comment]
Thanks for opening an issue.

We are happy to accept pull requests to improve `JSONField` either in code or by better documentation.

A good starting place for any improvements in code is the JsonField from Django itself and to follow it as closely as we can:

https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#jsonfield
https://docs.djangoproject.com/en/1.11/_modules/django/contrib/postgres/fields/jsonb/#JSONField

More documentation (and examples) on how to use the field and write validators for it would also be appreciated.
