### ISSUE TITLE
exec in subfunction = syntaxerror

### ISSUE THREAD

**Issue by joej** [django-extensions/django-extensions#1091]
command "./manage.py shell_plus" throws:
SyntaxError: unqualified exec is not allowed in function 'get_plain' it contains a nested function with free variables

in line 230 of shell_plus.py, this seems to solve it:
                    exec(compile(pythonrc_code, pythonrc, 'exec'), imported_objects) in globals(), locals()

**Comment by trbs** [comment]
Please make a pull request.

Could you please also look into a test for this ? we don't have any tests for `shell_plus` at the moment. It would be very good to hit this with a test so we can make sure there no regressions in the future.

**Comment by trbs** [comment]
I think this is already fixed in git. 
If the mainline version is still not working for you please reopen the ticket and add a test to the test suite.

**Comment by ewjoachim** [comment]
Hi, do you think it would be possible to make a new release with the fix ?

Thank you.

**Comment by trbs** [comment]
Sure will be out shortly 👍

**Comment by trbs** [comment]
The new release does not include any patch for this issue.

If 1.9.1 still causes issues then please add more information about which version of Python and Django Extensions your using and submit a PR with a test for this issue.

Thanks

**Comment by clokep** [comment]
I'm still seeing this with django-extensions 1.9.1 and Python 2.7.6 with Django 1.10.8.

Full stack trace:
```
Traceback (most recent call last):
  File "manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 229
    exec(compile(handle.read(), pythonrc, 'exec'), imported_objects)
SyntaxError: unqualified exec is not allowed in function 'get_plain' it contains a nested function with free variables
```

**Comment by ewjoachim** [comment]
Well, a test could import the shell_plus module and fail when a SyntaxError is raised :/

So, I *thought* you said it had been fixed, sorry for the trouble.

**Comment by jgb** [comment]
I'm having this issue on django-extensions 1.9.1, python 2.7.6 and django 1.8.18

**Comment by ppython** [comment]
@trbs  : this change seems to have broken the shell_plus command https://github.com/django-extensions/django-extensions/commit/f850cdd55563fb9ac8a29937709a445bc1b14155

As @joej  suggested, adding "in globals(), locals()" makes this new writting works; 
This is all I needed, I'll link a PR
