### ISSUE TITLE
Repeated Error output with runserver_plus vs runserver

### ISSUE THREAD

**Issue by yunti** [django-extensions/django-extensions#1092]
Currently the runserver_plus output creates a lot of noise when it hits an exception by repeating the error several times over.

Gist below showing output:
https://gist.github.com/anonymous/d961492aaa82c32edd73dc0f8cadb570

(using:
django-extensions==1.9.0
Werkzeug==0.12.2
)

**Comment by trbs** [comment]
It looks like your site is loading multiple urls / http-requests in parallel ?

```
127.0.0.1 - - [29/Aug/2017 12:10:25] "GET /users/quotes_results/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Aug/2017 12:10:25] "GET /users/quotes_results/?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [29/Aug/2017 12:10:25] "GET /users/quotes_results/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [29/Aug/2017 12:10:25] "GET /users/quotes_results/?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [29/Aug/2017 12:10:25] "GET /users/quotes_results/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

Using `---nothreading` might solve this as all the requests will be serialized.

(Although I thought Django's runserver also does threading by default now, so not sure why that only shows one error message.)

Another thing would be that the stacktrace is a lot longer and repeating the part around `django_extensions/management/technical_response.py` several times.

If this is something we can fix in `django-extensions` I'm happy to accept PR's for it.

**Comment by yunti** [comment]
Thanks, yes Django does seem to be threaded by default - not clear why then there is a difference in the output?

From the docs
`--nothreading¶
Disables use of threading in the development server. The server is multithreaded by default.`
