### ISSUE TITLE
runserver_plus: allow specification of ssl keyfile on command line

### ISSUE THREAD

**Issue by simonwiles** [django-extensions/django-extensions#1103]
I have a `.key` file which is not in the same directory as the `.crt` file, and so `runserver_plus` won't use it, and insists on trying to generate a new one in the same directory as the `.crt` file (which fails, as this directory is not world-writable).  It's a trivial addition: would you accept a PR?

**Comment by trbs** [comment]
Sure, very happy to accept a PR for this !

**Comment by domandinho** [comment]
@trbs Should be possible to set file with different name as key file than name of cert file?

**Comment by trbs** [comment]
Yes

I would like (but feel free to suggest something else / better :) ) the following options / flow:

- add `--cert-file` and `--key-file`, both are mutually exclusive with `--cert` and cannot be used at the same time.
- if `--cert` is specified and current behavior is used. (`--cert-file` and `--key-file` cannot be used when `--cert` is given and will result in an error)
- if `--cert-file` and `--key-file` are given use them as `certfile` and `keyfile`
- if `--cert-file` is specified then use that as the path to the `.crt` file. If `--key-file` is not given then automatically use `keyfile = "%s.key" % os.path.splitext(certfile)[0]`

Optionally it might be nice to also rename `--cert` to `--cert-path` and use `--cert` as an alias to `--cert-file`. Deprecating `--cert` which in turn will be removed in a later version.

**Comment by domandinho** [comment]
PR https://github.com/django-extensions/django-extensions/pull/1137

**Comment by domandinho** [comment]
@trbs In my opinion ticket can be closed because PR was merged.
