### ISSUE TITLE
runscript gives ImportError when script does not exist in all apps

### ISSUE THREAD

**Issue by rwillmer** [django-extensions/django-extensions#1111]
I use runscript to run some scripts which exist for all my apps (e.g. for logging kpis) and also for some other scripts which exist only in one app. For example, 

apps
- a
  - scripts
    - kpi.py
- b
  - scripts
    - kpi.py
    - b_only.py

In this case, if I run ```python manage.py runscript kpi```, all is well.

But if I run ```python manage.py runscript b_only```, I get 
```
ImportError: No module named 'apps.a.scripts.b_only'
Cannot import module 'apps.a.scripts.b_only': No module named 'apps.a.scripts.b_only'.
```

This used to work fine. AFAICS, this change in behaviour was introduced in 1.9.1.

Python 3.5.2, Django 1.9.13. django-extensions 1.9.1

**Comment by trbs** [comment]
Thanks for the issue report.

Could you please write a test case for this ?
Think you should be able to `tests/testapp` and maybe add a `tests/testapp/app_a` and `tests/testapp/app_b` to recreate your case. This will help to solve the issue and make sure we dont reintroduce it in the future.

**Comment by domandinho** [comment]
Pull request: https://github.com/django-extensions/django-extensions/pull/1115/

**Comment by trbs** [comment]
Thanks for the PR !
