### ISSUE TITLE
Start daily/hourly jobs at different times 

### ISSUE THREAD

**Issue by maikksmt** [django-extensions/django-extensions#1119]
I'd like a way for daily jobs to run at a set time. 
Example: 
script_a.py in daily jobs at 01:00 and 
script_b.py in daily jobs at 09:00

**Comment by xporium** [comment]
hi, 
can you tell me how to set time to run the job?
i m new in python django so i dont know how to run the job as per given time.

thanks

**Comment by trbs** [comment]
This is not really supported. Jobs in `django_extensions` are pretty basic (and regretfully old and somewhat unmaintained).

I **think** that might get away with something like changing the `when` field of an daily job to something else:
```
class SomeJob(DailyJob):
    when = "daily_at_9"
```

And then calling `runjobs` with that name from cron:

```
0 9 * * * /path/to/manage.py runjobs daily_at_9
```

**Comment by xporium** [comment]
where to configure 0 9 * * * /path/to/manage.py runjobs daily_at_9 this line

**Comment by trbs** [comment]
@xporium https://stackoverflow.com/questions/132971/what-is-the-windows-version-of-cron
