### ISSUE TITLE
show_urls fails with django 2.0beta

### ISSUE THREAD

**Issue by canni** [django-extensions/django-extensions#1122]
The `show_urls` command  fails with Django 2.0 beta due to import error.

The `urlresolvers` module was merged to `django.urls` but classes like `RegexURLPattern` where renamed to `URLPattern`

**Comment by chrickso** [comment]
i have this same issue. traceback:

Traceback (most recent call last):
  File "/Users/xxx/Dropbox/Repositories/venvs/yyy/lib/python3.6/site-packages/django_extensions/management/commands/show_urls.py", line 11, in <module>
    from django.urls import RegexURLPattern, RegexURLResolver, LocaleRegexURLResolver
ImportError: cannot import name 'RegexURLPattern'

**Comment by trbs** [comment]
git has some fixes for this, though locale urls are probably still broken.
