### ISSUE TITLE
keyczar and pycrypto

### ISSUE THREAD

**Issue by Mosho1** [django-extensions/django-extensions#1123]
`db/fields/encrypted.py` has a dependency on keyczar, which has a dependency on pycrypto, which has long since been deprecated and replaced. However, neither seem to be alive. There's an open 6 month old [issue](https://github.com/google/keyczar/issues/208) on keyczar to replace pycrypto with no feedback. 

Are there any alternatives? Are there any plans to update these dependencies?

**Comment by trbs** [comment]
There are no plans to fork or fix keyczar from our side.

Eventually we will have to remove encrypted fields as it currently exists from `django-extensions` if `keyczar` would be completely unmaintained and broken...

We are open for PR's to add other options of creating encrypted fields or patches to fix these issues if that's possible.
