### ISSUE TITLE
Import issue under Django 2.0 

### ISSUE THREAD

**Issue by shacker** [django-extensions/django-extensions#1124]
In a Django 2.0 beta project, with extensions 1.9.7, `./manage.py show_urls` throws:

```
 File ".../lib/python3.6/site-packages/django_extensions/management/commands/show_urls.py", line 13, in <module>
    from django.core.urlresolvers import RegexURLPattern, RegexURLResolver, LocaleRegexURLResolver
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

django.core.urlresolvers is replaced with django.urls in 2.0

**Comment by trbs** [comment]
Please test with the master version in github. Following https://github.com/django-extensions/django-extensions/issues/1122 there (partial) patches for this issue should be in git. If you still have ImportErrors please reopen the issue.
