### ISSUE TITLE
library not supported for python3

### ISSUE THREAD

**Issue by cmaliwal** [django-extensions/django-extensions#1129]
I have python 3.6.3 and django 1.9
It's working fine with 2.7 but it's not working with python3.6.

Every time i run  script its shows : 
No (valid) module for  script '  '  found.

Please have a look on this.

Thanks,
Chirag Maliwal

**Comment by trbs** [comment]
Could you please provide a PR with a test that shows the failure case ?

**Comment by cmaliwal** [comment]
I will add failure code on my github account and will let you know.

**Comment by trbs** [comment]
Also please test with `master` version, just in case this is already fixed in the upcoming release :-)

**Comment by trbs** [comment]
If you have some testing testing with `master` and if it's still broken adding a test case would be much appreciated ! ;)

**Comment by trbs** [comment]
If this is still a problem please create a PR with test case
