### ISSUE TITLE
Incorrect formatting on IPv6 address when run with -6

### ISSUE THREAD

**Issue by hingston** [django-extensions/django-extensions#1132]
When I run: `manage.py runserver_plus 8080 -6 --cert C:\cert\`

The output is:
```
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 2.0, using settings 'test.settings'
Development server is running at https://::1:8080/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CTRL-BREAK.
 * Debugger is active!
 * Debugger PIN: 129-007-922
 * Running on https://[::1]:8080/ (Press CTRL+C to quit)
```

The line `Development server is running at https://::1:8080/`

Should be `Development server is running at https://[::1]:8080/`

**Comment by trbs** [comment]
Committed a fix for this in 114a1445394352ec5b7bb2f6ec97a3dd4dee0fca
Please check with the git master version and re-open this ticket if the above patch didn't fix your issue.

Thanks for reporting !
