### ISSUE TITLE
runserver_plus fails in Django 2.0 because MIDDLEWARE_CLASSES doesn't exist anymore

### ISSUE THREAD

**Issue by dedsm** [django-extensions/django-extensions#1133]
solvable by just adding `MIDDLEWARE_CLASSES = MIDDLEWARE` in the settings.py as a temporary solution

**Comment by trbs** [comment]
Thanks should be fixed (without need for workaround) in b6951d39736fc1d13e667c3a11f52f5c1764767d

Could you please test the fix in git master ?

Then we can create a new release to fix this in a release version.

**Comment by dedsm** [comment]
I'm sorry, your reply got lost in the mail, I've just tested against latest master and it works, thanks!
