### ISSUE TITLE
AttributeError: 'list' object has no attribute 'write'

### ISSUE THREAD

**Issue by sridharchary** [django-extensions/django-extensions#1151]
self.render_output_pydot(dotdata, **options)
  File "/usr/local/lib/python3.4/dist-packages/django_extensions/management/commands/graph_models.py", line 151, in render_output_pydot
    graph.write(output_file, format=format)
AttributeError: 'list' object has no attribute 'write'

I am trying to excecute command python3 manage.py graph_models --pydot -a -g -o my_proj_visual.png
django version 1.7
pydot==1.2.4
pyparsing==2.2.0

**Comment by trbs** [comment]
Thanks for reporting your issue.

I've tested the command and It works for me with: Python 3.6, Django 1.11, Django Extensions 1.9.9 and pydot 1.2.3

Your Django version 1.7 is not supported anymore and looking at the line numbers of Django Extensions I am guessing you might also be using an older version as well ?

Please try to upgrade and if it still fails please reopen the ticket.
