### ISSUE TITLE
sqldiff -a will erroneously include diffs for proxy models

### ISSUE THREAD

**Issue by wahuneke** [django-extensions/django-extensions#1153]
Unless I'm misunderstanding something about proxy models, I think they probably should not be included in the sqldiff output.  The SQL does render correctly (using the real table name) but it duplicates ALTER statements that are already printed out by the real (non-proxy) model.

Is this a mistake or something intentional?  Is there a use case I'm not thinking of?

**Comment by trbs** [comment]
I think your right, proxy models should probably be ignored.

Would you be able to create a PR for this ?

**Comment by domandinho** [comment]
https://github.com/django-extensions/django-extensions/pull/1157

**Comment by trbs** [comment]
@wahuneke could you check if this test covers your use case as well ?

For now the tests seem to work fine:
```
$ ./venv3/bin/python manage.py sqldiff -a --include-proxy-models|grep -i post
-- Model: PostWithTitleOrdering
-- Table missing: django_extensions_post
-- Model: Post
-- Table missing: django_extensions_post

$ ./venv3/bin/python manage.py sqldiff -a |grep -i post
-- Model: Post
-- Table missing: django_extensions_post
```

If there is still an issue please open a new ticket (or reopen this one) and include a reproducible test case so we can fix the issue.

Thanks !
