### ISSUE TITLE
Please add option for pygment to use dark background colors

### ISSUE THREAD

**Issue by karolyi** [django-extensions/django-extensions#1159]
Hey,

I'm using the SQL printing option of `shell_plus`, and at night when I code, flux removes the blue colors from my display. This results of the SQL commands displayed in dark blue, unreadable on a dark background, which I have in my Terminal.

Here's the culprit:

https://github.com/django-extensions/django-extensions/blob/ad2913ffe4c878723b9c490e6b83d4d9250abfbd/django_extensions/management/commands/shell_plus.py#L383-L387

If you could replace line 386 to `pygments.formatters.TerminalFormatter(bg='dark')`, or at least add a configurable value for having a dark background, that would be really appreciated. Now, I monkeypatched it by hand, so at least I can see the SQL results.

**Comment by trbs** [comment]
Thanks for the suggestion.

With the above commit you should now be able to configure the pygments formatter in `settings.py` with:

```
SHELL_PLUS_PYGMENTS_FORMATTER_KWARGS = dict(bg='dark')
```

Please test this and let me know if there any issues ;-)

**Comment by karolyi** [comment]
@trbs thanks for the prompt response.

just tested it, LGTM! permission to rollout granted :)

**Comment by karolyi** [comment]
I can haz release?

**Comment by trbs** [comment]
Thy might.

should be out shortly :-)
