### ISSUE TITLE
 Graph Models: additionnal options to make the result more readable?

### ISSUE THREAD

**Issue by ddahan** [django-extensions/django-extensions#1163]
Would it be possible to add some options to the excellent Graph Models extensions to help generate more readable graphs?

- **A way to remove abstract classes from the result**. As I'm using [Django model behaviours](http://blog.kevinastone.com/django-model-behaviors.html), basically, all my models inherit from many abstract classes. In the end, the generated graph is pretty impossible to understand.

- **A way to have models without attributes**. In the same spirit, if I want an overview of my relations between my models, without entering the details, that could be very usefull.

IMHO, the perfect graph model documentation for a  reasonable complex Django project would be 1 + 2 :
1) An detailed app by app view, with full models described. If we have 10 apps, we have 10 graphs. (today we can do it)
2) A full project view with all models from all apps, but without model attributes, and without abstract classes (today we can **NOT** do it).

Thanks.

**Comment by ddahan** [comment]
My mistake, it is possible.
I thought the examples in the doc were the only options...

**Comment by trbs** [comment]
If you can, then a PR for improvements on the documentation would be much appreciated.

**Comment by ddahan** [comment]
After reading it again, not sure the documentation is bad.
I just thought the showed examples were comprehensive, but they're not.
