### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by spapanik** [django-extensions/django-extensions#1167]
I found this deprecation warning after upgrading to python 3.6 (using django extensions 1.9.9)

/usr/local/lib/python3.6/site-packages/django_extensions/collision_resolvers.py:207: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  assert len(inspect.getargspec(collision_resolver_class.resolve_collisions).args) == 2, \

**Comment by domandinho** [comment]
PR: https://github.com/django-extensions/django-extensions/pull/1181

**Comment by trbs** [comment]
Thanks !
