### ISSUE TITLE
Do not include "typing" lib in `install_requires` if Python 3.5+

### ISSUE THREAD

**Issue by tdruez** [django-extensions/django-extensions#1168]
From https://pypi.python.org/pypi/typing:
> NOTE: in Python 3.5 and later, the typing module lives in the stdlib, and installing this package has NO EFFECT.

We should not force the install of `typing` for Python version 3.5 or later.

I'm suggesting the following change:

```
install_requires = ['six>=1.2']
if sys.version_info < (3, 5):
    install_requires.append('typing')

setup(
    [....]
    install_requires=install_requires,
    [....]
)
```

@trbs let me know what you think.

**Comment by trbs** [comment]
Looks good. Could you make a PR for this ?
Thanks !

**Comment by tdruez** [comment]
@trbs sure thing, PR @ https://github.com/django-extensions/django-extensions/pull/1170

**Comment by luzfcb** [comment]
@trbs this only work if i install django-extensions with pip `--no-binary`, I other words, when I force pip do not use the `whell` package

```
pip install django-extensions -U --no-binary :all:
```

my environment
```
Python 2.7.11 (default, Mar  8 2016, 09:32:11) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip, setuptools, wheel, sys
>>> sys.version_info
sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0)
>>> pip.__version__
'9.0.1'
>>> setuptools.__version__
'38.2.4'
>>> wheel.__version__
'0.30.0'
>>>
```
I've looked for some way to fix this, but I'm still a bit confused as to the correct way to do this

The closest I found it was

https://hynek.me/articles/conditional-python-dependencies/

**Comment by luzfcb** [comment]
@hynek do you have any comments on what is the current correct way to specify conditional dependencies in a way to work with a package wheel?

**Comment by s-wirth** [comment]
@tdruez Hey man, maybe I am misreading how the setup.py works, but it seems to me like you are currently installing typing only if the Python Version is *smaller* than 3.5. 
https://github.com/django-extensions/django-extensions/pull/1170/files#diff-2eeaed663bd0d25b7e608891384b7298R124

**Comment by luzfcb** [comment]
@s-wirth the `typing` module was included in the standard library in Python 3.5, so it is not necessary to install it in python 3.5 or higher, because it is already installed

**Comment by s-wirth** [comment]
@luzfcb Ah yeah that makes sense. Thank you for the answer :)

**Comment by hynek** [comment]
@luzfcb the most correct way is currently PEP 508 but the most compatible way appears to be the using `extras_require`. It strictly depends on how old pip/setuptools you want to support.

**Comment by trbs** [comment]
related to https://github.com/django-extensions/django-extensions/issues/1176

**Comment by trbs** [comment]
Please test with Django Extensions 2.0.5 and hopefully that fixes the issues.

**Comment by trbs** [comment]
If there other (edge) cases where it still fails please reopen the issue.

**Comment by rcdosado** [comment]
the issue still present in 2.0.6, im using windows 7, python 3.5.0, my workaround is changing 

> from typing import (  # NOQA
>         Dict,
>         List,
>         Tuple,
>         Type,
>         Union,
> )
 to
> if False:
>     from typing import (  # NOQA
>         Dict,
>         List,
>         Tuple,
>         Type,
>         Union,
>     )

for both shells.py, and import_subclasses.py
