### ISSUE TITLE
cannot import name 'opentype' python 3.6

### ISSUE THREAD

**Issue by felipe3dfx** [django-extensions/django-extensions#1172]
After update ubuntu dependencies and run shell_plus command it shown this warning:

I have installed service_identity package (sudo pip install service_identity) but not works

```
$ python3.6 manage.py shell_plus
```
Warning message:

> :0: UserWarning: You do not have a working installation of the service_identity module: 'cannot import name 'opentype''.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

any ideas?

**Comment by trbs** [comment]
Thanks for reporting the issue.

Given the warning message it seems to have something to do with `Twisted` inside of your application. `Django Extensions` itself does not use `Twisted` so my assumption is that it's a dependency that is triggered by `shell_plus` scanning for models to load.

If you think this is something that is triggered by `Django Extensions` itself please make a reproducable test case for it (eg in a git repo or gist) and reopen this issue.
