### ISSUE TITLE
Add `generate_password` command to print a random password

### ISSUE THREAD

**Issue by gh640** [django-extensions/django-extensions#1173]
I'd like to have a command which generates a new password for user just as `generate_secret_key.py` does.

I know the existence of the command `passwd`. But there're cases when I want to get a new password without setting it to any user and it cannot be used for such cases...

**Comment by gh640** [comment]
FYI, the logic is the same as the one used by `django.contrib.auth.base_user.BaseUserManager.make_random_password`.

https://github.com/django/django/blob/40bac28faabbacd0875e59455cd80fb1dbb16966/django/contrib/auth/base_user.py#L32

**Comment by trbs** [comment]
Wondering if we should not use the `make_random_password` method directly.

So if there any updates to it we will 'automatically' use them. This could also be described in the help_text and documentation of the command.

Talking about documentation could you add a documentation for the command ?
And please also add a small test, for this command making sure then `length` option works is good enough.

Thanks !

**Comment by gh640** [comment]
@trbs thank you for your review and comment.

I see. Surely using `make_random_password` method directly should be better for future maintenance.

I modified the command and tried adding a test and a documentation for the command. I'm not experienced and I'd like you to let me know if you find anything wrong with them.

The change after some additional commits is shown at:

https://github.com/django-extensions/django-extensions/pull/1174/files

Thanks :)

**Comment by gh640** [comment]
@trbs thanks!!
