### ISSUE TITLE
clear_cache should have an --all option

### ISSUE THREAD

**Issue by costela** [django-extensions/django-extensions#1202]
Hi,

It would make life a bit easier if the `clear_cache` command had an `--all` option, to clear all caches instead of having to name them individually.

Cheers

**Comment by costela** [comment]
FYI: `django.core.cache.caches.all()` only returns those caches that have been touched at least once (tested on 1.11 and 2.0). So if we want to implement a "clear all caches", we probably (AFAIU) need to loop over `settings.CACHES` instead of relying on `django.core.cache.caches.all()`.

**Comment by trbs** [comment]
Yeah sounds really useful.

More then happy to accept a PR for this !

**Comment by costela** [comment]
@trbs happy to oblige, here you go: #1203 :)
