### ISSUE TITLE
Graph models: Use crow's-foot notation for relations instead of dots.

### ISSUE THREAD

**Issue by bendavis78** [django-extensions/django-extensions#1205]
The current graphs show cardinality (eg, many-to-one), but not modality (aka "optionality"). Cardinality and modality together convey a lot more information about the relationship between models.

Crow's-foot notation is a great way to convey more detail about relationships in basic symbols. Here's a great article on cardinality and modality. Here's a great article that covers this using crow's-foot notation:

https://www.calebcurry.com/blogs/database-design/cardinality-and-modality

![options](https://user-images.githubusercontent.com/324392/40243930-1b5e0678-5a87-11e8-810e-c14a1ce2acb5.png)

**Comment by trbs** [comment]
Thanks for the issue/report.

Would love to have more detail in the generated output, but not sure how this ticket and the link contributes towards getting this in the dot output and generated images.

We would be very happy to except a PR that enabled this for `graph_models` !
