### ISSUE TITLE
"notes" command raises exception on utf-8 content

### ISSUE THREAD

**Issue by igorcc** [django-extensions/django-extensions#1210]
Here's a proposal to workaround the issue:
```
Index: notes.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- notes.py	(date 1528976929000)
+++ notes.py	(date 1528976929000)
@@ -54,5 +54,5 @@
                             if annotation_lines:
                                 self.stdout.write("%s:" % fpath)
                                 for annotation in annotation_lines:
-                                    self.stdout.write("  * %s" % annotation)
+                                    self.stdout.write(u"  * %s" % annotation.decode('utf-8'))
                                 self.stdout.write("")
```

**Comment by trbs** [comment]
Would you mind greating a pull request with a test for the `notes` command that has `utf-8` content ?

That way we can also be sure of regressions in the future.

**Comment by igorcc** [comment]
Yes, with my pleasure.
As it is my first pull request in Github, I suppose I need to have an access to the repository with writing permission?

**Comment by trbs** [comment]
Great thanks !

You can click `fork` in the top right to fork the repository into your own account. After you commit and push the code to (your) github repo the link "create pull request" should appear.

(See https://help.github.com/articles/creating-a-pull-request-from-a-fork/ for a better explanation then mine :-) )

**Comment by trbs** [comment]
Thanks !
