### ISSUE TITLE
[Suggested feature] Create a CharNullField for allowing unique nullable CharFields

### ISSUE THREAD

**Issue by YPCrumble** [django-extensions/django-extensions#1224]
I'm looking to add a CharField to my models that is unique if it is set, but does not need to be set.

[This answer on StackOverflow](https://stackoverflow.com/a/1934764/2532070) suggests converting the CharField blank value to null to achieve this, via a `CharNullField`.

I'd be happy to create a django-extension for this field if it's something the maintainers would find useful?

Thanks for any feedback/suggestions, and thanks for maintaining this great library!

**Comment by trbs** [comment]
Just to check, are we sure this cannot be achieved right now (out of the box) with the latest Django version ?

If not I'm happy to accept a PR for such a field. Please also include tests and documentation in the PR !

**Comment by YPCrumble** [comment]
@trbs confirming this is possible using `empty_value` which automatically converts an empty string (or any empty input, `[], {}, '', (), None` to the `empty_value` set in the model. Docs: https://docs.djangoproject.com/en/dev/_modules/django/forms/fields/#CharField

Thanks!
