### ISSUE TITLE
There is no way to override created field while using .create

### ISSUE THREAD

**Issue by karankurani** [django-extensions/django-extensions#1227]
This happened when the library went from `1.5.5` to `1.5.6`.

Created field was earlier allowed to be overriden while calling .create() - so it will only pick the current time if the field wasn't set.

Once the use of `auto_now_add` was incorporated it caused this feature to stop working. Hence we cannot override the created field while creating an object without doing lot of refactoring of existing code. 

From the [documentation](https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.DateField.auto_now_add) -

`Note that the current date is always used; it’s not just a default value that you can override. So even if you set a value for this field when creating the object, it will be ignored. `

Is there any way to fix this?

**Comment by trbs** [comment]
I don't think so. Other then creating a new abstract model or overriding the fields to use `default=`...

**Comment by karankurani** [comment]
Got it. Thanks for replying! 👍

**Comment by jacobg** [comment]
```python
@contextmanager
def mock_timestamped_model(model, created=None, modified=None):
    created_field = model._meta.get_field('created') if created else None
    modified_field = model._meta.get_field('modified') if modified else None
    if created:
        created_field.auto_now_add = False
        created_field.default = created
    if modified:
        modified_field.auto_now = False
        modified_field.default = created
    yield
    if created:
        created_field.auto_now_add = True
        created_field.default = None
    if modified:
        modified_field.auto_now = True
        modified_field.default = None
```
