### ISSUE TITLE
Preload initial commands in config. 

### ISSUE THREAD

**Issue by zelds** [django-extensions/django-extensions#1240]
Hi. Is there the way to run commands on every shell_plus init ?
Thanks.
Example:
```
%load_ext autoreload
%autoreload 2
```

**Comment by trbs** [comment]
One way of doing that would be to create an `ipython` profile that executes those commands and then load that profile by using `IPYTHON_ARGUMENTS` in `settings.py` or using it as an environment variable.

https://ipython.org/ipython-doc/3/config/intro.html

**Comment by trbs** [comment]
Btw if this works for you please consider creating a Pull Request to update the documentation and explain the steps you took with an example so other people can find that later 👍

**Comment by danihodovic** [comment]
I've managed to add these lines to the default profile at `~/.ipython/profile_default/ipython_config.py`
```
c = get_config()
c.InteractiveShellApp.extensions = ['autoreload']
c.InteractiveShellApp.exec_lines = [
    '%autoreload 2',
    'print("Hello world!")',
]
```

autoreload works
```
In [1]: %load_ext autoreload
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
```

however `c.InteractiveShellApp.exec_lines` are never executed, any ideas why?

**Comment by danihodovic** [comment]
Update:

it seems to work with `manage.py shell_plus --ipython`, but not with `manage.py shell_plus --ptipython`, I'm investigating as to why...
