### ISSUE TITLE
AttributeError: '_thread._local' object has no attribute 'wsgi_tb'

### ISSUE THREAD

**Issue by elcolie** [django-extensions/django-extensions#1256]
I use `django-cookies` create the project. And this is `Debug=True` will raises this error.

```bash
django_1        | Traceback (most recent call last):
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 66, in __call__
django_1        |     return self.application(environ, start_response)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
django_1        |     response = self.get_response(request)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
django_1        |     response = self._middleware_chain(request)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
django_1        |     response = response_for_exception(request, exc)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
django_1        |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
django_1        |     return debug.technical_500_response(request, *exc_info)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 31, in null_technical_500_response
django_1        |     elif tld.wsgi_tb:
django_1        | AttributeError: '_thread._local' object has no attribute 'wsgi_tb'
```

Is it related to `django-extensions`?

**Comment by trbs** [comment]
Yes it regretfully is :( 

Related to https://github.com/django-extensions/django-extensions/pull/1228 

I added patch in c03f3abd1d40ae54ea903834694bf20a198b5fdd

@elcolie does the above patch work for you ?
@jhselvik could you take a look why this is happening ? and if the patch is good

**Comment by elcolie** [comment]
I works. Thank you very much
`-e git+git@github.com:django-extensions/django-extensions.git@master#egg=django-extensions`

**Comment by jhselvik** [comment]
Uhg, silly bug to get through. I believe initializing the attribute `wsgi_tb` to None on the `threading.local()` will also fix this if you do not want to catch AttributeError as in your patch.

```
tld = threading.local()
tld.wsgi_tb = None
```

Should work, but I haven't tested it. @trbs I can take a look on Monday though if you'd like an alternative to the patch that closed this issue?

**Comment by trbs** [comment]
Added your initialization patch as well a7ecc7c2d58cfbf9115877daecc507a30778e07b

I am thinking of keeping both :-) it's not unreasonable that something might happen in walking the tb frames or with the thread local (even though it shouldn't) and raising an error for the fix is probably more confusing then at that point just letting the old situation exist...

**Comment by jhselvik** [comment]
Yeah, both is not a bad idea since walking the tb frames is really variable. Thanks for patching it.
