### ISSUE TITLE
NOTEBOOK_ARGUMENTS settings variable does not honor --notebook-dir

### ISSUE THREAD

**Issue by dnk8n** [django-extensions/django-extensions#1261]
I have django extensions running in a docker container in an environment managed by pipenv.

Everything runs as expected except that the notebook server runs from whatever the current working directory specified in the docker entrypoint.

For more context please see this project I started today: https://gitlab.com/dnk8n/django-veva/tree/9c79818315d41976c4cebe90c3b4e2951e39d2dd

You should be able to cd to project and `docker-compose up` which would result in a django server at http://localhost:8000 and a jupyter notebook server at http://localhost:8888 (log in by copying the token from the docker-compose logs).

Normally, using conventional Jupyter I am able to overide that using the cli flag: '--notebook-dir=/path/i/want'

In the django-extensions docs I came across the NOTEBOOK_ARGUMENTS settings variable. It works for --ip and --port but does not for --notebook-dir.

Should I be setting this variable elsewhere or is this a bug?

**Comment by dnk8n** [comment]
I included a test jupyter notebook which explains what the problem is: https://gitlab.com/dnk8n/django-veva/blob/9c79818315d41976c4cebe90c3b4e2951e39d2dd/test_jupyter.ipynb

**Comment by dnk8n** [comment]
I found a workaround where I could specify the path to the pipenv environment. This allows the notebook to  run in the root of the project copied into the image. I can then specify the correct docker run command and an environment variable to specify the mounted source code if developing and it works as I wish.

Same test jupyter notebook gives the desired results: https://gitlab.com/dnk8n/django-veva/blob/0c26c4e2369fe2ec5febc76147ed9b6d5d32b9bd/test_jupyter.ipynb

To run it in the correct environment, follow the initial instructions but go to https://gitlab.com/dnk8n/django-veva/tree/0c26c4e2369fe2ec5febc76147ed9b6d5d32b9bd

**Comment by trbs** [comment]
@dnk8n I cannot access your gitlab links :-( I get a login page instead of the notebooks.

Can you post an example of how you are using `NOTEBOOK_ARGUMENTS` ?

**Comment by trbs** [comment]
I think this is a bug.

If you try the following I think it will work:
```
NOTEBOOK_ARGUMENTS = [
  '--ip', '0.0.0.0', 
  '--port', '8888', 
  '--notebook-dir', '/veva'
]
```

But I will commit a fix as well.

**Comment by trbs** [comment]
Thanks for the report !
Please try and test with master
