### ISSUE TITLE
how to run jobs as specific time?

### ISSUE THREAD

**Issue by xporium** [django-extensions/django-extensions#1269]
Hi,

in documentations given like "Jobs do not run automatically! You must either run a job manually specifying the exact time on which the command is to be run, or use crontab"

but after implement logic how to run daily and hourly jobs as per given time and date(how to set time and date to run the job)?

once it run manually than it will work until application exit?

Thanks and your help will be very appreciable .....

**Comment by trbs** [comment]
I'm not entirely sure what your asking. 

`Jobs` in `django-extensions` is a really simple tool (and somewhat unmaintained).

You must set it up in *cron* or another scheduler as described in https://django-extensions.readthedocs.io/en/latest/jobs_scheduling.html

(If the documentation is not clear about this then any help in the form of a PR is appreciated)

**Comment by xporium** [comment]
i mean in document mention "Jobs do not run automatically! You must either run a job manually specifying the exact time on which the command is to be run, or use crontab" 

but i dont know how to do make service in autorun?


please see below code

from django_extensions.management.jobs import DailyJob
class Job(DailyJob):
    help = "My sample job."

    def execute(self):
        print('this is test....................')


i want run execute function in everyday at 1 AM so what to do?

crontab is not working in windows...

**Comment by trbs** [comment]
Then you should use whatever the equivalent is of a scheduler like `cron` on windows.
