### ISSUE TITLE
Windows path  not found for django_crontab

### ISSUE THREAD

**Issue by xporium** [django-extensions/django-extensions#1270]
Hello All,

Jobs do not run automatically! You must either run a job manually specifying the exact time on which the command is to be run, or use crontab:

so m using crontab for autorun....

I am trying to use django_crontab to run repetitive task. I want to insert
records to database on a particular time. Also, I am in process of learning
django hence I m trying to reach every aspect of django.

The issue i am facing i m able to configure django_crontab but its not able
to find cron.py. I am using windows 10 and i believe it must be something
else for windows

CRONJOBS = [
     ('*/2 * * * *', 'test.test_app.cron.my_scheduled_job')
]

testis my project directory.

When I run the command manage.py crontab add it gives error saying "The
system cannot find the path specified."

I am using Windows.

Please help..

**Comment by trbs** [comment]
I think you need to ask this question over at the nice folks of https://github.com/kraiz/django-crontab
