### ISSUE TITLE
runserver_plus --cert-file and --key-file should not expect any extensions

### ISSUE THREAD

**Issue by bartekbrak** [django-extensions/django-extensions#1282]
`runserver_plus` allows specifying self-generated SSL cert and key files (that I generate with [mkcert](https://github.com/FiloSottile/mkcert/blob/master/README.md)) but requires via [determine_ssl_files_paths](https://github.com/django-extensions/django-extensions/commit/64d9a55ea39251954f3f546d1df15c0872d6e51d#diff-3d83f4d549c1e3b62522a07d357cea88R402) that these have extensions `crt` and `key`. Those extensions are conventions only and should not be required, my certs end with `.pem`, this causes `runserver_plus` to silently create its own certs:

```
$ ls -1 *pem *key *crt
$ touch cert.pem key.pem
$ manage.py runserver_plus --cert-file cert.pem --key-file=key.pem
# output skipped
$ ls -1 *pem *key *crt
cert.crt
cert.key
cert.pem
key.pem
```

I'd rather not be forced or at least be informed what happened.
I can probably provide a PR if this case is convincing. Easy fix. 
If possible, please provide reasoning behind the current behaviour.

**Comment by bartekbrak** [comment]
Additionally, the help misleads:
```
        cert_group.add_argument('--cert-file', dest='cert_path', action="store", type=str,
                                help='SSL .cert file path. If not provided path from --key-file will be selected. '
                                     'Either --cert-file or --key-file must be provided to use SSL.')
```
not `SSL .cert` but `SSL .crt`, `manage.py runserver_plus --cert-file cert.cert` will create `cert.crt  cert.key`.

**Comment by trbs** [comment]
Happy to accept a PR for this.

Think this stems from that in earlier days only `--cert`(-path) was available.
I would not mind cleaning this up and making it work like any other application where you can specify your own certs :-)

**Comment by domandinho** [comment]
PR: https://github.com/django-extensions/django-extensions/pull/1347

**Comment by domandinho** [comment]
@trbs 
Can we close this issue? PR is merged.
