### ISSUE TITLE
truncate_letters templatetag is no longer needed

### ISSUE THREAD

**Issue by kuter** [django-extensions/django-extensions#1302]
Django has truncatechars https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#truncatechars which provides exact same functionality.

I've created PR #1303

**Comment by trbs** [comment]
Yes. Though instead of removing it outright i would like to do this by deprecating the filter first (with a warning). 
Then removing it later :-)

**Comment by kuter** [comment]
@trbs can we add deprecation warning and import django truncatechars whitin old templatetag file ? like:

`
from django.template.defaultfilters import truncatechars as truncate_letters
`

**Comment by trbs** [comment]
Is the behaviour the same ? If so thats a great solution !

**Comment by kuter** [comment]
@trbs take a look #1303 .. I use django build in templatetag and show DeprecationWarning on truncate_letters call.

**Comment by trbs** [comment]
closing this since we are going to merge #1303
