### ISSUE TITLE
`ModificationDateTimeField` instance with name other than "modified" does not work with the `update_modified` option.

### ISSUE THREAD

**Issue by koliber** [django-extensions/django-extensions#1322]
The code that handles the `update_modified` option assumes that the field name of the `ModificationDateTimeField` name is `modified`:

https://github.com/django-extensions/django-extensions/blob/89baa8837f5109f515a7062884cc2a17d697e43b/django_extensions/db/fields/__init__.py#L402-L405

**Comment by trbs** [comment]
Could you maybe write a test for this in our tests suite ?

**Comment by koliber** [comment]
I will, and can probably even fix it, but need to find the time. I wanted to get it logged in the correct place first.
