### ISSUE TITLE
How do I use IDLE with shell_plus

### ISSUE THREAD

**Issue by wyattbiker** [django-extensions/django-extensions#1328]
Hi, I like using IDLE as my django shell, sometimes. I am running it on linux. Here is the shell startup. Any suggestions how to achieve this?

```
(dj) standing:~/public_html/mysite$ cat /usr/bin/idle 
#! /usr/bin/python3

from idlelib.pyshell import main
if __name__ == '__main__':
    main()
```

**Comment by trbs** [comment]
Could you please try with latest master (specially commit ea14ec69887cd9de09b0dfc0e946344797080da3 ) and see if this works for you ?

```
./manage.py shell_plus --idle
```

<img width="697" alt="image" src="https://user-images.githubusercontent.com/65552/53688514-6f3fca00-3d45-11e9-89df-57bc580c4f33.png">

**Comment by wyattbiker** [comment]
Well it worked, sort of,  but had to manually move folder. The git clone and setup in the docs (see below) do not work because it created an .egg folder in site-packages.
```
$ git clone git://github.com/django-extensions/django-extensions.git
$ cd django-extensions
$ python setup.py install
```

Here is what I had to do to make it work.

- Rename the old package in site-packages, 
- Drag the django_extensions from .egg folder to site-packages.

So almost there. Thanks!

![image](https://user-images.githubusercontent.com/930478/53690797-49172b80-3d3f-11e9-8edc-86fc5e3b0e0e.png)


![image](https://user-images.githubusercontent.com/930478/53690969-9a74ea00-3d42-11e9-8514-6f61a43b56fa.png)

**Comment by trbs** [comment]
That does not sound like it has anything to do with `Django-Extensions` just your local setup.

Cool, it will make it into the next release and then you should just be able to `pip install` it.

**Comment by wyattbiker** [comment]
Thanks for the quick fix.
