### ISSUE TITLE
sqldiff -a creates KeyError

### ISSUE THREAD

**Issue by simanto604newscred** [django-extensions/django-extensions#1333]
https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/sqldiff.py#L495

`
  File "/Users/MAK/Envs/lifemed3/lib/python3.7/site-packages/django_extensions/management/commands/sqldiff.py", line 492, in find_index_missing_in_model
    if constraint['index'] and constraint['type'] == 'idx' and constraint['orders'] and field.unique:
KeyError: 'orders'

`

**Comment by trbs** [comment]
Could you add a reproducible example or better yet a test case ? this also helps to avoid the same issue(s) cropping up in the future again.

**Comment by simanto604newscred** [comment]
I can see that:
ipdb> constraint
{'columns': ['user_id'], 'primary_key': False, 'unique': False, 'check': False, 'foreign_key': None, 'index': True, 'type': 'idx'}
ipdb> table_name
'django_admin_log'
ipdb> table_constraints
{'PRIMARY': {'columns': ['id'], 'primary_key': True, 'unique': True, 'index': True, 'check': False, 'foreign_key': None, 'type': 'idx'}, 'content_type_id_refs_id_93d2d1f8': {'columns': ['content_type_id'], 'primary_key': False, 'unique': False, 'index': False, 'check': False, 'foreign_key': ('django_content_type', 'id')}, 'user_id_refs_id_c0d12874': {'columns': ['user_id'], 'primary_key': False, 'unique': False, 'index': False, 'check': False, 'foreign_key': ('auth_user', 'id')}, 'django_admin_log_6340c63c': {'columns': ['user_id'], 'primary_key': False, 'unique': False, 'check': False, 'foreign_key': None, 'index': True, 'type': 'idx'}, 'django_admin_log_37ef4eb4': {'columns': ['content_type_id'], 'primary_key': False, 'unique': False, 'check': False, 'foreign_key': None, 'index': True, 'type': 'idx'}}


FYI: We are in the process of migrating to Django 2.1.7

Let me know if you need any more context

**Comment by trbs** [comment]
Are you using `mysql` by any chance ?

**Comment by simanto604newscred** [comment]
Yes I am

**Comment by trbs** [comment]
`mysql` does not seem to have or at least does not introspect `orders` (sorting order) for indexes.

I can fix the `KeyError` but I have no `mysql` database to test the correct functioning of the result...

Please check with latest version in github (specifically f58fbebba6ddceebc321cb8d717a161b44186aab)

**Comment by simanto604newscred** [comment]
I think need to install it from git to get the change, isnt it?

**Comment by trbs** [comment]
Awesome !

I'll try to do a new release over the next few days so you don't need to install from master.
