### ISSUE TITLE
Tests should be not distrubited with package

### ISSUE THREAD

**Issue by kuter** [django-extensions/django-extensions#1334]
Issue related to PR #1332. I quite sure that tests should not be included into package. Django, DRF does not provide tests with package.

**Comment by jayvdb** [comment]
Django does include tests in its sdist.

They shouldnt appear in the wheel, and shouldnt be installed.  If the current setup.py logic is including them in either, I'll be happy to fix that


The setup.py logic was a bit convoluted, so I didnt do a detailed check of all paths, but it didnt look like it was going to put them into the wheel or install them.

**Comment by kuter** [comment]
@jayvdb you're right django-extensions is distibuted as a wheel package and tests don't appear there.

BTW. They exists when package created via command python setup.py sdist

**Comment by trbs** [comment]
When I install the sdist package they do not get installed for me.

```bash
$ python3 -m venv venv-test
$ /venv-test/bin/pip install dist/django-extensions-2.1.6.tar.gz
Processing ./dist/django-extensions-2.1.6.tar.gz
Collecting six>=1.2 (from django-extensions==2.1.6)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: six, django-extensions
  Running setup.py install for django-extensions ... done
Successfully installed django-extensions-2.1.6 six-1.12.0
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ find venv-test/lib/python3.7/site-packages | grep manage.py
$ find venv-test/lib/python3.7/site-packages | grep tests
venv-test/lib/python3.7/site-packages/pip/_vendor/webencodings/__pycache__/tests.cpython-37.pyc
venv-test/lib/python3.7/site-packages/pip/_vendor/webencodings/tests.py
$
```

But they are in the sdist bundle:
```
$ tar tf dist/django-extensions-2.1.6.tar.gz | grep manage.py
django-extensions-2.1.6/manage.py
$ tar tf dist/django-extensions-2.1.6.tar.gz | grep tests
django-extensions-2.1.6/tests/
django-extensions-2.1.6/tests/__init__.py
django-extensions-2.1.6/tests/collisions/
django-extensions-2.1.6/tests/collisions/__init__.py
django-extensions-2.1.6/tests/collisions/apps.py
django-extensions-2.1.6/tests/collisions/models.py
django-extensions-2.1.6/tests/management/
django-extensions-2.1.6/tests/management/__init__.py
...
django-extensions-2.1.6/tests/testapp_with_template_errors/
django-extensions-2.1.6/tests/testapp_with_template_errors/__init__.py
```

**Comment by trbs** [comment]
Does this mean it works as expected ?

**Comment by kuter** [comment]
> Does this mean it works as expected ?

looks good for me .. I'm just not sure if sdist bundle should contains tests .. I used to remove tests from bundle via `recursive-exclude` in MANIFEST.in file - thats why I'm asking.

**Comment by trbs** [comment]
Think the benefit of including the tests in the source bundle but not having them installed when installing said source bundle with `pip`/`setup.py` is that downstream distributions can use them to test their packages. Think this is your usecase @jayvdb right ?

**Comment by trbs** [comment]
(please reopen in case I am missing something here :-) )
