### ISSUE TITLE
Option to hide edge labels

### ISSUE THREAD

**Issue by dms-cat** [django-extensions/django-extensions#1343]
The edge labels take up quite a bit of space, and should be easy to remove from the Dot output. This would be handy to produce tighter graphs.

**Comment by trbs** [comment]
Would be happy to accept a PR which adds an option to remove them from rendering

**Comment by karranb** [comment]
Hi @trbs, what do you think about this approach. #1367

**Comment by trbs** [comment]
Hi @karranb, thanks for creating the PR !
Useful indeed :-)

I added small request to the PR, basically adding tests and few lines in the docs, after that I will merge it.
