### ISSUE TITLE
support  django-postgres-extra in reset_db

### ISSUE THREAD

**Issue by belonesox** [django-extensions/django-extensions#1344]
There are project https://github.com/SectorLabs/django-postgres-extra/
that provided additional postgres specific features with backend 'psqlextra.backend'

Unfortunately, reset_db did not recognize this backend as one of the postgresql backends 
(only 'postgresql', 'postgresql_psycopg2', 'postgis') 

Probably this can be fixed in the line
https://github.com/django-extensions/django-extensions/blob/b63a4dc17c8f7086aa048cb8410559079094e744/django_extensions/management/commands/reset_db.py#L134
but with ugly patch, adding 'backend' to list.

Better patch also engine detection in https://github.com/django-extensions/django-extensions/blob/b63a4dc17c8f7086aa048cb8410559079094e744/django_extensions/management/commands/reset_db.py#L70

**Comment by trbs** [comment]
Please look at latest master.

You should now be able to control which names count as engines in `reset_db`.

Use `settings.DJANGO_EXTENSIONS_RESET_DB_POSTGRESQL_ENGINES` to extend the list, eg:

```
DJANGO_EXTENSIONS_RESET_DB_POSTGRESQL_ENGINES = (
     'django.db.backends.postgresql',
     'django.db.backends.postgresql_psycopg2',
     'django.db.backends.postgis',
     'psqlextra.backend',
)
```

Hope this help.
