### ISSUE TITLE
Jupyter Kernel installed under Library/Jupyter  rather than virtual environment

### ISSUE THREAD

**Issue by dustinmichels** [django-extensions/django-extensions#1378]
I have a Django project that uses pipenv to manage its virtual environment, in which I have installed Jupyter and "django-extensions" and run `/manage.py shell_plus --notebook`.

It seems the "django_extensions" jupyter kernel gets installed in `Library/Jupyter/kernerls`, making is accessible to other jupyter projects. By contrast, it seems like the python3 kernel is installed within the virtual environment.

Here is what I see when running `jupyter kernelspec list`, inside my project `cc-dashboard` with its respective pipenv activated.

```bash
jupyter kernelspec list

Available kernels:
  django_extensions    /Users/dustinmichels/Library/Jupyter/kernels/django_extensions
  python3              /Users/dustinmichels/.local/share/virtualenvs/cc-dashboard-15QDmC0q/bin/../share/jupyter/kernels/python3
```

Is there a way to get the kernel to install itself under the virtual environment's `share/jupyter` folder instead? Thanks.

## Specs

- **django** -- version: 2.2.1
- **django-extensions** -- version: 2.1.7
- **jupyter** -- version: 4.4.0
- **python** -- version: 3.7.3
- **pipenv** -- version 2018.11.26
- **OS** -- MacOS Mojave (10.14.5)

**Comment by trbs** [comment]
The directory is taken from `user_kernel_dir` as follows:
```
ksm = app.kernel_spec_manager
kernel_dir = os.path.join(ksm.user_kernel_dir, 'django_extensions')
```

If we can also get the `kernel_dir` from the virtualenv I think it would make sense to install it in there by default and adding a command line flag to be able to force `shell_plus` to use the user globally available `user_kernel_dir` instead.

**Comment by jcquarto** [comment]
having the same problem.  Actually it tries to do this with `shell_plus` even if I don't add `--notebook`

**Comment by trbs** [comment]
@jcquarto I do not see how that should be possible `install_kernel_spec` is only called when using `--notebook`.

**Comment by trbs** [comment]
Please see https://github.com/django-extensions/django-extensions/pull/1500

**Comment by terencehonles** [comment]
> @jcquarto I do not see how that should be possible `install_kernel_spec` is only called when using `--notebook`.

@trbs this may have been related to e8d5daa06e5b6419e54d6c925f86a0adbe58ce8b
