### ISSUE TITLE
Install only single command or subset

### ISSUE THREAD

**Issue by step21** [django-extensions/django-extensions#1393]
Would it somehow be possible to use/install a command or a subset of commands without forking/adjusting the code myself? Somehow it seems like a bad idea to load this many additional management commands without checking them all.

**Comment by trbs** [comment]
As far as I know this is not possible.

Theoretically I guess one could monkey-patch Django's discovery and loading of management commands to whitelist only a specific set. But if one is concerned about vetting the code (which is a good security principle ;-) ) then not auto discovering them is not that much of an improvement... Also one needs to check all the dependencies from `django-extensions` (which we luckily don't have that many off but still) and other packages.

A long way of saying: No AFAIK this is not possible now :-)

(But happy to accept any improvement that does not create to much overhead in maintaining Django Extensions)
