### ISSUE TITLE
MySQL 8 returns upper case column names results in KeyError in dictionary

### ISSUE THREAD

**Issue by potulabe** [django-extensions/django-extensions#1394]
In function [sql_to_dict](https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/sqldiff.py#L257) SELECT result which was returned from sql-server is transformed to dictionary. Then some particular keys are supposed to be in this dict, dependent on SELECT, for example, ["column_name"](https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/sqldiff.py#L768) . But MySQL 8 ( Ver 8.0.15-6 for debian-linux-gnu on x86_64 (Percona Server (GPL), Release '6', Revision '63abd08')) returns column names in upper case, so instead "column_name" there will be "COLUMN_NAME".

Possible solution is to add .lower() to name[0] in sql_to_dict()

**Comment by trbs** [comment]
If you want to make a PR for this I think the easiest way is to override the `sql_to_diff` method in the `MySQLDiff` class to support this. 

I am not familiar with MySQL would we need to do this only for MySQL 8 or also for other mysql versions or variants (MariaDB et al) ?
