### ISSUE TITLE
PyPi package (2.1.9) containts text_tags.py in templatetags 

### ISSUE THREAD

**Issue by sha-red** [django-extensions/django-extensions#1396]
For some reason the current package for django-extensions in PyPi is double size and contains a text_tags template tag library which isn't part of this repository. Very confusing, I've got a name clash and could find the problem for some time.

If the difference between this repository and the package on PyPi is intentional please mention this appropriatly in the README.

**Comment by trbs** [comment]
Thanks for reporting this. `text_tags` should not be in the repository nor the releases at this time.

There is a new release on PyPi which fixes this.
