### ISSUE TITLE
GEOSException from runscript

### ISSUE THREAD

**Issue by asoyeur** [django-extensions/django-extensions#1401]
I have to run a old django project on a new computer. I use virtualenv with
django==1.5 and django_extensions==1.5.5
I need django_extensions to run a script (it worked on ubuntu 14.04) but on a new ubuntu19.04,
$python manage runscript -v 2 main
gives a geos exception :
GEOSException: Could not parse version info string "3.7.1-CAPI-1.11.1 27a5e771"
I do not use geolocalisation in my project. How to disable geos from django_extensions ?

**Comment by trbs** [comment]
From the top of my head there is no hard dependency on any “goes” library. 

Without more information (like a full stack trace) it’s hard to say. 

But I think there might be something in the script your running that is loading some library that is raising the ‘GEOSException’ ?

**Comment by asoyeur** [comment]
Found the solution in other post that works for me :
Edit this file: site-packages/django/contrib/gis/geos/libgeos.py
Look for the function: geos_version_info
And change this line:
ver = geos_version().decode()
With this line:
ver = geos_version().decode().split(' ')[0]

**Comment by erfanMountain** [comment]
> Found the solution in other post that works for me :
> Edit this file: site-packages/django/contrib/gis/geos/libgeos.py
> Look for the function: geos_version_info
> And change this line:
> ver = geos_version().decode()
> With this line:
> ver = geos_version().decode().split(' ')[0]

I applied this but I got the valueerror: empty separator
