### ISSUE TITLE
shell_plus --print-sql output length problem

### ISSUE THREAD

**Issue by morenice** [django-extensions/django-extensions#1408]
I found sql length problem. it doesn't confirm full sql text.

**example: select query and 3 table join**
SELECT `rs`.`aid`,
       `rs`.`bid`,
       `rs`.`cid`,
       `rs`.`did`,
       `rs`.`fid`,
       `rs`.`gid`,
       `rs`.`date`,
       `req`.`id`,
       `req`.`cid`,
       `req`.`cid2`,
       `req`.`fid`,
       `req`.`gid`,
       `req`.`date`,
       `req`.`closedate`,
       `req`.`opendate`,
       `req`.`opendate2`,
       `req`.`opendate3`,
       `req`.`opendate4`,
       `su`.`id`,
       `su`.`bid`,
       `su`.`cid`,
       `su`.`did`,
       `su`.`eid`,
       `tt`.`id`,
       `tt`.`rid`,
       `tt`.`pid`,
       `tt`.`tag1`,
       `tt`.`tag2`,
       `p`.`id`,
       `p`.`mid`,
       `p`.`jid`,
       `p`.`addr3`,
       `p`.`addr2`,
       `p`.`addr1`,
       `p`.`tag1`,
       `p`.`tag2`,
       `p`.`tag3`,
       `p`.`tag4`, `p

[Execution time: 0.431622s] [Database: default]

**Comment by trbs** [comment]
There is a configuration setting controller how long a printed SQL statement is allowed to be called: `SHELL_PLUS_PRINT_SQL_TRUNCATE = 1000`

Try settings this higher in `settings.py` and see if that helps.

(In git master version it's now also possible to disable truncation by using `SHELL_PLUS_PRINT_SQL_TRUNCATE = None`)

**Comment by morenice** [comment]
@trbs Thanks : )

**Comment by morenice** [comment]
I set two configuration in `settings.py`

SHELL_PLUS_PRINT_SQL_TRUNCATE = None
RUNSERVER_PLUS_PRINT_SQL_TRUNCATE = None
