### ISSUE TITLE
sqlcreate with postgis should behave like postgres

### ISSUE THREAD

**Issue by ekeydar** [django-extensions/django-extensions#1411]
if you run python manage.py sqlcreate with postgis, you get message that it falls back to sql instead of behave like postgres.

To reproduce, have settings like in this example https://docs.djangoproject.com/en/2.2/ref/contrib/gis/tutorial/#configure-settings-py

**Comment by trbs** [comment]
Thanks for the PR !

Note to self: We should use the same construct as in `reset_db` using `DEFAULT_POSTGRESQL_ENGINES` and friends :-)
