### ISSUE TITLE
Multiple Settings files

### ISSUE THREAD

**Issue by oduvan** [django-extensions/django-extensions#1422]
I'm wondering, if my app has more than one settings file, how can I add multiple Django-Shell kernels?

I didn't find this is docs and at the first glance in source code it is  impossible to do as well.

Am I miss something?

Thanks

**Comment by terencehonles** [comment]
@oduvan depending on what you're trying to do exactly my change #1509 allows you to generate more kernels. You would need to override the ENV or figure out another way to initialize your kernels. If all you need to do is specify multiple settings files I believe you would be able to use the ENV var `DJANGO_SETTINGS_MODULE` to point to the modules you want to be started as kernels.
