### ISSUE TITLE
Compability Issue with Django 3.x

### ISSUE THREAD

**Issue by Jane-1** [django-extensions/django-extensions#1424]
The following was removed in Django 3.0:
`from django.contrib.admin.templatetags.admin_static import static`

This results in a ModuleNotFoundError in `django_extensions/admin/widgets.py`
Easy fix, just replace this:
`from django.contrib.admin.templatetags.admin_static import static`
with this:
`from django.templatetags.static import static`

AFAIK, they are functionally equivalent.

**Comment by trbs** [comment]
Thanks for the report. This is fixed in master. Will do a new release soon :-)
