### ISSUE TITLE
Add Indexes for TimeStampedModel on created and modified fields.

### ISSUE THREAD

**Issue by anudeepsamaiya** [django-extensions/django-extensions#1425]
By default indexes should be added inside the Meta of abstract class.

**Comment by vstoykov** [comment]
Can you provide a PR?

**Comment by trbs** [comment]
Also in the future please provide a little bit of reasoning behind the request or PR :-)

I assume this is because that way if one overrides the class you can easily change the indexes to your liking.

Happy to accept a PR for this.

**Comment by anudeepsamaiya** [comment]
Yes, I have almost every model in my project inherit from `TimeStampedModel`. So it would be nice to have indexes in `AbstractModel` itself. 

I was waiting to raise a PR.

**Comment by trbs** [comment]
@anudeepsamaiya if you submit a PR I will try to much it as fast as I can and make a new release for you. (Next month I will be traveling a lot and probably not get to it.)

**Comment by PawelRoman** [comment]
TimeStampedModel seems to have a design flaw: it adds two non-indexed fields (created and modified) and at the same time it defines a default ordering on those fields. That results in a full table scan each time a query is run on any model that inherits from TimeStampedModel.

Since explicit is better than implicit I would simply remove the default ordering from the TimeStampedModel.

**Comment by trbs** [comment]
> TimeStampedModel seems to have a design flaw: it adds two non-indexed fields (created and modified) and at the same time it defines a default ordering on those fields. That results in a full table scan each time a query is run on any model that inherits from TimeStampedModel.
> 
> Since explicit is better than implicit I would simply remove the default ordering from the TimeStampedModel.

Not sure if it's a design flaw per see, but at the least it can be surprising to people implementing the abstract class. 

I agree... seems that explicitly defining ordering on the model using the `TimeStampedModel` is a better approach. 

Thinking that indexes might be similar and one can always make a small base abstract class of their own if it's used a lot; eg: `IndexedOrderedTimeStampedAbstractModel(TimeStampedModel)` :-)

For now I have removed the default ordering and will close this issue for now.

If there is enough need in the world to add a subclass with index support I'm happy to add that put please first make you get some decent number of developers / users to support your change before submitting a PR.

Thanks to everybody contributing to this issue !
