### ISSUE TITLE
Add option to shell_plus to ignore SystemChecks

### ISSUE THREAD

**Issue by kennell** [django-extensions/django-extensions#1438]
Suggestion: add a option to `manage.py shell_plus` that will either ignore or skip any failing `SystemCheck`s. Perhaps both.

Usage example:

```
python manage.py shell_plus --ignore-checks
# Will start the shell even if SystemChecks fail
```

```
python manage.py shell_plus --skip-checks
# Will start the shell without running SystemChecks at all
```

**Comment by trbs** [comment]
Like the idea !

And there is good news ;-) `--skip-checks` is already part of Django 3.0 https://github.com/django/django/commit/6866c91b638de5368c18713fa851bfe56253ea55

Maybe you can raise a ticket against Django to get `--ignore-checks` as well ?
