### ISSUE TITLE
graph_models doesn't generate the characters

### ISSUE THREAD

**Issue by XinyuHou** [django-extensions/django-extensions#1454]
I have django 1.11.23, django-extensions 1.7.7, and running it in a Docker container, then ssh into it and pip install pydotplus graphviz, then I ran ./manage.py graph_models -a -g -o my_project_visualized.png. It generated a file with model and relationship. But all the characters render as squares, as if they are unicode or something. All my models are English, so should be within ASCII range.

<img width="1065" alt="Screen Shot 2019-12-10 at 2 20 00 PM" src="https://user-images.githubusercontent.com/9194706/70752756-3f284d00-1d01-11ea-84b8-a6ea2bf4010f.png">

**Comment by jrd** [comment]
It's more probably a missing `pango` library in docker. This library is necessary for doing font rendering if I'm not mistaken.
This perfectly normal that this library is not installed by default in a docker and the python library cannot request for it.

**Comment by XinyuHou** [comment]
@jrd 
Thanks for the hint. Do you know which package I should install? When I try to install pydotplus and graphviz, it didn't mention anything else, and I think the dependencies should be automatically installed.

**Comment by XinyuHou** [comment]
If I just generate a dot file, it uses Helvetica as the font.

**Comment by XinyuHou** [comment]
Should have read @jrd comment more carefully. I didn't use your solution. Instead I copy the dot file into my local machine and use graphviz to convert it into svg.

**Comment by howiezhao** [comment]
If you use alpine docker image, you should `apk add ttf-freefont`. @XinyuHou
