### ISSUE TITLE
NoWhiteSpaceValidator not working

### ISSUE THREAD

**Issue by AthulMuralidhar** [django-extensions/django-extensions#1457]
- The no white space validator supplied by django-extensions is not called during form validation
- Running Django-extensions 1.7.3 with python 2.7 on django 1.8

**Comment by trbs** [comment]
Is it possible to make a PR with a test case ?
That way we have the exact problem to fix and can make sure there will be no regression in the future.

Thanks

**Comment by AthulMuralidhar** [comment]
Actually after some in-depth investigation, it is working as expected. Writing tests helped! Thanks @trbs

**Comment by trbs** [comment]
@AthulMuralidhar awesome :-)

You think your test case might be interesting to include in django-extensions as additional tests ?

**Comment by AthulMuralidhar** [comment]
@trbs  it was just some brute force testing (i'm not too proud of it haha)
