### ISSUE TITLE
No sql output from shell_plus --print-sql (Django 3)

### ISSUE THREAD

**Issue by dobsonjon** [django-extensions/django-extensions#1460]
Django==3.0.1
django-extensions==2.2.5

Settings has DEBUG=True

**Comment by trbs** [comment]
Works for me :-)

```
» ./manage.py shell_plus --print-sql
...
Python 3.7.6 (default, Dec 30 2019, 19:38:26)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import django; django.__version__
Out[1]: '3.0.2'

In [2]: User.objects.all()
Out[2]: SELECT "auth_user"."id",
       "auth_user"."password",
       "auth_user"."last_login",
       "auth_user"."is_superuser",
       "auth_user"."username",
       "auth_user"."first_name",
       "auth_user"."last_name",
       "auth_user"."email",
       "auth_user"."is_staff",
       "auth_user"."is_active",
       "auth_user"."date_joined"
  FROM "auth_user"
 LIMIT 21


Execution time: 0.000113s [Database: default]

...
```

If you still have problems, please reopen the ticket but with more information and a reproducable use-case.

**Comment by rdmurphy** [comment]
I'm actually seeing this as well. Not sure how far I'd have to go to create something reproducible though. 🤔 Whatever it is, I think it was affecting `django-debug-toolbar`'s `debugdbshell` too because that's where I first saw this happening. Possibly related to Python 3.8 if that's what you were also using @dobsonjon?

```
Django==3.0.2
django_extensions=2.25

Python @ 3.8.0
```

**Comment by rdmurphy** [comment]
Well, I just spun of a quick project and did a similar test as @trbs and it worked fine. O.o

Same versions as I listed above.

**Comment by rdmurphy** [comment]
Okay, I've traced it a little further — it works with SQLite, but *does not* work with with PostgreSQL. Do you see the same @trbs in your test case if you swap in Postgres as the DB?

**Comment by dobsonjon** [comment]
I'm using Python 3.7.2 and I'm using Postgres (psycopg2-binary==2.7.7) as well. 

The --print-sql flag was working as expected for me when I was on Django 2.2 and django_extensions 2.1.6.

**Comment by dobsonjon** [comment]
Just confirming what @rdmurphy already found. I made a new django project with Python 3.7.2 and the following modules:

```
asgiref==3.2.3
Django==3.0.2
django-extensions==2.2.5
psycopg2-binary==2.8.4
pytz==2019.3
six==1.13.0
sqlparse==0.3.0
```

With default SQLite settings, --print-sql works as expected. However, after switching to PostgreSQL db settings, I get no SQL output:

```
% ./manage.py shell_plus --print-sql
# Shell Plus Model Imports
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import Group, Permission, User
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When, Exists, OuterRef, Subquery
from django.utils import timezone
from django.urls import reverse
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> User.objects.all()
<QuerySet [<User: a>, <User: b>, <User: c>, <User: d>, <User: e>, <User: f>, <User: g>, <User: h>, <User: i>, <User: j>, <User:k>, <User: l>, <User: m>, <User: n>, <User: o>, <User: p>, <User: q>, '...(remaining elements truncated)...']>
```

@trbs can you test with PostgreSQL and let us know if it works for you? Thanks!

**Comment by trbs** [comment]
I can reproduce the same issue with master (Python 3.7.6 + Postgresql 12.1)

**Comment by trbs** [comment]
I've added a test for it which now fails for Django 3 and PostgreSQL.
https://travis-ci.org/django-extensions/django-extensions

Next step trying to fix it. If anybody else has some additional cycles to spare any help would be much appreciated :-)

**Comment by rdmurphy** [comment]
I really have no clue how to go about this, but what I do see that changed on the Django side was in [this commit](https://github.com/django/django/commit/f7408b49a54d746db252ebc7176a67506d183a58#diff-1132e403debb86cff5e5dd3366985796), which directly mucks with the `django.db.backend.utils` file that `print-sql` reaches in to and didn't go into effect until Django 3.0. Perhaps this changed something `django-extensions` assumed about how this script worked?

**Comment by trbs** [comment]
Since it only breaks in postgresql and the test works for sqlite and mysql. I am expecting it to be somewhat related to the postgresql backend....

**Comment by trbs** [comment]
Think I got it... since 3.x the PostGreSQL driver has it's own `CursorDebugWrapper` class: https://github.com/django/django/blob/stable/3.0.x/django/db/backends/postgresql/base.py#L319

This class is not monkeypatched by `shell_plus`

**Comment by trbs** [comment]
Please test the latest fix on master

**Comment by rdmurphy** [comment]
Worked for me!

<img width="490" alt="image" src="https://user-images.githubusercontent.com/419145/72168974-11c3d300-3383-11ea-8a17-56944650f986.png">

**Comment by rdmurphy** [comment]
Worked in my original private repo too. 👍

**Comment by trbs** [comment]
Awesome, thanks for testing !

I will do a new pypi release asap.

**Comment by jacqueswww** [comment]
Awesome works again for me in 2.2.9. Thanks so much for the fix everyone involved! :-) :rocket:

**Comment by markusmo** [comment]
It only prints out the first two statements when starting the server, but nothing else then... Am I using it wrongly?

**Comment by cjproud** [comment]
I'm not sure if my issue is similar to @markusmo but it's definitely similar to #1626, when running `shell_plus` I only get a maximum of two queries output. Does anyone else see this issue?
