### ISSUE TITLE
Subclassing StaticFilesConfig results in static files not being served

### ISSUE THREAD

**Issue by robberwick** [django-extensions/django-extensions#1461]
Since Django 1.10, it is possible to subclass StaticFilesConfig in order to update the `ignore_patterns` attribute (https://docs.djangoproject.com/en/3.0/ref/contrib/staticfiles/#customizing-the-ignored-pattern-list). Doing so as per the documentation requires the replacement of `django.contrib.staticfiles` with the custom `AppConfig` class. 

However, with this configuration, runserver_plus no longer serves static files, as the test in `runserver_plus.py` for the presence of `django.contrib.staticfiles` in `settings.INSTALLED_APPS` fails.

**Comment by trbs** [comment]
Thanks for reporting this issue !

Please check again with the latest version in github.
