### ISSUE TITLE
Encoding passed to json.loads was deprecated to be removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [django-extensions/django-extensions#1465]
`encoding` parameter passed to `json.loads` was ignored and deprecated since Python 3.1 . This will be removed in Python 3.9 .

https://github.com/django-extensions/django-extensions/blob/5208677aeb0ad9225eca1ac5d6cc3b79869f3aca/django_extensions/mongodb/fields/json.py#L41

Ref : https://bugs.python.org/issue33461

**Comment by trbs** [comment]
Same goes for:

https://github.com/django-extensions/django-extensions/blob/master/django_extensions/db/fields/json.py#L31

**Comment by trbs** [comment]
In April 2020 the extended support for Django 1.11 will end. I think at this time Django will not support any Python version below 3.1 and we can safely remove it.
