### ISSUE TITLE
pipchecker imports broke with pip 20.0.2

### ISSUE THREAD

**Issue by cmackenziek** [django-extensions/django-extensions#1471]
`python manage.py pipchecker` fails with `CommandError: Pip version 6 or higher is required` with pip version 20.0.2.

It seems this is due to a failing import in line 11 of pipchecker.py:

`from pip._internal.download import PipSession`

It seems the latest versions of pip moved that class to `pip._internal.network.session`, so changing that import to `from pip._internal.network.session import PipSession` might be a (brittle) solution.

I'm not at all familiar with this code so its only speculation.

**Comment by trbs** [comment]
Thanks !
Should be fixed in ee1c7b9518a9e8f8a4c873d61a21ac7d37d46bea
