### ISSUE TITLE
ModuleNotFoundError: No module named 'django_extensions'

### ISSUE THREAD

**Issue by gDoe24** [django-extensions/django-extensions#1472]
Keep getting this error when I try to do anything with manage.py. I am able to import django_extensions when I open up a python shell, but for some reason will not work with my app even though it says "requirements filled" when I go to pip install again.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_extensions',
    'corsheaders',
    'rest_framework.authtoken',
    'core',
    'user',
    'recipe',
    'frontend',
]

Django >=2.2.6,<2.3.0
django-extensions>=2.2.5,<3.0.0

(myvenv) C:\Users\425823\Django_projects\recipe-app-api>docker-compose run app sh -c "python manage.py help"
Starting recipe-app-api_db_1 ... done
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'

**Comment by trbs** [comment]
Does sound like your docker container cannot find ‘django-extensions’. Can you import it inside of the container ? 

Also you could double check with something like ‘docker run —rm -it imagename pip freeze’ to be sure. 

(If you can post your repo and/or dockerfile we can try help debugging the issue)

**Comment by gDoe24** [comment]
https://github.com/gDoe24/recipe-app-api

Here is the repo link. I am now running into issues trying "docker run -rm -it postgres:10-alpine pip freeze"

/usr/local/bin/docker-entrypoint.sh: line 176: exec: pip: not found.

I am new to using Docker, so I'm sure I am missing something basic.

**Comment by trbs** [comment]
The PostgreSQL container won't have `pip` installed :-)

Please note that I do not own or use or have ever used any windows machines so there might be things you run or need to understand there that I do not know about. The below is all done on Mac and Linux.

Your `app` seems to be working fine for me. After adding `django_extensions` to the `INSTALLED_APPS` list I get:

```
$ docker run --rm -it test python /app/manage.py shell_plus

# Shell Plus Model Imports
from core.models import Ingredient, Recipe, Tag, User
from django.contrib.admin.models import LogEntry
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.sessions.models import Session
from rest_framework.authtoken.models import Token
# Shell Plus Django Imports
from django.core.cache import cache
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import transaction
from django.db.models import Avg, Case, Count, F, Max, Min, Prefetch, Q, Sum, When, Exists, OuterRef, Subquery
from django.utils import timezone
from django.urls import reverse
Python 3.7.6 (default, Jan 18 2020, 02:49:59)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>>
now exiting InteractiveConsole...
```

And using `docker-compose up`:

```
$ docker-compose up

Creating recipe-app-api_db_1 ... done
Creating recipe-app-api_app_1 ... done
Attaching to recipe-app-api_db_1, recipe-app-api_app_1
db_1   | The files belonging to this database system will be owned by user "postgres".
db_1   | This user must also own the server process.
db_1   |
db_1   | The database cluster will be initialized with locale "en_US.utf8".
db_1   | The default database encoding has accordingly been set to "UTF8".
db_1   | The default text search configuration will be set to "english".
db_1   |
db_1   | Data page checksums are disabled.
db_1   |
db_1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db_1   | creating subdirectories ... ok
db_1   | selecting default max_connections ... 100
db_1   | selecting default shared_buffers ... 128MB
db_1   | selecting default timezone ... UTC
db_1   | selecting dynamic shared memory implementation ... posix
db_1   | creating configuration files ... ok
db_1   | running bootstrap script ... ok
db_1   | performing post-bootstrap initialization ... sh: locale: not found
db_1   | 2020-02-04 20:26:18.474 UTC [28] WARNING:  no usable system locales were found
db_1   | ok
db_1   | syncing data to disk ... ok
db_1   |
db_1   | Success. You can now start the database server using:
db_1   |
db_1   |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1   |
db_1   |
db_1   | WARNING: enabling "trust" authentication for local connections
db_1   | You can change this by editing pg_hba.conf or using the option -A, or
db_1   | --auth-local and --auth-host, the next time you run initdb.
db_1   | waiting for server to start....2020-02-04 20:26:19.945 UTC [33] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2020-02-04 20:26:19.968 UTC [34] LOG:  database system was shut down at 2020-02-04 20:26:19 UTC
db_1   | 2020-02-04 20:26:19.973 UTC [33] LOG:  database system is ready to accept connections
db_1   |  done
db_1   | server started
app_1  | Waiting for database...
app_1  | Database connection successful!
db_1   | CREATE DATABASE
db_1   |
db_1   |
db_1   | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1   |
db_1   | 2020-02-04 20:26:20.394 UTC [33] LOG:  received fast shutdown request
db_1   | waiting for server to shut down....2020-02-04 20:26:20.398 UTC [33] LOG:  aborting any active transactions
db_1   | 2020-02-04 20:26:20.398 UTC [33] LOG:  worker process: logical replication launcher (PID 40) exited with exit code 1
db_1   | 2020-02-04 20:26:20.399 UTC [35] LOG:  shutting down
db_1   | 2020-02-04 20:26:20.415 UTC [33] LOG:  database system is shut down
db_1   |  done
db_1   | server stopped
db_1   |
db_1   | PostgreSQL init process complete; ready for start up.
db_1   |
db_1   | 2020-02-04 20:26:20.511 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2020-02-04 20:26:20.511 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2020-02-04 20:26:20.515 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2020-02-04 20:26:20.536 UTC [44] LOG:  database system was shut down at 2020-02-04 20:26:20 UTC
db_1   | 2020-02-04 20:26:20.540 UTC [1] LOG:  database system is ready to accept connections
app_1  | Operations to perform:
app_1  |   Apply all migrations: admin, auth, authtoken, contenttypes, core, sessions
app_1  | Running migrations:
app_1  |   Applying contenttypes.0001_initial... OK
app_1  |   Applying contenttypes.0002_remove_content_type_name... OK
app_1  |   Applying auth.0001_initial... OK
app_1  |   Applying auth.0002_alter_permission_name_max_length... OK
app_1  |   Applying auth.0003_alter_user_email_max_length... OK
app_1  |   Applying auth.0004_alter_user_username_opts... OK
app_1  |   Applying auth.0005_alter_user_last_login_null... OK
app_1  |   Applying auth.0006_require_contenttypes_0002... OK
app_1  |   Applying auth.0007_alter_validators_add_error_messages... OK
app_1  |   Applying auth.0008_alter_user_username_max_length... OK
app_1  |   Applying auth.0009_alter_user_last_name_max_length... OK
app_1  |   Applying auth.0010_alter_group_name_max_length... OK
app_1  |   Applying auth.0011_update_proxy_permissions... OK
app_1  |   Applying core.0001_initial... OK
app_1  |   Applying admin.0001_initial... OK
app_1  |   Applying admin.0002_logentry_remove_auto_add... OK
app_1  |   Applying admin.0003_logentry_add_action_flag_choices... OK
app_1  |   Applying authtoken.0001_initial... OK
app_1  |   Applying authtoken.0002_auto_20160226_1747... OK
app_1  |   Applying sessions.0001_initial... OK
app_1  | Watching for file changes with StatReloader
app_1  | Performing system checks...
app_1  |
app_1  | System check identified no issues (0 silenced).
app_1  | February 04, 2020 - 20:26:23
app_1  | Django version 2.2.10, using settings 'app.settings'
app_1  | Starting development server at http://0.0.0.0:8000/
app_1  | Quit the server with CONTROL-C.
```

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/65552/73784527-ebccfb00-4795-11ea-9527-55b49f3694d8.png">

I will do a PR on your repository with the couple of small tweaks I made to get it to run for me locally.

Really hope this helps you to get your application going.
For now I will close the issue here since it's not a `django-extensions` related issue by itself.
