### ISSUE TITLE
404 for static files

### ISSUE THREAD

**Issue by adambyer** [django-extensions/django-extensions#1474]
Hi. I'm trying this out for the first time. I have the server running with...

python manage.py runserver_plus --cert-file cert.crt

And can access my app at https://127.0.0.1:8000/.

But all static files are 404.

What am I missing?

Thanks.

**Comment by trbs** [comment]
I'm not sure...

When I try the following on our app in `tests/` it seems to work:
```
curl --head http://localhost:8000/static/django_extensions/img/indicator.gif
HTTP/1.0 200 OK
Content-Type: image/gif
Content-Length: 1553
Content-Disposition: inline; filename="indicator.gif"
Last-Modified: Tue, 06 Sep 2016 14:17:16 GMT
Server: Werkzeug/1.0.0 Python/3.7.6
Date: Mon, 10 Feb 2020 20:23:38 GMT
```

If for some reason it turns out that we can clarify something in the documentation (or alike) to help people tripping over this particular issue I'm happy to merge a PR for it.

**Comment by adambyer** [comment]
When using runserver_plus, the Django `static` tag produces https urls which result in 404s, but you're example uses http.
