### ISSUE TITLE
ImportError when Werkzeug is installed

### ISSUE THREAD

**Issue by jameswilliams1** [django-extensions/django-extensions#1475]
Running the following code with the latest Wekzeug installed now gives an ImportError (I believe this should now be `from werkzeug.debug import DebuggedApplication`.
https://github.com/django-extensions/django-extensions/blob/0ad61ae76b121344ccd2ad4bbf4af4e4b5b8f70e/django_extensions/management/commands/runserver_plus.py#L222

```
ImportError: cannot import name 'DebuggedApplication' from 'werkzeug' (/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py)
```

Not checked the other imports but a few are at least deprecated and may also be removed soon.

**Comment by jameswilliams1** [comment]
Update: I checked though Werkzeugs code and looks like in the move from 0.16.0->0.16.1 they dropped deprecated top level imports even though it says should have only been done in version 1.0. Raised an issue there as it is technically their problem but I doubt they will patch to re add deprecated code that is due to removed anyway so I guess it needs fixing here.

**Comment by isolationism** [comment]
Yay: Werkzeug 1.0.0 has finally dropped (after only what, a little over a decade?)
Boo: Still broken as per above.

```
$ pip list | grep -i Werkzeug
Werkzeug                  1.0.0     
$ ./manage.py runserver_plus 0.0.0.0:8000
CommandError: Werkzeug is required to use runserver_plus.
Please visit http://werkzeug.pocoo.org/ or install via pip. (pip install Werkzeug)
```

**Comment by jugmac00** [comment]
I created #1477 to fix the import error.

**Comment by trbs** [comment]
Thanks !

**Comment by mawais78** [comment]
> Yay: Werkzeug 1.0.0 has finally dropped (after only what, a little over a decade?)
> Boo: Still broken as per above.
> 
> ```
> $ pip list | grep -i Werkzeug
> Werkzeug                  1.0.0     
> $ ./manage.py runserver_plus 0.0.0.0:8000
> CommandError: Werkzeug is required to use runserver_plus.
> Please visit http://werkzeug.pocoo.org/ or install via pip. (pip install Werkzeug)
> ```

Did anyone find solution of this?

**Comment by mawais78** [comment]
> > Yay: Werkzeug 1.0.0 has finally dropped (after only what, a little over a decade?)
> > Boo: Still broken as per above.
> > ```
> > $ pip list | grep -i Werkzeug
> > Werkzeug                  1.0.0     
> > $ ./manage.py runserver_plus 0.0.0.0:8000
> > CommandError: Werkzeug is required to use runserver_plus.
> > Please visit http://werkzeug.pocoo.org/ or install via pip. (pip install Werkzeug)
> > ```
> 
> Did anyone find solution of this?

I fixed this issue by downgrading the version of **Werkzeug** from 1.0.0 to 0.16.0

**Comment by trbs** [comment]
If there is a real problem open a new issue and/or submit a PR.
