### ISSUE TITLE
shell_plus command fails (CommandError) with a SHELL_PLUS settting 

### ISSUE THREAD

**Issue by benjaminrigaud** [django-extensions/django-extensions#1547]
Hello,

When running `DJANGO_SETTINGS_MODULE=myproject.my_settings ./manage.py shell_plus`
And a `SHELL_PLUS = "ipython"` setting

it fails with `CommandError: No shell runner could be found.`

In the code: it executes the `elif SETTINGS_SHELL_PLUS` branch and it retrieves a `get_runner`

I suppose it should go there afterwards https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/shell_plus.py#L514 :thinking:

**Comment by trbs** [comment]
Could you please test d777e233a1901ff0be0ec37d5de922ad013df85d ? 

If that works for everybody I will release 3.0.2 asap.

**Comment by benjaminrigaud** [comment]
I'll do that asap !

**Comment by trbs** [comment]
Thanks

**Comment by trbs** [comment]
https://pypi.org/project/django-extensions/3.0.2/
