### ISSUE TITLE
Exclude django.contrib.* from graph

### ISSUE THREAD

**Issue by Crazor** [django-extensions/django-extensions#1586]
I'm trying to exclude djang.contrib stuff from the generated graph by running `./manage.py graph_models -a --hide-edge-labels -X 'django.contrib.*' -g -o model.png`. However, I cannot get -X to filter anything, let alone all the contrib stuff. Am I doing this wrong or is that a bug?

**Comment by trbs** [comment]
If you want to exclude `django.contrib.sessions` you could do:
```bash
$ ./manage.py graph_models -a -g -o /tmp/test.png -X Session,AbstractBaseSession && open /tmp/test.png
```

Or if you got no other models ending on "Session"
```bash
$ ./manage.py graph_models -a -g -o /tmp/test.png -X "*Session" && open /tmp/test.png
```

There is no support for using `-X 'python.module.path'` or `-X applabel.model` or excluding applabels from `-a` at the moment.

So your other option would be to not use `-a` and explicitly list all your apps.
