### ISSUE TITLE
graph_model font type difference: black bold / grey bold / grey regular

### ISSUE THREAD

**Issue by davidshumway** [django-extensions/django-extensions#1589]
![Screenshot from 2020-10-08 13-11-32](https://user-images.githubusercontent.com/3892695/95497363-d41ec580-0967-11eb-9c8b-bbcdbb64e2e0.png)

In graph_model, what is the difference in font types: black bold / grey bold / grey regular (see image).

Searched documentation and code and couldn't find a quick answer to this question. Thanks!

**Comment by trbs** [comment]
From the top of my head this is set in the templates (somewhere in `django_extensions/templates/graph_models/`)

Where:
- `black bold == relationship + blank=False`
- `grey bold == relationship + blank=True`
- `grey regular == normal field + blank=True`

Think there should also be `black regular == normal field + blank=False` and `italic` which indicate abstract fields.

**Comment by ulgens** [comment]
@trbs I think this issue shouldn't be closed without an update in docs.

**Comment by trbs** [comment]
I am open for pull request or sponsorships for this issue.
(But will not leave this issue open as a form of documentation)
