### ISSUE TITLE
Permission to use shell_plus in other projects?

### ISSUE THREAD

**Issue by tony** [django-extensions/django-extensions#1595]
Hi!

I assume this is okay to do technically, but wanted to get good graces / check ahead of time :)

I would like to have the `readline` friendly and shell-detection capability of django-extensions in a project of mine ([tmuxp](https://tmuxp.git-pull.com))

The PR of the code is https://github.com/tmux-python/tmuxp/pull/638 ([diff](https://github.com/tmux-python/tmuxp/pull/638/files))

- Is it okay if I borrow from `shell_plus.py` for this purpose?
- Is it safe to say `shell_plus.py` is MIT licensed and there's no LGPL code attached to this project?
- Separate topic: Any thoughts on separating `shell_plus`'s detection/abstraction into a separate, dependency-free library?

  There is usefulness in being able to drop into the richest debugger possible based on `site-packages`

**Comment by tony** [comment]
I suppose I should cc @trbs :)

**Comment by trbs** [comment]
Yes, yes and yes ;-)

We don't do any massive license management, audits or something... no CLA's, no long pages of documentation or other non-sense :-) It should be obvious to anybody that is contributing code to the project is placing this directly under the MIT license. `#iamnotalawyer`...

Awesome if you see value to this code in a broader scope. 

I am happy to help with moving this into a separate completely dependency-free library and then switching `Django-Extensions` to that library. (I have always been careful to try and keep Django-Extensions itself free any required dependencies as much as possible.)

(If the separate library gets going we should check with the `Django` project itself as well.. there `./manage.py shell` might also be interested...)

**Comment by tony** [comment]
@trbs Thank you!  I think I will go ahead and merge a variation of `shell_plus` into `tmuxp`!  

> I am happy to help with moving this into a separate completely dependency-free library and then switching Django-Extensions to that library. (I have always been careful to try and keep Django-Extensions itself free any required dependencies as much as possible.)

I'm interested in what that would look like and how lite we can make it.  My package is available on distributions, so if it's a python package, but also friendly to copy-paste as a file across projects (e.g. vendorize) that is very welcome

If we do want to entertain splitting the `shell_plus` abstraction into a separate module - would you like to take the first attempt? A gist? A repo? would you like me to?

I'd like to see what we could do to chisel down `shell_plus` as a `breakpoint()`-like function.

What I'm thinking of:

- vanilla (no django specific stuff)
- single file (copy-paste friendly, but also can be available on pypi as well)
- no _required_ dependencies (of course it'd check for ipython, ipdb, ptpython, bpython, etc) to be installed and potentially use them
- allows passing an explicit pdb tool
- python 2.7 support?
- should it maintain `breakpoint()` compatiblity with 3.7+?

Any thoughts on the above?

**Comment by trbs** [comment]
Hi Tony,

Sounds good :-)

Sorry I do not have much time for my OSS work as is... so regretfully have no spare cycles to take a first stab...

I would not do `Python 2.7` support unless there is a good reason for it... (some distro's still do `Python 2` ?)
The module would be probably basic enough that it could work with PY2 and PY3 might even work without something like `six` ;-)

**Comment by tony** [comment]
@trbs Here is working concept of what I have: https://github.com/tmux-python/tmuxp/blob/master/tmuxp/shell.py

(This is live in `tmuxp 1.6.1`: https://tmuxp.git-pull.com/history.html#tmuxp-1-6-1-2020-11-07)

I don't want to take up space on the issue queue with this so we can close this for now.

Here's my issue: Is a wrapping utility like this worth putting up on pypi? I'm going to continue to think this over.

> (some distro's still do `Python 2`?)

I'm trying to figure that out here: https://github.com/tmux-python/tmuxp/issues/625

Debian phases out Python 2 in "Bullseye"

FreeBSD and Gentoo are okay to drop 2.x support for

Slack/arch - not sure

Anyway if it's okay we close this, pending me making a package for a shell abstraction, I suppose?  I am also wary of adding more OSS workload for myself 😆

**Comment by tony** [comment]
I will close this for now, but if anyone else has further questions please make a new issue and refer to this if you'd like :)
