### ISSUE TITLE
ipykernel_launcher.py: error: unrecognized arguments: --notebook-dir

### ISSUE THREAD

**Issue by ovidiuc** [django-extensions/django-extensions#1602]
Running Jupyter Notebooks with Django Shell-Plus kernel causes for me the following error:

```
[I 21:51:35.652 NotebookApp] Kernel started: 47f6e877-d578-41c4-bbf5-34889c933111, name: django_extensions
usage: ipykernel_launcher.py [-h] [--debug] [--quiet] [--init] [--no-stdout] [--no-stderr] [--trio-loop] [--autoindent] [--no-autoindent] [--automagic] [--no-automagic] [--pdb] [--no-pdb] [--pprint]
                             [--no-pprint] [--color-info] [--no-color-info] [--nosep] [--secure] [--no-secure] [--profile-dir ProfileDir.location] [--profile IPKernelApp.profile]
                             [--ipython-dir IPKernelApp.ipython_dir] [--log-level IPKernelApp.log_level] [--config IPKernelApp.extra_config_file] [--ip IPKernelApp.ip] [--hb IPKernelApp.hb_port]
                             [--shell IPKernelApp.shell_port] [--iopub IPKernelApp.iopub_port] [--stdin IPKernelApp.stdin_port] [--control IPKernelApp.control_port] [-f IPKernelApp.connection_file]
                             [--transport IPKernelApp.transport] [--autocall ZMQInteractiveShell.autocall] [--colors ZMQInteractiveShell.colors] [--logfile ZMQInteractiveShell.logfile]
                             [--logappend ZMQInteractiveShell.logappend] [-c IPKernelApp.code_to_run] [-m IPKernelApp.module_to_run] [--ext IPKernelApp.extra_extension] [--gui IPKernelApp.gui]
                             [--pylab [IPKernelApp.pylab]] [--matplotlib [IPKernelApp.matplotlib]] [--cache-size ZMQInteractiveShell.cache_size] [--ident Session.session] [--user Session.username]
                             [--keyfile Session.keyfile]
                             [extra_args [extra_args ...]]
ipykernel_launcher.py: error: unrecognized arguments: --notebook-dir
[I 21:51:38.651 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
```
It keeps restarting until it dies. The error appears when opening a notebook in the browser, with the Django Shell-Plus kernel. The python 3 kernel works fine.

Commenting out this line fixes the problem: https://github.com/django-extensions/django-extensions/blob/253f151c4cb1b75164a4197a667b2840ad1db2ce/django_extensions/management/commands/shell_plus.py#L231

I'm not sure if the issue is in this repo or Jupyter Notebook or in another dependency. I've tried downgrading the following packages, with no luck: django-extensions, jupyter, notebook, ipykernel.

I do not have ```--notebook-dir``` in my configuration, but I've tried also adding it... did not change a thing.

I have the following package versions installed:
```
Django==3.1.3
ipython==7.19.0
jupyter==1.0.0
notebook==6.1.5
django-extensions==3.0.9
```
```
python 3.8.6
```

To me it looks like a bug, but maybe there is something I'm missing?

**Comment by ovidiuc** [comment]
The following day (which involved a reboot of my development docker container, inside which Jupyter Notebooks were running), it was no longer working, even with the line I mentioned commented out.

I've found that it was appending that ```--notebook-dir``` argument from ```/root/.local/share/jupyter/kernels/django_extensions/kernel.json```, which I assume was written by https://github.com/django-extensions/django-extensions/blob/51fef746bafb6cffa12a47a069f2baaa4370b74f/django_extensions/management/commands/shell_plus.py#L251 

So maybe it's an issue of defaults.

I've removed the argument from the JSON file and now it's working again, no matter if I comment out or not the line ```notebook_arguments.extend(['--notebook-dir', '.'])``` .

**Comment by terencehonles** [comment]
I couldn't reproduce this, so you may want to try upgrading your dependencies rather than downgrading them.

The next version of jupyter lab/notebook might be changing the names of some of the options, which I don't know if it will break this or not, and why I was looking into this. However, I don't have time right now to test if there is a newer release that I can test.

You may also want to test out using jupyter-lab instead of jupyter-notebook via the `--lab` option (and installing `jupyterlab`) as that is the newer and fancier notebook server.

Finally, when reporting your package versions you may want to use `pip freeze` because your issue _may_ be related to transitive dependencies. Using `jupyter --version` should print out a number of those dependencies if you feel `pip freeze` is too verbose. I'm currently running with:

```
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : 5.0.2
ipython          : 7.20.0
ipykernel        : 5.4.3
jupyter client   : 6.1.11
jupyter lab      : 3.0.7
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.2
traitlets        : 5.0.5
```

**Comment by ovidiuc** [comment]
It's been a while since I had this issue and I can no longer reproduce it myself. I've recreated my docker container many times since and probably upgraded some of the transient dependencies in the process. From the ones I've listed initially, `notebook==6.2.0` is the one I see changed.
Right now it seems to be working fine without any hacks, so the issue can be closed.
