### ISSUE TITLE
[feature request] Optional colorization for graph edges based on on_delete criteria

### ISSUE THREAD

**Issue by fjfnaranjo-wavelt** [django-extensions/django-extensions#1604]
(Admin: Feel free to remove this line, the brackets in the title, and add the actual "feature request" tag)

I've using the visualization command to study the effects of `on_delete` in one of our projects. I generate a simple graph filtering using my apps and then I color the edges in the graph using Gimp. Red is for `CASCADE` and yellow for `PROTECTED`. This allow to study deletion criteria for relations with just a quick look.

I tought that patching the mainstream project was worth it, and here I am.

Do you think it will be a good addition to the model graph command? I don't have time right now for preparing the PR but if someone think this will be useful I will try to find time in the future.

Ofc, is someone wants to do it it will be nice. A quick inspections shown that the model graph class is a good place to start. There is already a simple method a that class that prepares de json for the edges. I think extending the signature of that definition and adding the 'fillcolor' param there will be enough.

**Comment by trbs** [comment]
Happy to accept a PR for this !
