### ISSUE TITLE
django 3.1 support 

### ISSUE THREAD

**Issue by emrum** [django-extensions/django-extensions#1619]
for django 3.1.5 
i was able to identify the following issues:

the object "FieldDoesNotExist" moved to a different package:
change this: 
#from django.db.models.fields import FieldDoesNotExist
to: 
from django.core.exceptions  import FieldDoesNotExist

this is deprecated: 
#models.NullBooleanField( .. )
changed to : 
models.BooleanField( null=True  )

**Comment by emrum** [comment]
sorry, 
the "FieldDoesNotExist"
seems to be related to the  
django_tables2 package  - and appears fixed in v.2.3.4

**Comment by trbs** [comment]
no problem ;-)

good luck with your project
