### ISSUE TITLE
The drop_test_database management command does not drop all test databases when using --parallel flag

### ISSUE THREAD

**Issue by abbottc** [django-extensions/django-extensions#1636]
On a system with multiple cores, running `manage.py test --parallel --keepdb`, produces multiple test databases (one for each core):

    test_<dbname>
    test_<dbname>_1
    test_<dbname>_2
    ...etc

After running `manage.py drop_test_database`, only `test_<dbname>` gets dropped and the other test databases remain intact. This could cause a state where future test suite runs are running parts of the test suite against different versions of the database.

Would it be reasonable to update the command to drop all test databases that follow the expected naming convention, or alternatively if it's determined the command is not intended to work well with the `--parallel` flag, to document this caveat?

**Comment by trbs** [comment]
Think it's reasonable to expect the behavior as you describe.
Possibly adding switches if appropriate but I would expect that this is not needed here.

Seems what is needed is creating the logic for determining which/all test databases that need to be dropped and changing the printed warning and drop-table parts to match.

Would you mind making a PR ?

**Comment by abbottc** [comment]
Yes, I'll make a PR. Since it's known that the clone databases will always be sequentially numbered, but it's not known how many there will be, I think the best approach for the logic is just to sequentially test for the presence of each one before dropping it, and then stop when a number is reached that doesn't exist. I'll use that approach unless you prefer something else.

**Comment by abbottc** [comment]
By the way, it looks like this line in tox.ini still references Django's primary branch with the name "master" even though it was changed to "main", which means the URL will produce a 404 currently when running tox:

https://github.com/django-extensions/django-extensions/blob/master/tox.ini#L39

**Comment by abbottc** [comment]
The PR is up. 

Can you confirm whether the CI server is properly configured for this project? When I look into the errors reported back from the CI server, they appear to be configuration issues, rather than related to the PR changes.

For example, all tox tests running against pypy have errors across nearly the entire test suite, such as this example:
https://travis-ci.org/github/django-extensions/django-extensions/jobs/763905803

...or this test failure example, which reports "InterpreterNotFound: Python 3.8": 
https://travis-ci.org/github/django-extensions/django-extensions/jobs/763905792

I don't want to dig more heavily into the error report until I know whether it's legitimate.

**Comment by trbs** [comment]
If I ever have time I will move to Github actions instead of Travis... Travis seems broken (or at least breaking) for a while now...

**Comment by trbs** [comment]
I will close this in favor of the PR :-)
