### ISSUE TITLE
CommandError: Neither pygraphviz nor pydotplus could be found to generate the image. To generate text output, use the --json or --dot options.

### ISSUE THREAD

**Issue by withrvr** [django-extensions/django-extensions#1640]
in https://github.com/django-extensions/django-extensions/blob/master/README.rst

other commands are working but
from docs, this command is not working

`python manage.py graph_models -a -o myapp_models.png`

trying to run this command on the console
but this error is coming

```
CommandError: Neither pygraphviz nor pydotplus could be found to generate the image. To generate text output, use the --json or --dot options.
```

```
how to solve this error 
and on internet there is zero data to solve this error
```

https://www.google.com/search?q=python+manage.py+graph_models+-a+-o+myapp_models.png+CommandError%3A+Neither+pygraphviz+nor+pydotplus+could+be+found+to+generate+the+image.+To+generate+text+output%2C+use+the+--json+or+--dot+options.&rlz=1C1CHBD_enIN904IN904&oq=python+manage.py+graph_models+-a+-o+myapp_models.png+CommandError%3A+Neither+pygraphviz+nor+pydotplus+could+be+found+to+generate+the+image.+To+generate+text+output%2C+use+the+--json+or+--dot+options.&aqs=chrome.0.69i59j69i64l3.368j0j9&sourceid=chrome&ie=UTF-8

**Comment by trbs** [comment]
https://django-extensions.readthedocs.io/en/latest/graph_models.html
