### ISSUE TITLE
Database name set to template1, requires different permissions

### ISSUE THREAD

**Issue by nilgrant** [django-extensions/django-extensions#1645]
https://github.com/django-extensions/django-extensions/blob/5f74d761237b367348b8ae08f22ddcf9f8b76b54/django_extensions/management/commands/reset_db.py#L146-L156

**Comment by trbs** [comment]
please add some more information

**Comment by nilgrant** [comment]
What more information do you want? I believe you are using template1 db because you cannot dump a database you are connected to, but this has at least 3 major problems:
1. template1 may not exist
2. template1 may require different permissions that are not available (my issue)
3. template1 could be used for something else, probably best not to mess with it
