### ISSUE TITLE
RemovedInDjango41Warning: 'django_extensions' defines default_app_config

### ISSUE THREAD

**Issue by budziam** [django-extensions/django-extensions#1649]
The following warning is emitted when using django-extenstions along with django 3.2
```
django.utils.deprecation.RemovedInDjango41Warning: 'django_extensions' defines default_app_config = 'django_extensions.apps.DjangoExtensionsConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

I suppose it is related to the change introduced by django 3.2: https://docs.djangoproject.com/en/3.2/releases/3.2/#what-s-new-in-django-3-2

Environment:
* python 3.8
* django 3.2

**Comment by trbs** [comment]
Note to self (or others): Probably enough to add a little version check such that we do not define `default_app_config` in 3.2
