### ISSUE TITLE
Modifier matching SHELL_PLUS_PRINT_SQL_TRUNCATE

### ISSUE THREAD

**Issue by niccolomineo** [django-extensions/django-extensions#1686]
Hi, would you consider adding a modifier matching the behaviour of the `SHELL_PLUS_PRINT_SQL_TRUNCATE` setting?

Thank you.

**Comment by sshishov** [comment]
Hi @niccolomineo and @trbs , just a side note, the modifier is not working as expected in case of "NOT_TRUNCATE".

If I want to set modifier to not truncate `--sql-truncate=0` then it is initially set as `None` but then afther the check against `None` inside the function, it is reset to default. It means that using CLI option is impossible to set DO NOT TRUNCATE.

Could you please fix it? I guess the proper way to check if option is set or not and have UNSET state.
