### ISSUE TITLE
Working with Jupyter Notebooks in Visual Studio Code

### ISSUE THREAD

**Issue by fabge** [django-extensions/django-extensions#1699]
`python manage.py shell_plus --notebook` uses [IPython Notebook](http://ipython.org/ipython-doc/dev/interactive/htmlnotebook.html) in a web browser as its user interface.

Is it possible to somehow use Visual Studio Code's UI for Jupyter Notebooks? 

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/21140791/149117244-bf1669f1-a12f-4fbe-8c69-5e2536e099d5.png">

**Comment by fabiocapsouza** [comment]
Hi @fabge , I could make it work by starting the Jupyter server using `shell_plus --notebook`, then copying the URL from the terminal and pasting it in VSCode command "Jupyter: Specify jupyter server for connections > Existing"
