### ISSUE TITLE
runserver_plus does not work with werkzeug 2.1.0

### ISSUE THREAD

**Issue by hamblin** [django-extensions/django-extensions#1715]
Werkzeug just released version 2.1.0 on March 28, 2022 (4-5 hours ago as of writing this).  When using runserver_plus with that version of werkzeug, the development server cannot be started.  

As part of werkzeug 2.1.0, some previously deprecated code was removed, including werkzeug.server.shutdown
From the werkzeug [release notes](https://werkzeug.palletsprojects.com/en/2.1.x/changes/#version-2-1-0):  "Remove the non-standard shutdown function from the WSGI environ when running the development server. See the docs for alternatives."

In django-extensions runserver_plus.py - line 326 we have this:
del environ['werkzeug.server.shutdown']
which results in a KeyError since shutdown was removed

Rolling back to werkzeug <2.1 (2.0.3) resolves the issue.  

This is the first time I've looked into code for runserver_plus -- but would be happy to provide a PR if anyone with more familiarity can provide some rough guidance.  

Also, while making this change, perhaps the preceding line is from runserver_plus (if not options['keep_meta_shutdown_func']:) is also no longer needed as well...?

**Comment by bchip50** [comment]
I just commented out the two lines in runserver_plus and so far the server is working fine in debug mode.

**Comment by fortin** [comment]
> I just commented out the two lines in runserver_plus and so far the server is working fine in debug mode.

Same here, lines 325 and 326. No problems after a few hours of heavy Django testing.

**Comment by farridav** [comment]
This is affecting me too, namely because of:

```
  File "/path/to/lib/python3.9/site-packages/django_extensions/management/commands/runserver_plus.py", line 326, in make_environ
    del environ['werkzeug.server.shutdown']
KeyError: 'werkzeug.server.shutdown'
```

**Comment by fortin** [comment]
> This is affecting me too, namely because of:
> 
> ```
>   File "/path/to/lib/python3.9/site-packages/django_extensions/management/commands/runserver_plus.py", line 326, in make_environ
>     del environ['werkzeug.server.shutdown']
> KeyError: 'werkzeug.server.shutdown'
> ```

If you open `runserver_plus.py` and comment out lines 325 and 326, the problem should go away.

**Comment by cpontvieux-systra** [comment]
So a
```python
if 'werkzeug.server.shutdown' in environ:
    del environ['werkzeug.server.shutdown']
```
should fix this for all versions ?

**Comment by atleta** [comment]
There is actually a workaround for this that doesn't involve locally editing runserver_plus.py (or creating a fork): the `--keep-meta-shutdown` option seems to prevent exactly this behaviour (wanting to delete that key from `environ`). So you can just add that to the `runserver_plus` command line, until it gets fixed.
