### ISSUE TITLE
RemovedInDjango41Warning: 'django_extensions' defines default_app_config

### ISSUE THREAD

**Issue by Crocmagnon** [django-extensions/django-extensions#1743]
Hello,
The same warning as described in #1655 and #1649 is present in 3.2.0.
The if block was removed in f67ff680cd6d7264cdce05309b537ac2e1ee4a70

A fix is easy but I guess it would be best to write a test ensuring this doesn't happen again.

**Comment by Crocmagnon** [comment]
Ooh thanks, I didn't think of checking merge requests before reporting 😅

**Comment by johnnymetz** [comment]
Fixed in https://github.com/django-extensions/django-extensions/pull/1654. We can close this issue.

**Comment by Crocmagnon** [comment]
> Fixed in #1654. We can close this issue.

To be correct, it’s been fixed in #1741. #1654 predates this issue.
