### ISSUE TITLE
[runserver_plus] autoreload django 

### ISSUE THREAD

**Issue by michelematera** [django-extensions/django-extensions#1766]
Hello, 
after updating Django to version 4.1.1 I noticed that using runserver_plus on the modification of python files, the autoreload works correctly but on the modification of html files if I do not restart the server,  by reloading the web page the changes are not displayed. If I use the Django runserver command everything works fine.
I think this all depended on this: https://docs.djangoproject.com/en/4.1/releases/4.1/#templates

I wait your feedback.
Thanks!

**Comment by darkpixel** [comment]
I'll second that.

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'OPTIONS': {
            'loaders': [(
                'django.template.loaders.app_directories.Loader',
                'django.template.loaders.filesystem.Loader',
            )],
           # etc...
    }
]
```

**Comment by carltongibson** [comment]
Copying a comment from a conversation on Twitter

> You’re doing reloads somehow though I guess? If you can have your watcher trigger django.templates.autoreload.reset_loaders you’ll be good. 

https://twitter.com/carltongibson/status/1588534399561510914?s=20&t=J-EAyK34GY0uHLP67Nqnxg

**Comment by foarsitter** [comment]
There is a pull request #1775 solving this issue. Can someone test it by installing the repo through git: `git+https://github.com/foarsitter/django-extensions.git`?

I tested it only with the stat reloader and works nicely inside a docker container.
