### ISSUE TITLE
Do not show request

### ISSUE THREAD

**Issue by pazyn404** [django-extensions/django-extensions#1771]
I found out some strange behavior, image we have two models MovieSession and CinemaHall, MovieSession has foreign key to CinemaHall. So if I retrieve some MovieSession by id and then try to get attributes of CinemaHall django-extension don't show one more query, but if I have collection of MovieSession and do the same I got N + 1 problem.

**Comment by trbs** [comment]
Sorry I cannot correlate this to anything Django Extensions specific.
