### ISSUE TITLE
runserver_plus slow on Python 3.12

### ISSUE THREAD

**Issue by jgillard** [django-extensions/django-extensions#1864]
Testing on MacOS 13.6.2, and Django 4.2.11, I've seen a large slowdown to page loads, and even starting up the web server, when upgrading to Python 3.12. I went back to Python 3.11 and found that runserver & runserver_plus had roughly the same performance. On Python 3.12, runserver is again roughly the same performance as 3.11, but runserver_plus loads page much slower. I don't have a more scientific test than this anecdote.

UPDATE: I've noticed that there is very high Python CPU usage when the server is running but nothing else is happening. This appears to be at least partly caused by the watchdog reloader, as when I set the reloader to stat the CPU usage is much lower and page load speed is better. Server startup speed is still much slower than it used to be on 3.11 though, so this isn't the only issue. I've tried watchdog 3.0.0 and 4.0.0 and the issue is the same.

![image](https://github.com/django-extensions/django-extensions/assets/3770312/1f935b3c-bc45-49b5-8fc7-78037203d541)

**Comment by jgillard** [comment]
Closing as I think this may in fact be a debugpy issue: https://github.com/microsoft/debugpy/issues/1496

**Comment by areski** [comment]
I'm having the exact same issue and I'm not using debugpy.
@jgillard have you found anything to solve this?

**Comment by areski** [comment]
Ok, so it seems that I have to configure `RUNSERVERPLUS_POLLER_RELOADER_TYPE = "stat"`, 
using as previously "watchdog" make the `runserver_plus` extremely slow.
