### ISSUE TITLE
Running profile startup files in an embedded IPython instance

### ISSUE THREAD

**Issue by hekevintran** [django-extensions/django-extensions#194]
I want to use an embedded IPython shell with a user_ns dictionary and a my profile configuration (ipython_config.py and the startup files). The purpose is to run a Django shell with models imported on startup. django-extensions implements a command called shell_plus that does this:

https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/shell_plus.py

    from IPython import embed
    embed(user_ns=imported_objects)

The problem is that this does not load my startup files. embed() calls load_default_config() which I figure loads ipython_config.py. 

How do I make the embedded IPython instance run my profile startup files?

**Comment by 4dn** [comment]
Is there any progress in this, I just want to load a custom profile.

**Comment by fridiculous** [comment]
+1 on this

**Comment by trbs** [comment]
Now using ```start_ipython``` as per documentation:

```
Launch a normal IPython instance (as opposed to embedded)

    `IPython.embed()` puts a shell in a particular calling scope,
    such as a function or method for debugging purposes,
    which is often not desirable.

    `start_ipython()` does full, regular IPython initialization,
    including loading startup files, configuration, etc.
    much of which is skipped by `embed()`.
```
