### ISSUE TITLE
With ipython 0.13.1, shell_plus --notebook does auto-import models

### ISSUE THREAD

**Issue by seanbell** [django-extensions/django-extensions#297]
The django extensions do not load properly with ipython 0.13.1 (current version in `pip`):

    [IPKernelApp] Loading IPython extension: django_extensions.management.notebook_extension
    [IPKernelApp] Error in loading extension: django_extensions.management.notebook_extension

It works under ipython 0.12.

My `settings.py`:

    IPYTHON_ARGUMENTS = [
        '--ext', 'django_extensions.management.notebook_extension',
        '--profile=nbserver',
        '--debug'
    ]

All output:

    $ ./manage.py shell_plus --notebook
    [NotebookApp] Config changed:
    [NotebookApp] {'Application': {'log_level': 10}, 'BaseIPythonApplication': {'profile': u'nbserver'}, 'IPKernelApp': {'extra_extension': u'django_extensions.management.notebook_extension'}}
    [NotebookApp] Using existing profile dir: u'/home/ubuntu/.ipython/profile_nbserver'
    [NotebookApp] Searching path [u'/srv/labelmaterial/server', u'/home/ubuntu/.ipython/profile_nbserver'] for config files
    [NotebookApp] Attempting to load config file: ipython_config.py
    [NotebookApp] Loaded config file: /home/ubuntu/.ipython/profile_nbserver/ipython_config.py
    [NotebookApp] Attempting to load config file: ipython_notebook_config.py
    [NotebookApp] Loaded config file: /home/ubuntu/.ipython/profile_nbserver/ipython_notebook_config.py
    [NotebookApp] Config changed:
    [NotebookApp] {'ZMQInteractiveShell': {'colors': 'Linux'}, 'BaseIPythonApplication': {'profile': u'nbserver'}, 'ProfileDir': {}, 'Application': {'log_level': 10}, 'IPKernelApp': {'pylab': 'inline', 'extra_extension': u'django_extensions.management.notebook_extension'}, 'NotebookApp': {'enable_mathjax': True, 'ipython_dir': u'/home/ubuntu/.ipython', 'open_browser': False, 'ip': '*', 'password': u'removed for security', 'port': 9999}, 'NotebookManager': {'notebook_dir': '/vol/labelmaterial/data/ipython-notebooks'}}
    [NotebookApp] Serving notebooks from /vol/labelmaterial/data/ipython-notebooks
    [NotebookApp] Adding cluster profile 'nbserver'
    [NotebookApp] Adding cluster profile 'nbserver-old'
    [NotebookApp] Adding cluster profile 'default'
    [NotebookApp] WARNING: the notebook server is listening on all IP addresses but not using any encryption or authentication. This is highly insecure and not recommended.
    [NotebookApp] The IPython Notebook is running at: http://[all ip addresses on your system]:9999/
    [NotebookApp] Use Control-C to stop this server and shut down all kernels.
    WARNING:root:Invalid cookie signature 'YmQ4NGMzOTAtODhjZS00ZjNhLWJmODQtZWJjMDgxODUzNjJi|1359755475|cf5e81b7722c6d1bbcdfe109ce315527520cfc72'
    [NotebookApp] Using MathJax from CDN: http://cdn.mathjax.org/mathjax/latest/MathJax.js
    [NotebookApp] Kernel started: e0a802cb-68b0-4248-aa9e-51e85ee78f15
    [NotebookApp] Kernel args: {'extra_arguments': [u'--ext', u'django_extensions.management.notebook_extension', u'--profile=nbserver', u'--debug', u"--KernelApp.parent_appname='ipython-notebook'"], 'cwd': u'/vol/labelmaterial/data/ipython-notebooks'}
    [NotebookApp] Connecting to: tcp://127.0.0.1:36320
    [NotebookApp] Connecting to: tcp://127.0.0.1:42644
    [NotebookApp] Connecting to: tcp://127.0.0.1:48347
    [IPKernelApp] Config changed:
    [IPKernelApp] {'KernelApp': {'parent_appname': 'ipython-notebook'}, 'IPKernelApp': {'profile': u'nbserver', 'extra_extension': u'django_extensions.management.notebook_extension', 'log_level': 10, 'connection_file': u'/home/ubuntu/.ipython/profile_nbserver/security/kernel-e0a802cb-68b0-4248-aa9e-51e85ee78f15.json', 'parent': 1}}
    [IPKernelApp] Using existing profile dir: u'/home/ubuntu/.ipython/profile_nbserver'
    [IPKernelApp] Searching path [u'/vol/labelmaterial/data/ipython-notebooks', u'/home/ubuntu/.ipython/profile_nbserver'] for config files
    [IPKernelApp] Attempting to load config file: ipython_config.py
    [IPKernelApp] Loaded config file: /home/ubuntu/.ipython/profile_nbserver/ipython_config.py
    [IPKernelApp] Attempting to load config file: ipython_notebook_config.py
    [IPKernelApp] Loaded config file: /home/ubuntu/.ipython/profile_nbserver/ipython_notebook_config.py
    [IPKernelApp] Config changed:
    [IPKernelApp] {'ZMQInteractiveShell': {'colors': 'Linux'}, 'ProfileDir': {}, 'IPKernelApp': {'profile': u'nbserver', 'pylab': 'inline', 'log_level': 10, 'parent': 1, 'extra_extension': u'django_extensions.management.notebook_extension', 'connection_file': u'/home/ubuntu/.ipython/profile_nbserver/security/kernel-e0a802cb-68b0-4248-aa9e-51e85ee78f15.json'}, 'NotebookApp': {'enable_mathjax': True, 'ipython_dir': u'/home/ubuntu/.ipython', 'open_browser': False, 'ip': '*', 'password': u'removed for security', 'port': 9999}, 'KernelApp': {'parent_appname': 'ipython-notebook'}, 'NotebookManager': {'notebook_dir': '/vol/labelmaterial/data/ipython-notebooks'}}
    [IPKernelApp] Loading connection file /home/ubuntu/.ipython/profile_nbserver/security/kernel-e0a802cb-68b0-4248-aa9e-51e85ee78f15.json
    [IPKernelApp] Starting the kernel at pid: 2116
    [IPKernelApp] shell ROUTER Channel on port: 36320
    [IPKernelApp] iopub PUB Channel on port: 42644
    [IPKernelApp] stdin ROUTER Channel on port: 60556
    [IPKernelApp] Heartbeat REP Channel on port: 48347
    [IPKernelApp] To connect another client to this kernel, use:
    [IPKernelApp] --existing kernel-e0a802cb-68b0-4248-aa9e-51e85ee78f15.json --profile nbserver
    [IPKernelApp] Enabling GUI event loop integration, toolkit=inline, pylab=inline
    [IPKernelApp] Loading IPython extensions...
    [IPKernelApp] Loading IPython extension: storemagic
    [IPKernelApp] Loading IPython extension: django_extensions.management.notebook_extension
    [IPKernelApp] Error in loading extension: django_extensions.management.notebook_extension
    Check your config files in /home/ubuntu/.ipython/profile_nbserver

**Comment by trbs** [comment]
Please reopen or open another ticket if this does not work for you.
PR's to backport the solution to IPython <3.0 are welcome.

**Comment by si14** [comment]
I would like to report that this issue seems to persist with latest Jupyter/IPython and django-extensions. Somehow after setting `--notebook-dir` in settings I don't get current directory in `PYTHONPATH`, and because `manage_py_dir != os.getcwd()` here https://github.com/django-extensions/django-extensions/commit/41d553fb928f76433531d4caa401df16814ef6ec#diff-f5ace238b5d61cb0a96b6a5dc5ffaca3R134 there is no `manage_py_dir` in `PYTHONPATH` at all. This gets fixed if I run `manage.py shell_plus --notebook` from some other directory, though.

**Comment by fdemmer** [comment]
just ran into this issue: when loading an ipython notebook, the DJANGO_SETTINGS_MODULE is not found. 

reading into the code, i am wondering why that `manage_py_dir != os.getcwd()` is there?

imho the manage_py_dir should _still_ be added to PYTHONPATH. otherwise ipython won't find the project and having it in there should not hurt, when just running `shell_plus` without `--notebook`.
