### ISSUE TITLE
Add support for command line arguments to the iPython notebook

### ISSUE THREAD

**Issue by ollieglass** [django-extensions/django-extensions#302]
Feature request

I'm looking to run a notebook server, and this command gives an error:
    shell_plus --notebook profile create nbserver
    Error: Command doesn't accept any arguments

Would really appreciate this, or an interim workaround to let me run a server.

**Comment by trbs** [comment]
I think the IPYTHON_ARGUMENTS in settings file solution works for most people / use cases.

If you still need additional support for ipython arguments please open a new ticket.
