### ISSUE TITLE
Use of AdminMediaHandler causes runserver_plus/runserver inconsistencies in Django 1.4.x

### ISSUE THREAD

**Issue by dji** [django-extensions/django-extensions#305]
When calling ``python manage.py runserver_plus --nostatic`` in Django 1.4.3, AdminMediaHandler is used (at ``runserver_plus.py`` line 146) to serve admin static files, using a hardcoded path.  

This does not make sense with Django 1.4 and django.contrib.staticfiles, which is smart enough to find the version of the admin static files that you are intending to use.  (For example, if using grappelli).  ``python manage.py runserver --nostatic`` and ``python manage.py collectstatic``  traverse your static files to serve the appropriate (highest priority) file.  This is the expected behavior.

A workaround of course is to specify ``--adminmedia`` as you did before Django 1.4.  However this is not guaranteed to maintain consistency with ``collectstatic``, and it would be nice to know production and development were the same.

I'm happy to submit a patch but I'm not sure what it's doing there in the first place (presumably for some versions of Django it is needed?)

**Comment by trbs** [comment]
If this problem persists please open a new ticket.
