### ISSUE TITLE
sqldiff strips size from character varying under Postgres

### ISSUE THREAD

**Issue by jamercee** [django-extensions/django-extensions#330]
One of my favorite features of django-extensions is the sqldiff command. It's really useful when working through development of django projects. But we've discovered a small "glitch" when used with Postgres.

model file declared thusly:

    myfield = models.CharField(max_length=8)

Becomes this in Postgres:

        Column |     Type                      |
    ---------------+---------------------------------+
        myfield  |  character varying(9)   |

BUT sqldiff returns:

    ALTER TABLE "mytable"
               ALTER "myfield" TYPE VARCHAR;

notice -- sqldiff wants to strip the size from the varchar declaration.

I understand it's a completely harmless suggestion from sqldiff (postgres actually draws no distinction between the two scheme declarations).  BUT -- we prefer having the size field preserved as a form of documentation in the schema.

We're somewhat familiar with the django-extensions code base but we're still a bit new to it -- and it does some pretty sophisticated things (cool -- but sophisticated). Any suggestions on where in the code we could focus our attention to apply our own "patch" would be greatly appreciated!

Thanks
Jim

**Comment by trbs** [comment]
Closing this ticket. If it's still an issue please open a new ticket.
