### ISSUE TITLE
reset_db: OperationalError: cannot drop the currently open database

### ISSUE THREAD

**Issue by rajington** [django-extensions/django-extensions#394]
#73 was marked as closed with the instruction to reopen if the issue still exists.

I ran into the issue today with the latest form PIP using a postgresql database with the following in settings.py:

``` python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': '***_db',
        'USER': '***_admin',
        'PASSWORD': '***',
    }
}
```

running the following command:

```
$ python manage.py reset_db --router=default

You have requested a database reset.
This will IRREVERSIBLY DESTROY
ALL data in the database "diyatm_db".
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
OperationalError: cannot drop the currently open database
```

**Comment by artscoop** [comment]
Hi, the error is still happening here, with Django 1.7 and 1.8

```
psycopg2.OperationalError: database "new" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```

And I'm pretty sure nobody is using the database since Pgadmin3 can destroy the database.

**Comment by camilonova** [comment]
@artscoop can you check who is using it? Maybe is the same python process.

**Comment by artscoop** [comment]
Yes, I think it's the same python process since I try just after a restart of PostgreSQL.
If I wanted to know exactly which process was using a connection, how would I do ?

**Comment by artscoop** [comment]
Well, I just tried creating a new virtualenv and a new django project, and the command worked. So it's coming from my env configuration.

**Comment by camilonova** [comment]
ok, then is not an issue.

**Comment by artscoop** [comment]
For the record, I could locate what was causing the lock at the time:
it was a call to `django.core.urlresolvers.reverse` in middleware
that is to say, nothing to do with the database.

Now the lock is happening again, and I __cannot__ find what is causing it in my project.
Maybe django_extensions could "force-drop" active connections before resetting ?
