### ISSUE TITLE
Inconsistencies in graph_models with abstract base class models

### ISSUE THREAD

**Issue by aaronadamsTO** [django-extensions/django-extensions#416]
I'm working on a project with a non-developer friend, and I'm finding that Graphviz is a great communication tool.

Unfortunately, as the level of abstraction in my code increases, a number of quirks in  `graph_models` and the underlying [modelviz.py](https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/modelviz.py) have come to light, mostly regarding handling of abstract base classes.

I've tried to identify each quirk as specifically as possible, and while each is likely its own "bug," I still think they belong together in one report:

 1. While field inheritance is implemented recursively, model inheritance is not. For example, I have `Profile` and `User` models, both of which inherit from a `TimestampMixin` that itself inherits from a `CreatedTimestampMixin`. The fields from both mixins are correctly included in both `Profile` and `User`; `TimestampMixin` correctly appears as a model; but `CreatedTimestampMixin` is left out of the graph entirely.
 2. When grouping with the `-g` flag, an abstract model is clustered within the "first" app containing a model that inherits from it, rather than being clustered within the app in which it is declared. For instance, the aforementioned `TimestampMixin` is declared in `apputils`, but in the output it is instead included in the "first" app containing a model that inherits from it.
 3. I write "first" in scare quotes, because the order in which apps are output by `graph_models` is currently undefined; back-to-back calls to `graph_models` will often produce different output.

I think it would take a fairly significant restructuring to fix all of these issues; but if it's agreed that such changes would be widely beneficial, then I'm willing to take a stab at implementing them myself.

**Comment by esquevin** [comment]
Hi, have you ever had the time to work on these issues?
I'm facing the same problems.

**Comment by LeonardoGentile** [comment]
Did this ever happened ?

**Comment by camilonova** [comment]
Seems is not going to happen, I will close this issue unless @aaronadamsTO shows up.
