### ISSUE TITLE
Test Runner Issue

### ISSUE THREAD

**Issue by camilonova** [django-extensions/django-extensions#454]
Somehow django 1.6 does not run all the tests:

https://travis-ci.org/django-extensions/django-extensions/jobs/16780166#L132

It was running only 6, meanwhile other django versions where running 35 tests:

https://travis-ci.org/django-extensions/django-extensions/jobs/16780167#L173

So I have made this change https://github.com/django-extensions/django-extensions/commit/5285fd664c7ff4c0fee98aef03de8d1d91b22c1d

It works for django 1.6 but somehow does not work for django 1.5 and 1.4:

https://travis-ci.org/django-extensions/django-extensions/builds/16789212

Maybe the best solution would be to change the way we use the test runner, but since I don't know much about it I'll leave it here.

**Comment by camilonova** [comment]
Maybe one year later? ;)

**Comment by trbs** [comment]
Hehe :) It's clearly not been on my priority list... sorry about that.

Right now Travis seems to indicate that we run 57, 57, 40 and 40 tests for Django 1.7, 1.6, 1,5 and 1,4 respectively. Since 1.5 and 1.4 are very old now and 1.5 is unsupported I don't think we have to care too much about those.

However the tests on 1.8 are broken so we might need to take a good look at the testsuite anyways.

**Comment by camilonova** [comment]
Yay!

**Comment by trbs** [comment]
@camilonova what are your thoughts on replacing our current test suite with something based on py.test like suggested by https://github.com/benjaminabel ?

Think that might solve this issue as well right ?

**Comment by camilonova** [comment]
Yes it is.

@benjaminabel what do you think?

**Comment by benjaminabel** [comment]
@camilonova  `py.test django` find 59 tests for all django versions, so I think it could close the issue. However this need a little more work because all tests don't pass for all django versions.

**Comment by benjaminabel** [comment]
@camilonova @trbs I'm moving `tests` directory to root directory, and renaming each test to `test_....py`.
It's possible to run tests as functions in pytest, however we could use django.test.TestCase class, what do you think?

**Comment by camilonova** [comment]
@benjaminabel Sounds great for me. thanks

**Comment by benjaminabel** [comment]
@camilonova @trbs the pr is ready for a review.
