### ISSUE TITLE
ActivatorModel(Manager): does not use deactivate_date / activate_date

### ISSUE THREAD

**Issue by blueyed** [django-extensions/django-extensions#464]
`activate_date` and `deactivate_date` are not used by the manager.
`activate_date` is only initialized to the current time, if not provided in `save`.

Shouldn't these fields get used for filtering with the `active` and `inactive` manager methods?

Source: https://github.com/django-extensions/django-extensions/blob/master/django_extensions/db/models.py#L44

/cc @tehfink

**Comment by tehfink** [comment]
+1

**Comment by trbs** [comment]
closing this for now
