### ISSUE TITLE
Way to disable sql output in shell_plus notebook?

### ISSUE THREAD

**Issue by stuaxo** [django-extensions/django-extensions#468]
There is quite a lot of SQL output, I'd like a way to turn this on or off, is it possible ?

I guess ideally this might be integrated into the UI.

**Comment by trbs** [comment]
Hope this is solved by now, otherwise please open a new issue. Thanks !

**Comment by stuaxo** [comment]
Will do.

No idea if there is a better way than the solution I found above.   I'm an IT contractor, so am probably on about my 6th project since I posted this ticket, so it's a very long time since I was using this.
