### ISSUE TITLE
Running shell_plus via fab command - Ctrl + c interprets as KeyboardInterrupt and as Ctrl + z (Stop)

### ISSUE THREAD

**Issue by neara** [django-extensions/django-extensions#482]
![screen shot 2014-03-19 at 12 13 28 pm](https://f.cloud.github.com/assets/1453895/2458644/4633832e-af4f-11e3-8f9b-8439f5ff3d84.png)

If i hit ctrl + c i get `KeyboardInterrupt` as expected and i get thrown out of shell, half the way, the only thing after this is to close the terminal.

I don't get same issues when i run `python manage.py shell_plus` directly in terminal.

**Comment by trbs** [comment]
Hope this is solved by now, otherwise please open a new issue. Thanks !
