### ISSUE TITLE
PostgreSQLUUIDField + Django 1.7+ = incompatible types

### ISSUE THREAD

**Issue by davidfischer-ch** [django-extensions/django-extensions#487]
Using a `PostgreSQLUUIDField` as a primary key for a model in Django 1.7a2 raises an exception. I did fallback to `UUIDField` because it works as expected:

```
class Album(Model):
    id = PostgreSQLUUIDField(verbose_name=_(u'Unique Identifier'), auto=True, primary_key=True)
    ...

class Picture(Model):
    ...
    album = ForeignKey(Album, verbose_name=_(u'Album'), related_name=u'pictures')
```

Output of python manage.py test:

```
....
django.db.utils.ProgrammingError: foreign key constraint "souvenirs_album_album_id_4760c347c8fa04ab_fk_souvenirs_album_id" cannot be implemented
DETAIL:  Key columns "album_id" and "id" are of incompatible types: uuid and character varying.
```

I think this is related to the newest Django migration feature -vs- south.

Thanks !

PS : A UUID field may be integrated in the core : https://code.djangoproject.com/ticket/19463.

**Comment by tkuben** [comment]
@mhahn did you find a solution to the ProgrammingError problem when running python manage.py migrate?

**Comment by mhahn** [comment]
@tkuben I can't exactly remember, this was a long time ago. Django 1.8 now has a supported UUID field for postgres, so I think I just switched to the alpha version of that at the time.
