### ISSUE TITLE
Why was clean_pyc removed?

### ISSUE THREAD

**Issue by jaap3** [django-extensions/django-extensions#503]
I just upgraded to a more recent version of Django Extensions and now the clean_pyc command is gone. This happened in commit c00a8faac1a1003feb660a34edb3fb455674dd7d with the comment that "it does not work in many cases". I'd like to know what those cases are and if those cases are maybe the same for compile_pyc.

Also, next time if a command is removed it would be nice if it was deprecated first. Maybe make the command a noop and let it print a message or something. I use clean_pyc/compile_pyc in my deployment scripts and they suddenly started breaking because of a missing command. Thanks!

**Comment by SalahAdDin** [comment]
I have a problem with this command:
```bash
./manage.py clean_pyc
CommandError: No --path specified and settings.py does not contain BASE_DIR
```

Why?

**Comment by trbs** [comment]
This is a safety measure.

```clean_pyc``` has trouble (automatically) detect where your project root is.
Instead of just going ahead with deleting files it gives an error and warns you that it cannot (safely) continue.

You either need to specific --path or add a variable BASE_DIR to your settings file.
