### ISSUE TITLE
remove django_extensions/management/utils:get_project_root

### ISSUE THREAD

**Issue by trbs** [django-extensions/django-extensions#507]
Remove the ```get_project_root``` method for version 1.4.0

New Django installs specify BASE_DIR in settings.py which can be used instead for a consistent way to get the project root.

We should promote users adding BASE_DIR and explicitly telling us the project root.

**Comment by SalahAdDin** [comment]
I have a problem with this command:
```bash
./manage.py clean_pyc
CommandError: No --path specified and settings.py does not contain BASE_DIR
```

Why?

**Comment by trbs** [comment]
@SalahAdDin please do not cross post your question
