### ISSUE TITLE
runscript not working

### ISSUE THREAD

**Issue by ghost** [django-extensions/django-extensions#51]
Django-extensions works well, the dumpscript command too
but when I launch a ./manage.py runscript myscript  ("myscript" being in a "scripts" folder, in the project root folder, with an __init__.py file inside) I always get :
No module for script 'myscript' found

**Comment by morenoh149** [comment]
Not duh, https://django-extensions.readthedocs.io/en/latest/dumpscript.html#how suggests running `$ ./manage.py runscript testdata` sans `.py`.

Should I amend the command via PR?
