### ISSUE TITLE
UUIDField does not generate "uuid" datatype for PostgreSQL

### ISSUE THREAD

**Issue by debnet** [django-extensions/django-extensions#518]
Experiencing UUIDField and PostgreSQLUUIDFIeld which does not set "uuid" datatype to the column in PostgreSQL but always varchar(32) instead.

All the best.

**Comment by kevgathuku** [comment]
@debnet I am getting the correct field type when using `PostgreSQLUUIDField` i.e. the uuid type but getting `varchar(36)` when using `UUIDField` on PostgreSQL which seems to be the way it is intended to work.

**Comment by debnet** [comment]
Woo. It was a long time. Thanks for the answer so.

By the way, I think UUIDField will be natively integrated in Django 1.8 release with correct behavior.
https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.UUIDField

**Comment by kevgathuku** [comment]
@debnet Yeah. That should probably be used for those on the bleeding edge.
But I hope you can confirm that the field is working okay right now.
So do you think it's okay to close this?

**Comment by debnet** [comment]
Yes, it's perfectly OK.
