### ISSUE TITLE
runserver_plus always exits with error 247 whenever an exception is caught

### ISSUE THREAD

**Issue by jdotjdot** [django-extensions/django-extensions#529]
This issue just appeared a few weeks ago and I haven't been able to track it down or fix it.  I always use `runserver_plus` for the dev server so that I can use the werkzeug debugger.  However, for some reason, now whenever there's an exception, instead of properly displaying the werkzeug debug page, `runserver_plus` crashes.

First, the only the HTML of the page is loaded:
![image](https://cloud.githubusercontent.com/assets/1328961/3803517/791ce4c2-1c1b-11e4-86c7-222bba003389.png)

Then the server itself crashes:
![image](https://cloud.githubusercontent.com/assets/1328961/3803526/93a88c24-1c1b-11e4-8bf4-16d28ee7671d.png)

I am on Mac OS X (latest version).  I have not been able to track down what that exit code 247 means--it only appears when I run it in PyCharm.  The server does also crash if I run it outside of PyCharm, but without telling me the status code.

**Comment by quinox** [comment]
I had exactly the same problem and I've tracked it down to `request.META` containing the key [`werkzeug.server.shutdown`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L108) which is the callable [`shutdown_server`](https://github.com/pallets/werkzeug/blob/master/werkzeug/serving.py#L94). During the mail template rendering this callable gets called by Django to render, which subsequently shuts down the server.

**Comment by jdotjdot** [comment]
@quinox You are a **LIFE SAVER**.  My entire team thanks you **SO** much.

We were having this issue in even without using the error mailer (just when trying to render the error page at all) and I'm sure it was due to the same issue.  Adding this custom middleware solved the issue:

```python
## Dev only
class StopRunserverPlusShutdownMiddleware(object):
    def process_request(self, request):
        try:
            del request.META['werkzeug.server.shutdown']
        except KeyError:
            pass
```

**Comment by trbs** [comment]
Could people please test the above commit ?

```werkzeug.server.shutdown``` should now be removed by default.

**Comment by quinox** [comment]
Confirmed: with a72e026 the runserver quits, with cdd9503 it stays alive.

**Comment by trbs** [comment]
Hope this is solved by now, otherwise please open a new issue. Thanks !
