### ISSUE TITLE
search on EncryptedCharField (does not decrypt)

### ISSUE THREAD

**Issue by erikvw** [django-extensions/django-extensions#55]
is this possible?

For a model with EncryptedCharField named "last_name" i notice that the field does not decrypt when I search on it. In all other uses it is fine. This does not work:
        if form.is_valid():
            cd = form.cleaned_data
            search_results = MyTable.objects.filter(first_name__icontains=cd['search_term'])

is this by design or am i doing something wrong?
thanks for you help...

**Comment by camilonova** [comment]
This is too old to take a look. I'm closing this, if you want you can open a new ticket. Thanks.
