### ISSUE TITLE
Reliability of "func_globals" for detecting decorators on show_urls

### ISSUE THREAD

**Issue by diego-plan9** [django-extensions/django-extensions#559]
Currently, the [`show_url`](https://github.com/django-extensions/django-extensions/blob/33729988b257967025927ab46de279ff30f3ab2a/django_extensions/management/commands/show_urls.py#L118-L125) command relies on using `func.func_globals` (or `func.__globals__` on Python3) for detecting if a particular decorator has been applied to a particular url.

This might work on simple cases, but is prone to false positives and not being accurate on relatively complex applications - the name of the decorator being available in the global namespace of the function doesn't always mean that the decorator is actually used on that view.

A minimal example of an application that illustrates the problem (tested using `Python 2.7.7, Django==1.4.15`):

urls.py:

``` python
from django.conf.urls import patterns, url
urlpatterns = patterns('',
    url(r'^$', 'mysite.views.home', name='home'),
)
```

views.py:

``` python
from django.http import HttpResponse
login_required = 'foo'

def home(request):
    return HttpResponse("Hello, world")
```

show_urls output:

``` bash
$ python manage.py show_urls
/   mysite.views.home   home    login_required
```

I'm wondering if it would be possible or desirable to revise the show_urls command so the detection of decorators is more reliable, perhaps by inspecting `func_closure` instead of `func_globals` as suggested [here](http://schinckel.net/2012/01/20/get-decorators-wrapping-a-function/) or a similar solution.

**Comment by trbs** [comment]
Closing this for being inactive for too long. If there is a better way we are still happy to accept a PR for this.
