### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'db_index' with mongoengine

### ISSUE THREAD

**Issue by kaflesudip** [django-extensions/django-extensions#589]
Mongoengine's StringField doesn't have keyword argument 'db_index' which generates the above error.

**Comment by trbs** [comment]
Please make the report more specific. What goes wrong where exactly ?
If possible please provide a pull request with a reproducible test case, this will help us not to make the same mistake in the future (or tarball or gists somewhere) also this makes it easy to dive into the problem so changes are a lot greater that things will get solved sooner.

Please reopen the ticket when your able to provide more detailed information.
