### ISSUE TITLE
WindowsError on runprofileserver

### ISSUE THREAD

**Issue by asdftyp** [django-extensions/django-extensions#591]
Hi,

If I run following command 

     python manage.py runprofileserver --kcachegrind --prof-path=..\tmp-profile

and make a request from browser (127.0.0.1:8000), the following output is shown:

    A server error occurred.  Please contact the administrator.

The cmd shows:

    (example) E:\projects\example\example>python manage.py runprofileserver --
    kcachegrind --prof-path=..\tmp-profile
    Validating models...
    System check identified no issues (0 silenced).
    
    Django version 1.7.2, using settings 'example.settings'
    Development server is running at http://127.0.0.1:8000/
    Quit the server with CTRL-BREAK.
    Traceback (most recent call last):
      File "D:\Python27\Lib\wsgiref\handlers.py", line 85, in run
        self.result = application(self.environ, self.start_response)
      File "E:\projects\example\lib\site-packages\django_extensions\management\commands\runprofileserver.py", line 254, in handler
        os.rename(profname, profname2)
    WindowsError: [Error 32] The process cannot access the file because it is being used by another process
    [06/Jan/2015 14:03:32] "GET / HTTP/1.1" 500 59

I have following environment:
Windows 7
Python 2.7.8

>pip freeze
Django==1.7.2
Pillow==2.7.0
PyJWT==0.3.2
django-cors-headers==1.0.0
django-debug-toolbar==1.2.2
django-extensions==1.4.9
django-filter==0.9.1
django-nose==1.3
django-reversion==1.8.5
django-taggit==0.12.2
djangorestframework==3.0.2
djangorestframework-jwt==1.1.1
factory-boy==2.4.1
ipython==2.3.1
mock==1.0.1
nose==1.3.4
pyreadline==2.0
pytz==2014.10
six==1.9.0
sqlparse==0.1.14

The reason seems that in the command runprofileserver.py the file `profname` is not closed:

    if USE_LSPROF:
        kg = KCacheGrind(prof)
        kg.output(open(profname, 'w'))

solution is:

    if USE_LSPROF:
        kg = KCacheGrind(prof)
        with open(profname, 'w') as f:
             kg.output(f)

**Comment by trbs** [comment]
Your patch has been committed. Thanks !
