### ISSUE TITLE
Django 1.7 JSONField migrations broken

### ISSUE THREAD

**Issue by jaddison** [django-extensions/django-extensions#593]
BUG: adding a new JSONField to an existing Model sets the default value for existing Model instances incorrectly - the value stored in the DB is `"{}"` instead of just `{}`. Steps below:

**1. Create a migration for the following model:**

```
class JSONTest(models.Model):
    settings = JSONField(blank=True)
```

**2. Run `./manage.py migrate`**
**3. Run `./manage.py shell` and create a new `JSONTest` object:**

```
JSONTest.objects.create()
```

**4. Change the model to add another `JSONField` (like below) and create another migration:**

```
class JSONTest(models.Model):
    settings = JSONField(blank=True)
    settings2 = JSONField(blank=True)
```

**5. Run `./manage migrate`**
**6. Run `./manage.py shell` and get the `JSONTest` instance you created in step 3 above:**

```
o = JSONTest.objects.get(pk=1)
o.settings2
```

BUG: note that the default value of the newly added `settings2` field is `"{}"` instead of `{}`. Will be submitting a pull request for this.

**Comment by jaddison** [comment]
How long until the 1.5.0 release is out, if I can ask?

**Comment by trbs** [comment]
I was planning on looking into a new release next week.
If you need a new release I can try and do it earlier.

(A test case or some other people confirming your patch does not break anything would help)

**Comment by jaddison** [comment]
I think I mentioned it in the pull request itself, but here it is again: I'm really uncertain how to write a test case for this narrow, migrations-only scenario. Obviously, the issue is 1.7 specific (ie migrations). I don't know anyone else who uses this app's JSONField, however.
