### ISSUE TITLE
Broken runjobs command on Python 3.4

### ISSUE THREAD

**Issue by pyghassen** [django-extensions/django-extensions#602]
I was trying to run the runjobs command as the following:

```
    python manage.py runjobs minutely
```

When the this error was thrown:

```
    File "/home/user/env/lib/python3.4/site-packages/django_extensions/management/commands/runjobs.py", line 23, in runjobs
    list.sort()
AttributeError: 'dict_keys' object has no attribute 'sort'
```

**Comment by trbs** [comment]
I committed a slightly different version of the patch which should solve this problem as well and fixed the ugly use of the variable named ```list```.

Could you please test this patch and reopen the ticket if it does not work ?

Thanks for the report and patch !

**Comment by pyghassen** [comment]
It's all good now thanks @trbs
