### ISSUE TITLE
shell_plus command now is broken on python 3.4

### ISSUE THREAD

**Issue by pyghassen** [django-extensions/django-extensions#605]
shell_plus command now is broken:
```
editor = os.path.basename(os.environ.get('EDITOR'))
  File "/home/user/env/lib/python3.4/posixpath.py", line 142, in basename
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by trbs** [comment]
Could you try with the github version ?
I committed a patch for that yesterday: https://github.com/django-extensions/django-extensions/commit/2e1cbe0ace927430c5fb13bce0637181de42e5b6

**Comment by trbs** [comment]
If that patch does not work for you please reopen this ticket.
