### ISSUE TITLE
Django 1.8 - ADMIN_FOR removed and causing show_urls to fail

### ISSUE THREAD

**Issue by phoebebright** [django-extensions/django-extensions#608]
To fix:

In

https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/show_urls.py

Line 86

from:
        if settings.ADMIN_FOR:
to:
        if hasattr(settings,'ADMIN_FOR') and settings.ADMIN_FOR:

**Comment by trbs** [comment]
Fix applied, Thanks !
