### ISSUE TITLE
runserver_plus constantly uses about 30% of one CPU

### ISSUE THREAD

**Issue by ezheidtmann** [django-extensions/django-extensions#625]
Hey there,

I'm really pleased with `runserver_plus` but found today that it uses 30% of one CPU (according to top & htop)

When I run `strace` on the process, I see thousands of `stat` calls. I guess it's checking all my files (even libraries) for changes. 

I'm on Linux -- Ubuntu 14.03 "trusty". Is there any way to enable an alternative to this exhaustive polling on my platform, other than `--noreload`?

Thanks!
Evan

**Comment by ezheidtmann** [comment]
I think I may have answered my own question: The problem lies in `werkzeug`, which once supported `inotify` but no longer does.

In the 0.10 release notes, this is the latest mention of `inotify`:

> Version 0.7.1
> (bugfix release, released on July 26th 2011)
>
> Fixed a problem with newer versions of IPython.
> Disabled pyinotify based reloader which does not work reliably.

http://werkzeug.pocoo.org/docs/0.10/changes/

**Comment by trbs** [comment]
Thanks for figuring this one out !
I will add a note to the documentation about this so that it might help others trying to figure out the same issue.

**Comment by trbs** [comment]
Have you tried with the `watchdog` module as per http://werkzeug.pocoo.org/docs/0.10/serving/#reloader ?

**Comment by ezheidtmann** [comment]
Thanks for the tip! I did a `pip install watchdog` and the issue is gone! Marvelous!

Interestingly, `runserver_plus` now reports it is using `inotify`:

>  * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader

**Comment by sbnb** [comment]
Hey ezheidtmann,

Have you had any problems with runserver_plus not restarting on file changes when using watchdog?

I've experienced the same high CPU issues and that was solved by watchdog forcing werkzeug to use the inotfiy reloader. But unfortunately it is now missing most file changes, which seems to be the issue that lead to it being removed the first time.

Ideally I would like to use the polling method, but extend the time between polls to spare the CPU.  Anyone know if that is possible?

Thanks!

**Comment by trbs** [comment]
I have added support for specifying 'reload_interval' in werkzeug in 3ab67d4a8376f8ee04bc32547269f1bb19742f83.

You should now be able either add:
```
RUNSERVERPLUS_POLLER_RELOADER_INTERVAL = 5
```

To your settings files or use:

```
$ ./manage.py runserver_plus --reloader-interval 5
```

on the command line to control the interval between scans in poller mode.

**Comment by trbs** [comment]
Could you please check if this works for you ?

If anybody could make a PR to add this to the documentation as well I would be very grateful.

**Comment by sbnb** [comment]
Thanks a lot trbs.

It works as expected.
