### ISSUE TITLE
Add Prefetch in shell_plus loading

### ISSUE THREAD

**Issue by debnet** [django-extensions/django-extensions#626]
All is in the title. ;)

**Comment by trbs** [comment]
Sorry it's not entirely clear to me what you mean.

**Comment by debnet** [comment]
Sorry, I try to do better.

Just a little improvement for shell_plus command which load all models from all installed apps, and also helpers Django objects like Count, Sum, Avg, etc... It just lacks "Prefetch" from Django 1.7 which is merely used since it goes out. ;)

**Comment by trbs** [comment]
Ah I understand, please test the commit.

**Comment by debnet** [comment]
Works like a charm. ;)
