### ISSUE TITLE
shell_plus --notebook gives bad configuration error

### ISSUE THREAD

**Issue by kutenai** [django-extensions/django-extensions#631]
I am getting the following error when trying to use shell_plus --notebook:

[C 04:28:24.002 NotebookApp] Bad config encountered during initialization:
[C 04:28:24.003 NotebookApp] Unrecognized flag: '--ext'

This is my pip environment:
backports.ssl-match-hostname==3.4.0.2
certifi==14.5.14
Django==1.7.4
django-account==0.1.14
django-appconf==1.0.1
django-bootstrap-form==3.1
django-debug-toolbar==1.2.2
django-extensions==1.5.0
django-jsonfield==0.9.13
django-registration==1.0
django-suit==0.2.12
django-urlauth==0.1.8
django-user-accounts==1.0.1
djangorestframework==3.0.5
docutils==0.12
eventlog==0.10.0
gnureadline==6.3.3
ipython==3.0.0
Jinja2==2.7.3
jsonschema==2.4.0
MarkupSafe==0.23
metron==1.3.5
mistune==0.5
MySQL-python==1.2.5
nose==1.3.4
numpydoc==0.5
pinax-theme-bootstrap==5.7.1
psycopg2==2.6
ptyprocess==0.4
Pygments==2.0.2
pytz==2014.10
PyYAML==3.11
pyzmq==14.5.0
requests==2.5.3
sh==1.11
simplejson==3.6.5
six==1.9.0
Sphinx==1.2.3
sqlparse==0.1.14
terminado==0.5
tornado==4.1

**Comment by davecoates** [comment]
This is something to do with ipython 3.0.0 - I upgraded to this and got the same error. After downgrading to 2.4.0 at it works again.

**Comment by trbs** [comment]
Skimming over the backwards-incompatible-changes list of the IPython 3.0 release I could not find the culprit. But assuming either the '--ext' option has been renamed or loading extensions has been changed all together I am assuming this should be relatively easy to fix.

**Comment by pebreo** [comment]
This cause seems to be diagnosed here: https://github.com/ipython/ipython/issues/7913

**Comment by trbs** [comment]
Hopefully it is still possible to tell the notebook to load those extension for Python notebooks some other way.

```IPython 3, as part of the language-agnostic kernel starting changes, no longer relays the notebook's CLI arguments to the kernel.```

Otherwise it might be the end of ```shell_plus --notebook```

**Comment by takluyver** [comment]
I don't think it's possible directly at the command line, but it should still be possible by writing a config file. I was discussing this with @minrk earlier; we're trying to come up with the best way to do it so that it won't break again with IPython 4, when there will be a load more changes because we're splitting up IPython into several pieces.

**Comment by D3f0** [comment]
What about doing a %%magic_command to generate all the context shell_plus adds?
Maybe is not the optimal solution, but it'll allow some people to use IPython 3.0 with Django

**Comment by takluyver** [comment]
Trouble is, best way to define an extra magic is with an extension, and specifying an extension to load is already the issue. You could tell all your users to do `%load_ext django_admin`, at a pinch.

**Comment by minrk** [comment]
The `--ext` CLI arg here is equivalent to calling `%load_extension django_extensions.management.notebook_extension` at runtime, so if you either create a notebook pre-populated with this, or instruct users to call it themselves, you will get the same result.

We are still trying to figure out the easiest way to configure the kernel when the notebook server is in between you and it.

Current options I see:

- create `ipython_config.py` next to `manage.py` with `c.InteractiveShell.extensions = ['django...']` (this only works if notebooks are only created adjacent to manage.py, not exactly robust)
- specify a local IPython config directory with `IPYTHONDIR` env variable, containing ipython_config.py above (works same as above, but in a robust way). This one overrides any other config the user might have.
- pass the `--ext` arg to the kernel via a django kernelspec. IPython-3.0 specific, but relatively simple, and the closest to what you were doing before.

**Comment by minrk** [comment]
None of these are great, frankly. I'll sketch out the kernelspec version, as that's the 'new way' to do things, if nothing else than to see if we should improve anything on that API.

**Comment by trbs** [comment]
Just want to say: Thanks for all your efforts picking this up guys !

I know a lot of people (including me) love IPython and it's notebook and also like the convenience of auto loading Django specific modules.

**Comment by D3f0** [comment]
The solution @minrk suggested works
```python
%load_ext django_extensions.management.notebook_extension
```
It's just a little verbose, since it outputs everything we used to see in the terminal in IPython 2.

**Comment by trbs** [comment]
Drawback is that that does not happen automatically right ? (But it's at the least a good workaround until we have something better)

@minrk Looking a bit into kernel specs it seems it have some additional nice properties like a way to define "display_name", would be cool to see "Python 2 - Django" in the notebook interface :)

**Comment by minrk** [comment]
You can see one version of the kernelspec way in #634.

**Comment by benjaminabel** [comment]
Really nice code @minrk thank you very much.

**Comment by benjaminabel** [comment]
@trbs @kutenai, with this *powerfull *code we may also can load automatically the extension without any configuration in the `settings` with something like this:

```
# IPython >= 3 uses kernelspecs to specify kernel CLI args
                if release.version_info[0] >= 3:
                    ipython_arguments.append('--ext=django_extensions.management.notebook_extension')
                    install_kernel_spec(app, ipython_arguments)
```
Like this, the IPYTHON_ARGUMENTS is just optionnal to add more ipython options.

**Comment by trbs** [comment]
@benjaminabel yeah definitely.

**Comment by benjaminabel** [comment]
I extended the commit to use notebook extension by default see this [branch](https://github.com/django-extensions/django-extensions/compare/master...benjaminabel:shell_plus_notebook_ip3).

**Comment by miraculixx** [comment]
Following @minrk  and @D3f0's comments, I got this to work for `Django==1.6, ipython==3.0.0, django-extensions==1.5.2` as follows:

```
# add this to your ipython_config
# (typically ~/.ipython/profile_default/ipython_config.py)
import os
if os.environ.get('DJANGO_SETTINGS_MODULE'):
  c.InteractiveShellApp.extensions = ['django_extensions.management.notebook_extension']
```

This way `manage.py shell_plus [--notebook]`  works as before with IPython 2.4, and IPython also works without Django. It's a hack, but it works, follows DRY & is less verbose than running %load_ext in every notebook.
