### ISSUE TITLE
pipchecker - show latest stable

### ISSUE THREAD

**Issue by keradus** [django-extensions/django-extensions#637]
Hi, is it possible for pipchecker to show not only latest dev version, but latest stable version as well ?
Currently I have installed Django 1.7.4 and pipchecker show me that 1.8b2 is available, but I dont want to use `@dev` version, therefore it would be great to see 1.7.6 (latest `@stable`) as well.

**Comment by trbs** [comment]
I have been wishing for that more then once as well :)

Following pep-440 ( https://www.python.org/dev/peps/pep-0440/#developmental-releases ) would probably be the best way to implement this.

Personally I would not mind if showing only stable upgrades would be the (configurable) default as well.

**Comment by keradus** [comment]
I'm ok with showing only stables.
Any chances to have it implemented soon? Even without pep-404 one can always parse version's suffix for looking for `a` or `b` etc

BTW, sad it's not following SEMVER.

**Comment by trbs** [comment]
Regretfully I won't have much time for this in the near future. So I'm hoping somebody else can create a PR or sponsor this ticket.

**Comment by timgraham** [comment]
FWIW, it seems to me that the `pipchecker` command might be better suited to enhancing pip itself. For example, there's an open ticket to allow `pip list --outdated` to take a requirements file: https://github.com/pypa/pip/issues/3314.

**Comment by trbs** [comment]
Once this gets implemented in ```pip``` we can deprecate ```pipchecker```  and/or make it a shim for ```pip list -o -r requirements.txt```.

Until that time I'm still happy to take PR's to improve ```pipchecker```.

I'll leave this open for a bit but we can close it as well until somebody makes a PR either for ```pypa``` or ```django-extensions```.

**Comment by keradus** [comment]
Issue open for 15 months...
