### ISSUE TITLE
runscript not compatible with apps that use AppConfig in INSTALLED_APPS

### ISSUE THREAD

**Issue by NotSqrt** [django-extensions/django-extensions#641]
Since Django 1.7 (https://docs.djangoproject.com/en/1.7/ref/applications/#configuring-applications), it is possible to use:

```python

INSTALLED_APPS = (
    "my_app.apps.MyAppConfig",
)
```

But runscript fails to load scripts for these apps.
It looks for ``my_app.apps.MyAppConfig.scripts.my_script`` instead of ``my_app.scripts.my_script``.

**Comment by NotSqrt** [comment]
Any idea on the schedule for the next release ?

**Comment by trbs** [comment]
I will try to do a new release tomorrow.

**Comment by NotSqrt** [comment]
Great ! Thanks a lot for your promptness !
