### ISSUE TITLE
New management command to show database DSN

### ISSUE THREAD

**Issue by rodo** [django-extensions/django-extensions#645]
Hi,

I think it may be usefull to have a management command to show the Data Source Name based on settings. The command will write on stdout the above line form Postgresql by example

    locallhost:5432:base:user:password

With this kind of command you'll can fill your .pgass file with a one liner.

I can do the patch and open a pull request if you think it may be merged, and interest other people than me.

Regards

**Comment by trbs** [comment]
I like the idea and would merge it if it supported Django's Multiple Database :)
(and preferably supports all standard supported database backends)

**Comment by trbs** [comment]
Merged :+1:
