### ISSUE TITLE
Migrations of django-extensions' UUIDField to Django's (CharField) Leads to Issues

### ISSUE THREAD

**Issue by cancan101** [django-extensions/django-extensions#647]
On non-Postgres both the django-extensions and Django `UUIDField` are represented as a `CharField` but the Django fields has `-` characters removed whereas the django-extensions fields does not. This leads to all sorts of odd behavior where the upgraded models can no longer be saved.

**Comment by trbs** [comment]
I don't think it was ever meant that those UUIDField's would be compatible/interchangeable with each other.
In the long run we will remove our UUIDField in favor of the build-in field of Django.
