### ISSUE TITLE
`show_urls` doesn't support nested namespaces

### ISSUE THREAD

**Issue by ivanistheone** [django-extensions/django-extensions#678]
I have an app called `support` which includes `task1` and `task2` and each task in turn includes another urls file with suburl `add`. The overall url structure is:

     /support/task1/add      <==>   reverse('support:task1:add')
     /support/task2/add      <==>   reverse('support:task2:add')

Running `./manage.py show_urls` shows 

    support:add
    support:add

without the intermediate namespaces `task1` and `task2`.

**Comment by trbs** [comment]
Could you please try again with the github version ?

**Comment by ivanistheone** [comment]
Yep works. I get `support:task1:add`  and `support:task2:add` in the third column of the output of `show_urls` as expected. Thx. That's some stellar turnaround time.
