### ISSUE TITLE
Django 1.8+: null_techical_500_response() needs to accept status_code kwarg

### ISSUE THREAD

**Issue by andrewhayes1979** [django-extensions/django-extensions#683]
Found by:
 - Running Django 1.8+
 - Running latest django-extensions
 - Running runserver_plus
 - running in DEBUG=True
 - raising SuspiciousOperation exception in a view

...in the above flow of events, django's base handler picks up the SuspiciousOperation, calls through to debug.technical_500_response() passing a status_code kwarg of 400.

In runserver_plus, it appears django-extensions has patched out this function in favour of null_technical_500_response() to produce the nicer error pages.

null_technical_500_response() however crashes since it's not expecting a status_code kwarg.

In Django 1.8+, null_technical_500_response needs it's interface updating to reflect updates in Django 1.8 error handling.

**Comment by haakenlid** [comment]
Here's a hacky workaround. `status_code` is ignored, but that doesn't matter.

    def null_technical_500_response(request, exc_type, exc_value, tb, status_code=500):
        # ignore status_code
        six.reraise(exc_type, exc_value, tb)

**Comment by trbs** [comment]
Thanks !

I've added @haakenlid solution which does not seem so hacky to me.. it solves the signature problem just fine :)
