### ISSUE TITLE
shell_plus --ipython doesn't honor IPYTHON_ARGUMENTS

### ISSUE THREAD

**Issue by maroux** [django-extensions/django-extensions#685]
Now that IPython is being invoked the correct way with `start_ipython`, we can allow the setting `IPYTHON_ARGUMENTS` to be passed into `argv` argument of `start_ipython`. This would allow greater control over how IPython is run, including customizing configuration at run time.

**Comment by trbs** [comment]
Could you make a PR for this ?

**Comment by maroux** [comment]
@trbs done
