### ISSUE TITLE
ImportError: cannot import name update_wrapper

### ISSUE THREAD

**Issue by akhilclarion** [django-extensions/django-extensions#695]
File "/home/akhil/pythonproject/Django_extend/envde/local/lib/python2.7/site-packages/django_extensions/admin/__init__.py", line 18, in <module>
    from django.utils.functional import update_wrapper

Hello,
 i am getting this error with django_extensions==0.6, i tried on two different system with python=2.7 virtualenv.

Please help me on this.

Regards,
Akhil

**Comment by trbs** [comment]
please update to the latest version of Django Extentions if the problem persists please reopen or open a new ticket
