### ISSUE TITLE
How to turn off requests logging

### ISSUE THREAD

**Issue by sbitpdc** [django-extensions/django-extensions#700]
In DEBUG, when I request a url in django, the console will printing info of request.
example:
views.py

import requests
req = requests.get('http://www.piadu.com')

the console:
2015-07-09 11:10:03,311 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): www.piadu.com

I want to turn off this info

**Comment by trbs** [comment]
Does not seem to be django-extension related.

Please look at the logging documentation in Django and Python.
