### ISSUE TITLE
Autocomplete ignores formfield_for_foreignkey method in ForeignKeyAutocompleteAdmin

### ISSUE THREAD

**Issue by nkonin** [django-extensions/django-extensions#701]
I'm using the django-extensions to autocomplete ForeignKey field ('car_model') in the admin. Also I need to limit the selection for this field, so I use a formfield_for_foreignkey method, as specified in the Django documentation. But it does not work!
p.s. I added my code example to clarify the situation .
![snapshot](https://cloud.githubusercontent.com/assets/11088651/8634455/b6a9ebda-2801-11e5-892d-8e7ae08eb931.png)

**Comment by michael-k** [comment]
The [documentation](http://django-extensions.readthedocs.io/en/latest/admin_extensions.html) says to use `get_related_filter` for this.
