### ISSUE TITLE
French translation for ForeignKeyAutocompleteAdmin broken

### ISSUE THREAD

**Issue by d6bels** [django-extensions/django-extensions#702]
Hi,
It seems that the French translation for the help message appearing under the inputs with `ForeignKeyAutocompleteAdmin` does not work properly.

It says : `Use the left field to do xxx lookups in the fields xxx et xxx.` instead of the French translation.

I was able to fix it by editting the .po and regenerating the .mo file.
Btw, it also fixes a typo  (`recheres` --> `recherches`).

Here is diff for the .po which corrects the changes:

```
diff broken/django.po working/django.po
29,32c29,30
< msgid ""
< "Use the left field to do %(model_name)s lookups in the fields "
< "%(field_list)s."
< msgstr "Utilisez le champ de gauche pour faire des recheres de %(model_name)s dans les champs %(field_list)s."

---
> msgid "Use the left field to do %(model_name)s lookups in the fields %(field_list)s."
> msgstr "Utilisez le champ de gauche pour faire des recherches de %(model_name)s dans les champs %(field_list)s."
```

Thanks

**Comment by trbs** [comment]
Hope this is solved by now, otherwise please open a PR with the patch for this issue. Thanks !
