### ISSUE TITLE
show_urls doesn't show i18 patterns

### ISSUE THREAD

**Issue by chimeno** [django-extensions/django-extensions#704]
I didn't find any related issue about this.
When tipping this command, the output doesn't show related i18patterns.

For example:
in settings.py
````
LANGUAGES = (
    ('es', 'Spanish'),
    ('en', 'English'),
)
````

in urls.py:

````
urlpatterns += i18n_patterns('',
       url(r'^area-manager/$', TemplateView.as_view(
        template_name='pages/area_manager.html'), name='area-manager'),
````
show_urls output:
````
/None/area-manager/	django.views.generic.base.TemplateView	area-manager

````

It should show:

````
/en/area-manager/	django.views.generic.base.TemplateView	area-manager
/es/area-manager/	django.views.generic.base.TemplateView	area-manager
````

**Comment by trbs** [comment]
Could you please try again with https://github.com/django-extensions/django-extensions/commit/0485e21d4b686e7d86db017771f5e903ec6029f4 ?

**Comment by chimeno** [comment]
It's working well now! Great work!

**Comment by trbs** [comment]
Great, thanks for the report !
