### ISSUE TITLE
DeprecationWarning: SubfieldBase is being removed in Django 1.10

### ISSUE THREAD

**Issue by jaddison** [django-extensions/django-extensions#706]
An early warning for you... I noticed this warning popping up when I'm testing against Django 1.9 (master branch):

```
/home/jaddison/project/src/django/django/db/models/fields/subclassing.py:22: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  RemovedInDjango110Warning)
```

I found that `SubfieldBase` is used in django-extensions, thought I'd pass this along.

**Comment by timgraham** [comment]
Fixed in https://github.com/django-extensions/django-extensions/issues/810.
