### ISSUE TITLE
ptipython and ptpython ignore config files

### ISSUE THREAD

**Issue by sac2171** [django-extensions/django-extensions#711]
While I was using bpython or ipython with python manage.py shell_plus, the both respected the configuration files:
~/.pythonrc.py 

Running ptipython or ptpython from the shell also uses the default configuration file ~/.ptpython/config.py

Running python manage.py shell_plus after installing ptipython, where it now defaults to ptipython, does not read either configuration file. there doesn't seem to be any option for passing the configuration file through shell_plus to the underlying interpreter. 

as in: python manage.py shell_plus --ptipython --config???

How do I get ptipython shell_plus to use my configuration?

**Comment by trbs** [comment]
Currently ```shell_plus``` opens the ```ptipython``` shell and expect it to load any additional config files.
Unless ```ptipython``` provides a way directly (eg: via environment variables) its probably not possible to change what configuration file is used by default.

Looking at https://github.com/jonathanslenders/ptpython/blob/master/ptpython/entry_points/run_ptipython.py it does not seem very difficult to implement loading the default configuration file.

Pull Requests are welcome :)

**Comment by sac2171** [comment]
But that's the thing, I'm using the default configuration file, 
foobar-XPS13-9333% ls ~/.ptpython/config.py                             
/home/foobar/.ptpython/config.py

https://github.com/jonathanslenders/ptpython/blob/master/ptpython/entry_points/run_ptipython.py#L27
https://github.com/jonathanslenders/ptpython/blob/master/ptpython/entry_points/run_ptipython.py#L69

I'm not sure if  '--config-dir' is getting set, and if so by what?

**Comment by trbs** [comment]
It is not, this https://github.com/jonathanslenders/ptpython/blob/master/ptpython/entry_points/run_ptipython.py#L68 should be implemented. PR's are welcome :)
