### ISSUE TITLE
iPython 4.0 breaks shell_plus notebook

### ISSUE THREAD

**Issue by Koed00** [django-extensions/django-extensions#720]
Upgrading to iPython 4.0 will create an error when running ``python manage.py shell_plus --notebook``:

```python
.virtualenvs/django-q/lib/python3.4/site-packages/jupyter_client/kernelspec.py", line 143, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: 'python'
```

I've tested this with both Python 2.7.9 and 3.4.2.
Downgrading to iPython 3.2.1 returns everything to normal.

**Comment by multigl** [comment]
https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/shell_plus.py#L130

changing 
```python
ks = ksm.get_kernel_spec('python')
``` 
to 
```python
ks = ksm.get_kernel_spec('python2')
```` 
will fix the problem as a quick workaround.

**Comment by aronysidoro** [comment]
I had the same issue with using **iPython 4.0.0**.  This is the error traceback I got:

```
/Users/aaron/Documents/virtualenvs/django18_py2/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

/Users/aaron/Documents/virtualenvs/django18_py2/lib/python2.7/site-packages/IPython/frontend.py:21: ShimWarning: The top-level `frontend` package has been deprecated. All its subpackages have been moved to the top `IPython` level.
  "All its subpackages have been moved to the top `IPython` level.", ShimWarning)

Traceback (most recent call last):
  File "/Users/aaron/Documents/virtualenvs/django18_py2/lib/python2.7/site-packages/django_extensions/management/commands/shell_plus.py", line 120, in get_notebook
    from IPython.frontend.html.notebook import notebookapp
ImportError: cannot import name notebookapp

Could not load IPython Notebook interactive Python environment.
```

**Comment by tallus** [comment]
I put in a fix for this here: https://github.com/django-extensions/django-extensions/pull/723

You can get the kernel name using find_kernel_specs()

**Comment by trbs** [comment]
Please try with 92008a3

**Comment by joshowen** [comment]
That fixes the issue for me.

**Comment by trbs** [comment]
great :)

**Comment by Koed00** [comment]
Nice work. Looks fine for me

**Comment by hanleybrand** [comment]
One thing to note if you've tried

> `pip install -U git+git://github.com/django-extensions/django-extensions.git@92008a391c6357d7896a65ea74ac103664e21ddc`

and it's not working because 

```
The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

Traceback ([EDITED]):
....
  File ".../django_extensions/management/commands/shell_plus.py", line 353, in handle_noargs
    shell = get_notebook()
  File ".../django_extensions/management/commands/shell_plus.py", line 119, in get_notebook
    from IPython.html.notebookapp import NotebookApp
ImportError: No module named notebookapp
```

even though it may seem like there's still a problem with django-extensions, it may be that you didn't install ipython with notebook support.  In this case, try:

`pip install -U "ipython[notebook]"`

**Comment by trbs** [comment]
@hanleybrand please (re)try with 9648b292614110852d6e233b91a78d328688c819 it should now try the new ```notebook``` package first. This should get rid of the error at startup.
