### ISSUE TITLE
I keep getting jupyter_client.kernelspec.NoSuchKernel: 'python' Error

### ISSUE THREAD

**Issue by kisna72** [django-extensions/django-extensions#725]
I have 'regular' python 3 installed on my machine. I create a virtualenv as

```
C:\Python34\Scripts\virtualenv.exe venv
```

I installed django, created a project, and installed jupyter (new version of ipython using pip)
``` pip install jupyter ```

When I type ``` python manage.py shell_plus --ipython ``` everything works fine, and I get a ipython style shell.

However when I do ```python manage.py shell_plus --notebook ``` it gives me the error mentioned in the title. 

Any suggestions?

**Comment by kisna72** [comment]
Just saw #720  and changing line 130 to python3 works.
https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/shell_plus.py#L130

If you want to test what version of kernel you are using, do ```ipython kernelspec install-self```

**Comment by trbs** [comment]
Please try with 92008a3 

(Closing this issue in favor of #720 )
