### ISSUE TITLE
1.5.6 release

### ISSUE THREAD

**Issue by barseghyanartur** [django-extensions/django-extensions#727]
If current master is stable, why not make a new release?

**Comment by trbs** [comment]
It's on my todo list.

One of the things holding up a new release up where the IPython 4.0.0 problems but those seem to be solved now.

Time permitting I might release 1.5.6 today

**Comment by joshowen** [comment]
Thanks!  Looking forward to the PyPi release.

**Comment by barseghyanartur** [comment]
@trbs:

Thanks!
