### ISSUE TITLE
CommandError: No --path specified and settings.py does not contain BASE_DIR

### ISSUE THREAD

**Issue by SalahAdDin** [django-extensions/django-extensions#729]
I have a problem with this command:
```bash
./manage.py clean_pyc
CommandError: No --path specified and settings.py does not contain BASE_DIR
```

Why?

I'm use PROJECT_DIR setting in side of BASE_DIR.

**Comment by trbs** [comment]
I don't understand, do you mean 'instead of' or 'in side of' ? 

```clean_pyc``` will only work with ```BASE_DIR``` at the moment. So you could just do:

```
BASE_DIR = PROJECT_DIR
```

You could also write a pull request so that the used variable name (BASE_DIR, PROJECT_DIR, whatever) is configurable from settings.py
