### ISSUE TITLE
Options for `graph_models` are not documented

### ISSUE THREAD

**Issue by foresmac** [django-extensions/django-extensions#734]
The docs discuss options:
> Several options are available: grouping models, including inheritance, excluding models and columns, and changing the layout when rendering to an output image.

However, none of the these options are actually documented. I had to dig into the source to figure out which settings to use and how to use them.

**Comment by trbs** [comment]
We really would appreciate help with a documentation. If you have some time please submit a pull request (or add text to the issue) to help clarify the options that are not documented.

Thanks !

**Comment by foresmac** [comment]
I'll do what I can, but I honestly don't know if I'm using a setting right and there are bugs or I'm using settings wrong. For instance, I have the following set of models to exclude:
``` python
GRAPH_MODELS = {
    'exclude_models': 'BasePasscode, AbstractBaseUser, PermissionsMixin, Group, Permission',
}

But only `BasePasscode` is actually excluded from the final output. I tried making it a list instead of a comma separated string, and it definitely expects a comma separated string and **not** a list. And I couldn't even get it to work from the command line.

**Comment by trbs** [comment]
please retry with 0c09a24911b0ac063fe1349af1f6497db016fcf5
i fixed some code that reads the list.

**Comment by foresmac** [comment]
Cool, I'll give it a try tomorrow. Will still try to add docs as well, at least for what I can figure out.
