### ISSUE TITLE
UUIDField and Django 1.8 migration path

### ISSUE THREAD

**Issue by rmoorman** [django-extensions/django-extensions#746]
Hello,

Is there a migration path of some sort in case I have a django 1.7 installation with django extensions which uses the UUIDField and I want to upgrade to 1.8 and django's own new UUID field type?

Thank you very much in advance!

Best regards,
Rico Moorman

**Comment by tdruez** [comment]
@rmoorman this may help: http://baltaks.com/2015/08/how-to-change-text-fields-to-a-real-uuid-type-for-django-and-postgresql

**Comment by rmoorman** [comment]
Thank you @tdruez. I will have a look :-)

**Comment by tdruez** [comment]
@rmoorman did you manage to migrate to the new UUIDField ?

**Comment by rmoorman** [comment]
@tdruez I just tried it again with a more involved project but there it does not seem to work while my initial tests were promising.

**Comment by trbs** [comment]
Closing this ticket now...

If there is anything we can add to help users please submit a PR.

**Comment by km-pg** [comment]
We're having an issue migrating a django-extensions UUIDField to a Django UUIDField with MySQL. When running the migrate command, I'm getting an error from MySQL "Data too long for column 'uuid' at row 1". Any ideas on how to handle this? Is there any documentation on it?

**Comment by trbs** [comment]
Maybe there is some specific functions in Mysql to convert from the old `varchar` version to proper `uuid` column type ?
