### ISSUE TITLE
CommandError: You need to install pygraphviz python module

### ISSUE THREAD

**Issue by tanrax** [django-extensions/django-extensions#750]
[ master ] $ pip list
Django (1.8.4)
django-admin-bootstrapped (2.5.0)
django-bootstrap3 (5.4.0)
django-cleanup (0.3.0)
django-extensions (1.5.7)
django-push-notifications (1.3.1)
Pillow (2.8.1)
pip (7.1.2)
psycopg2 (2.6.1)
pygraphviz (1.2)
setuptools (15.2)
six (1.10.0)

**Comment by trbs** [comment]
Works for me... please try importing pygraphviz manually and see if something goes wrong there.

otherwise please reopen this ticket and add a reproducible test case if you still think this is django_extensions related.

**Comment by tanrax** [comment]
where you should import the module? Thank you

**Comment by encolpe** [comment]
@tanrax using manage.py shell or manage.py shell_plus and typing:
```
import pygraphviz
```

**Comment by encolpe** [comment]
Django 1.9 and Python 3.5

```
DJANGO_SETTINGS_MODULE="myproject.settings" django-admin  graph_models -o myproject-v1.1.png myproject 
/home/encolpe/Venv/myproject/lib/python3.5/site-packages/django/core/management/base.py:265: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  RemovedInDjango110Warning)

/home/encolpe/Venv/myproject/lib/python3.5/site-packages/django_extensions/management/modelviz.py:307: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  dot = t.render(c)

CommandError: Neither pygraphviz nor pydot could be found to generate the image
(myproject) $ pip freeze | grep viz
pygraphviz==1.3.1
```

In shell_plus when you import pygraphviz you have an hide error due to the try/except in django-extensions code:
```
ImportError: /home/encolpe/Venv/pygraphviz/lib/python3.5/site-packages/pygraphviz/_graphviz.cpython-35m-x86_64-linux-gnu.so: undefined symbol: Agundirected
```

No idea to improve the import to display this error.

**Comment by encolpe** [comment]
For reference, this bug is known on pygraphviz: [_graphviz.so: undefined symbol: Agundirected](https://github.com/pygraphviz/pygraphviz/issues/71)
