### ISSUE TITLE
Outdated tests in pypi package for 1.5.7

### ISSUE THREAD

**Issue by peterdemin** [django-extensions/django-extensions#755]
I know, it looks insane, but here is what I get in fresh virtualenv. After installation of current django-extensions version:

```bash
~/Envs/django/Lib/site-packages/django_extensions $ pip freeze | grep django-extensions
django-extensions==1.5.7

 ~/Envs/django/Lib/site-packages/django_extensions $ head tests/test_clean_pyc.py
import os
import six
import shutil
import fnmatch
from django.test import TestCase
from django.core.management import call_command
from django_extensions.management.utils import get_project_root
```

This file (test_clean_pyc.py) was in this state in version 1.5.2.
I found it because get_project_root was removed from management.utils in 1.5.7.

Another strange thing is that, if I download django-extensions-1.5.7.tar.gz directly from pypi (https://pypi.python.org/pypi/django-extensions/1.5.7) there is no "tests" directory at all.

**Comment by camilonova** [comment]
Please try with a newer version of the package. Thanks.

**Comment by peterdemin** [comment]
Thank you
```bash
.../django_extensions$ ls tests
ls: tests: No such file or directory
```
