### ISSUE TITLE
stop using South migrations

### ISSUE THREAD

**Issue by ezarowny** [django-extensions/django-extensions#760]
As of Django 1.8.6, this error will pop up when creating databases / migrating:

```python
django.db.migrations.loader.BadMigrationError: Migrated app 'django_extensions' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.
```

See https://code.djangoproject.com/ticket/25618#comment:7 for further information.

**Comment by theskumar** [comment]
The change seems to be already in `master` [1]. I think we just need a new pypi release.

[1] https://github.com/django-extensions/django-extensions/tree/master/django_extensions

**Comment by trbs** [comment]
indeed :)

**Comment by ezarowny** [comment]
Cool, thanks! :+1:
