### ISSUE TITLE
inconsistent naming: create_template_tags vs. show_templatetags

### ISSUE THREAD

**Issue by mislavcimpersak** [django-extensions/django-extensions#767]
Management command for creating template tags is named with an underscore: `template_tags` while management command for showing template tags got it written as a single word: `templatetags`.

I propose to rename `show_templatetags` to `show_template_tags`.
The code can be copied to the new file/tests updated, while keeping in the old file just a call to the new command (using `from django.core.management import call_command`) and raising `DeprecationWarning`.

If it's ok, I can do the changes myself, just need a green light to go + info about deprecation (version planned to drop support for old command).

**Comment by trbs** [comment]
Sorry for the late reply.

I'm fine with that change.

I would suggest keeping the old command around for something like 3 releases (around 6 months) maximum. Seems like an easy thing to fix for users and I would like to minimize having two names for a command.

**Comment by trbs** [comment]
Thanks !
