### ISSUE TITLE
Tests fail for Django 1.9

### ISSUE THREAD

**Issue by brianmay** [django-extensions/django-extensions#769]
11 tests fail.

**Comment by nikolas** [comment]
PR #772 addresses most of these.. there's still one failing test that's kind of tricky - further info is in that PR

**Comment by trbs** [comment]
Thanks !

**Comment by brianmay** [comment]
Any chance of a new release to fix this? Thanks

**Comment by brianmay** [comment]
Not sure if the fixes here made it into 1.6.1 or not, however I am still getting test failures with version 1.6.1

**Comment by trbs** [comment]
One fix actually broke things :(
And we still don't have a confirmed fix for that
