### ISSUE TITLE
crash when saving illegal json string to JSONField

### ISSUE THREAD

**Issue by craynic** [django-extensions/django-extensions#778]
When saving illegal json string to a JSONField, ValueError raised. ValidationError raised excepted.

**Comment by trbs** [comment]
please try with the github version and if you still have problems provide more information (including reproducible test case)

**Comment by craynic** [comment]
I don't think it needs a test case. It's obvious that it should raise ValidationError in method to_python, not ValueError. 
db/fields/json.py:84 I think we should catch ValueError and raise ValidationError here.

**Comment by trbs** [comment]
It's not obvious to somebody reading the ticket.
Since there is no traceback or alike information.

The reproducible case is so that somebody that wants to create a PR can get
going without having to figure out what exactly you need to do to trigger
your problem.

Regards,

Trbs
