### ISSUE TITLE
ForeignKeyAutocompleteAdmin not showing properly search icon on Dj1.9

### ISSUE THREAD

**Issue by danigosa** [django-extensions/django-extensions#786]
It looks for 

```
   <img src="/static/admin/img/selector-search.gif" width="16" height="16" alt="Lookup">
```

While it should be **search.svg**

Screenshot:
<img width="1399" alt="extensions_error" src="https://cloud.githubusercontent.com/assets/1827475/11899552/00a1c372-a5a0-11e5-9d6c-ecce8e0acb6a.png">

**Comment by arthurio** [comment]
I think it doesn't even need an `img` tag since the css on the `a` tag already adds the search icon.

**Comment by trbs** [comment]
Closing this for being inactive for too long. If there is a better way we are still happy to accept a PR for this.
