### ISSUE TITLE
Depreciation warnings

### ISSUE THREAD

**Issue by cnobile2012** [django-extensions/django-extensions#790]
I found this deprecation warning when I converted my project to Django 1.9. 

```
django/core/management/base.py:265: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  RemovedInDjango110Warning)
```

**Comment by Zverushko** [comment]
i see this warning too

**Comment by davidthewatson** [comment]
I get this when I run:

    ./manage.py show_urls

**Comment by timgraham** [comment]
This can be closed. All commands are now using argparse except as noted in https://github.com/django-extensions/django-extensions/issues/788#issuecomment-228459700.
