### ISSUE TITLE
AutoSlugField doesn't populate model

### ISSUE THREAD

**Issue by oppianmatt** [django-extensions/django-extensions#801]
Using the AutoSlugField in the normal way (making a slug from a name). It seems the slug field doesn't get populated in python but only in the sql.

Create a model and slug field is blank. Load the model from the database and the slug is populated.

Means I can't use the new model to redirect to since the slug is empty.

**Comment by st4lk** [comment]
Have same behaviour when specify `allow_duplicates = False`. With `allow_duplicates = True` (default) all goes well.
