### ISSUE TITLE
Complete switching to Py.test

### ISSUE THREAD

**Issue by Stranger6667** [django-extensions/django-extensions#802]
Hi!
I want to propose to rewrite the test suite with py.test. Main goals are: 
- Simplicity. Now test suite is quite complicated and has a lot of code duplication
- Usage of TestCase features when py.test has better options (e.g. fixtures & parametrization)

Now some tests are using py.test features but some are not.
It will be better to show the code, so, don't you mind if I'll create some draft for that?

**Comment by trbs** [comment]
Sure, I'm happy to merge any improvements !

**Comment by trbs** [comment]
If you think this still needs work, please create some pull requests 👍
