### ISSUE TITLE
RemovedInDjango110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.

### ISSUE THREAD

**Issue by thecardcheat** [django-extensions/django-extensions#808]
I did a quick test in Django 1.9,1.7.11 and see no reason this won't be part of my PR for #804. This deprecation warning is essentially one level up from the optparse deprecation so having compatibility command classes should sensibly resolve this as well.

**Comment by trbs** [comment]
yes that would be great !

**Comment by thecardcheat** [comment]
#804
