### ISSUE TITLE
Management command revamp for argparse broken commands

### ISSUE THREAD

**Issue by jaddison** [django-extensions/django-extensions#823]
`runserver_plus` no longer accepts the positional argument of `0.0.0.0:8000` (ip address/port combo) because the changes in this pull request ignore positional arguments. It looks like `optparse` was forgiving with regards to positional arguments, just passing them through to be handled. `argparse` expects them to be defined, it seems.  This is directly related to #820. The PR that causes this (mis)behaviour is #804 (I think).

See Django `master`'s current runserver code for this positional argument: https://github.com/django/django/blob/master/django/core/management/commands/runserver.py#L39

This is the error I see when using django-extensions `master` branch:

```
(myproject)vagrant@vagrant-ubuntu-trusty-64:/vagrant$ python manage.py runserver_plus 0.0.0.0:8000
usage: manage.py runserver_plus [-h] [--version] [-v {0,1,2,3}]
                                [--settings SETTINGS]
                                [--pythonpath PYTHONPATH] [--traceback]
                                [--no-color] [--ipv6] [--noreload] [--browser]
                                [--adminmedia ADMIN_MEDIA_PATH]
                                [--nothreading] [--threaded]
                                [--output OUTPUT_FILE] [--print-sql]
                                [--cert CERT_PATH] [--extra-file EXTRA_FILES]
                                [--reloader-interval RELOADER_INTERVAL]
                                [--pdb] [--ipdb] [--pm]
                                [--startup-messages STARTUP_MESSAGES]
                                [--nostatic] [--insecure]
manage.py runserver_plus: error: unrecognized arguments: 0.0.0.0:8000
```

I suspect that other django-extensions' management commands will need a positional argument review as well - particularly when you see other related issues like #820.

**Comment by MattBroach** [comment]
I'd like to add that I've also had this problem with the following `runserver_plus` arguments:
```
python3 manage.py runserver_plus [::]:8001
```
Incidentally, it worked just fine with django 1.9.7, but broke when I upgraded to django 1.10b1.  I did test the normal django runserver on 1.10b1, and it acceps `[::]:8001` as an argument.

**Comment by trbs** [comment]
Closing this for being inactive for too long. If there is a better way we are still happy to accept a PR for this.
