### ISSUE TITLE
manage.py print_settings not working with specified names

### ISSUE THREAD

**Issue by SeanHayes** [django-extensions/django-extensions#848]
Running Django 1.8.9.

```
$ python manage.py print_settings DEBUG INSTALLED_APPS
usage: manage.py print_settings [-h] [--version] [-v {0,1,2,3}]
                            [--settings SETTINGS]
                            [--pythonpath PYTHONPATH] [--traceback]
                            [--no-color]
manage.py print_settings: error: unrecognized arguments: DEBUG INSTALLED_APPS
```

**Comment by trbs** [comment]
This works for me on both Django 1.8 and Django 1.9.
Are you sure you are running a recent version of django-extensions ?

**Comment by SeanHayes** [comment]
I'm running django-extensions==1.6.1, that's the most recent, right?

**Comment by SeanHayes** [comment]
When I ran the command without args (to print everything) I got a JSON serialization error, if that helps.

**Comment by Eimis** [comment]
I second this, it doesn't work with Django 1.9.8 and django-extensions 1.6.7:

```
(virtualenv)MacBook-Air-2:mijnstroom eimantas$ python manage.py print_settings DEBUG
usage: manage.py print_settings [-h] [--version] [-v {0,1,2,3}]
                                [--settings SETTINGS]
                                [--pythonpath PYTHONPATH] [--traceback]
                                [--no-color] [--format FORMAT]
                                [--indent INDENT]
manage.py print_settings: error: unrecognized arguments: DEBUG
(virtualenv)MacBook-Air-2:mijnstroom eimantas$
```

**Comment by trbs** [comment]
Please test with the latest version on github. This should be solved.

One thing is that right now there are a lot of changes in the github version compared to the last release and I have not had the time to test everything and feel good about making a new release.

If people want to help by testing the github version, trying out the commands (and fields) and report back if they had any issues (or not) it would be much appreciated.

**Comment by Lrcezimbra** [comment]
Any updates on this?

I had the same error with `Python 2.7.13`, `Django==1.10.7` and `django-extensions==1.8.1`

```sh
$ python manage.py print_settings EMAIL_HOST_USER
usage: manage.py print_settings [-h] [--version] [-v {0,1,2,3}]
                                [--settings SETTINGS]
                                [--pythonpath PYTHONPATH] [--traceback]
                                [--no-color] [--format FORMAT]
                                [--indent INDENT]
manage.py print_settings: error: unrecognized arguments: EMAIL_HOST_USER
```

**Comment by trbs** [comment]
I think the command broke again with the change in how arguments work in django commands.

Basically the positional arguments are not working anymore. Looking at https://docs.djangoproject.com/en/1.11/howto/custom-management-commands/ the fix should be pretty trivial.

I hope somebody has a few minutes time to create a pull request fixing the positional arguments and a test in the test suite which tests the examples that are given in the documentation: https://django-extensions.readthedocs.io/en/latest/print_settings.html

**Comment by Lrcezimbra** [comment]
I can create a pull request

**Comment by trbs** [comment]
Closing this for being inactive for too long. If there is a better way we are still happy to accept a PR for this.
