### ISSUE TITLE
Issue using command syncdata

### ISSUE THREAD

**Issue by aleonsan** [django-extensions/django-extensions#856]
run time:
python 2.7.11 x86
django 1.8.8
django-extensions 1.6.1
django-parler 1.4

While attempting:

python manage.py syncdata fixture_file.json, I'm getting this error:
Traceback:
`File "/home/aleon/.virtualenvs/frontend_global_security/local/lib/python2.7/site-packages/django_extensions/management/commands/syncdata.py", line 178, in handle
    self.remove_objects_not_in(objects_to_keep, verbosity)
  File "/home/aleon/.virtualenvs/frontend_global_security/local/lib/python2.7/site-packages/django_extensions/management/commands/syncdata.py", line 82, in remove_objects_not_in
    type_deleted = six.u(class_._meta.verbose_name_plural)
  File "/home/aleon/.virtualenvs/frontend_global_security/local/lib/python2.7/site-packages/six.py", line 647, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
TypeError: decoding Unicode is not supported
`

Avoiding verbosity the issue won't happen: -v 0

The error raises at six module:
`type_deleted = six.u(class_._meta.verbose_name_plural)`
When calls:
`return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")`

variable "s" is django.utils.functional.**proxy** object

BR

**Comment by trbs** [comment]
Hope this is solved by now, otherwise please open a new issue. Thanks !
