### ISSUE TITLE
Just found a future deprecation issue

### ISSUE THREAD

**Issue by cnobile2012** [django-extensions/django-extensions#857]
/home/cnobile/.virtualenvs/fasbook/local/lib/python2.7/site-packages/django_extensions/management/modelviz.py:307: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  dot = t.render(c)

**Comment by timgraham** [comment]
Duplicate of https://github.com/django-extensions/django-extensions/issues/810 (which I believe is fixed).

**Comment by trbs** [comment]
thanks !

(if it's not fixed please open a new ticket)
