### ISSUE TITLE
runserver_plus doesn't reload altered .py files

### ISSUE THREAD

**Issue by Chiron1991** [django-extensions/django-extensions#860]
I recently updated django-extensions to its most recent release. Since then runserver_plus doesn't recognize changed .py files any more. Before the update everything worked fine. However, Django's regular runserver still works perfectly.

I've been doing some googling on this topic and found Werkzeug and watchdog to be involved with django-extensions and it's reloading feature, so I gave updating those a chance. Didn't fix the problem.

I'm running a VirtualBox (5.0.16, latest) with Vagrant (1.8.1, latest) and Ubuntu 14.04 for my development environment. Packages used:
django-extensions: 1.6.1
watchdog: 0.8.3
Werkzeug: 0.11.4

Let me know if you need any log files, etc.

**Comment by trbs** [comment]
Hope this is solved by now, otherwise please open a new issue. Thanks !
