### ISSUE TITLE
graph_models broken in (at least) django 1.5.1

### ISSUE THREAD

**Issue by fabiansvara** [django-extensions/django-extensions#862]
This happens in Django 1.5.1. I have not investigated whether this happens in any other django version.

In ```compat.py```, ```get_models_compat(app_label)``` always returns an empty list, because Django's AppCache instance's app_store SortedDict (in ```db/models/loading.py```) does not contain as keys the app names (which is how the code in compat.py attempts to look up the models), but their model modules.

In ```compat.py```, line 154 etc, changing
```
except ImportError:
        from django.db.models import get_models
        return get_models(app_label)
```
to 
```
except ImportError:
        from django.db.models import get_models
        return get_models(get_app(app_label))
```
fixes it.

The same issue may be present in multiple other locations.

Guess we're all yearning for static type checks.

**Comment by blueyed** [comment]
Maybe `get_models_for_app` should be used here, which uses that pattern?
https://github.com/django-extensions/django-extensions/blob/b3206a7b3179f4b5cfc4d0fe7d8b8638ce25c261/django_extensions/compat.py#L159

**Comment by blueyed** [comment]
Can you try https://github.com/blueyed/django-extensions/commit/dba191e04ee1f64452a8e018c29536f9622c16de / #882, please?
