### ISSUE TITLE
Possible combinations examples for RandomCharField in docs are wrong?

### ISSUE THREAD

**Issue by keybits** [django-extensions/django-extensions#863]
On [this page](https://github.com/django-extensions/django-extensions/blob/master/docs/field_extensions.rst) in the docs it says:

> Given a length of 8 thats yields 3.4 million possible combinations. A 12 character field would yield about 2 billion

The default character set for `RandomCharField` consists of lowercase letters (26), uppercase letters (26) and numbers (10). That makes a total of 62 characters. I believe the possible combinations should therefore be:
- length of 8 = 3,381,098,545 (3.4 billion)
- length of 12 = 2,160,153,123,141 (2.1 trillion)

Or perhaps I'm missing something?

**Comment by trbs** [comment]
Closing this for being inactive for too long. If there is a better way we are still happy to accept a PR for this.
