### ISSUE TITLE
ForeignKeyAutoComplete Deprecation Warnings

### ISSUE THREAD

**Issue by SpectralAngel** [django-extensions/django-extensions#868]
I have been getting this deprecation warning lately:

env/site-packages/django_extensions/admin/__init__.py:72: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  urlpatterns = patterns('', url(r'foreignkey_autocomplete/$', wrap(self.foreignkey_autocomplete), name='%s_%s_autocomplete' % info))

**Comment by timgraham** [comment]
Fixed in c614b5bba69d96f48ea8d08260fc7919a4ad2cdf.
