### ISSUE TITLE
create_superuser doesn't appear to exist.

### ISSUE THREAD

**Issue by kitsunde** [django-extensions/django-extensions#875]
`create_superuser` is listed in https://github.com/django-extensions/django-extensions/blob/master/docs/command_extensions.rst but it doesn't appear to exist.

**Comment by akoikelov** [comment]
maybe command calls `createsuperuser`?

**Comment by trbs** [comment]
it's been removed back in 752bd527250c282e7b2a480ba1a613a278f1ac48 but the documentation was never updated.

thanks for pointing this out
