### ISSUE TITLE
`save` function on `TimeStampedModel` not called when using django's `bulk_create`

### ISSUE THREAD

**Issue by gbozee** [django-extensions/django-extensions#878]
I just ran into an issue when attempting to use `bulk_create` on some models using the `TimeStampedModel` Mixin. This wasn't an issue with previous version of the library. On inspection I observed the following lines

    def save(self, **kwargs):
         self.update_modified = kwargs.pop('update_modified', True)
         super(TimeStampedModel, self).save(**kwargs)

on `django_extensions/db/fields/__init__.py` line 28-31

When a multiple model instances are initialized and are are saved using `Model.object.bulk_create`. An exception is raised. Tracing the exception, I observed this

    def pre_save(self, model_instance, add):
        if not model_instance.update_modified:
            return model_instance.modified
        return super(ModificationDateTimeField, self).pre_save(model_instance, add)

on `django_extensions/db/fields/__init__.py` line 412-415. 
since `model_instance.update_model` is created only when the save function is called, running `bulk_create` before actually saving any of the model instances throws `AttributeError: '***' object has no attribute 'update_modified'`

**Comment by Koed00** [comment]
I've observed the same problem with my models that use the  `ModificationDateTimeField`.
Any save() will throw an ```AttributeError: '***' object has no attribute 'update_modified'```

Reverting to version 1.6.1 resolves this.

**Comment by trbs** [comment]
Please test this patch.

Also can anybody provide a test case for this ?

**Comment by Koed00** [comment]
Patch seems to work for me.

**Comment by trbs** [comment]
New version released on PyPi
