### ISSUE TITLE
bulk_create

### ISSUE THREAD

**Issue by oyoun** [django-extensions/django-extensions#889]
Hi,

I am using django-extensions to write a script and I have those statements that don't work:

When I use the bulk_create method, the database is not affected.

The same for this request:
MyModel.objects.filter(created_on__lte=my_date).delete()

When I use the save method and delete on each object, it works.

Python 3.5 and django 1.9

**Comment by oyoun** [comment]
I am using python 3.5 and django 1.9

**Comment by trbs** [comment]
Don't think this is ```django-extensions``` related...

I would recommend looking carefully to the exact variables that are used in the querysets, also look into your database logs (maybe have toincreasing the log level) or use the query debug log from Django to see what actually gets executed on the database.
