### ISSUE TITLE
None of the shell_plus imports are working after upgrading to 1.6.7

### ISSUE THREAD

**Issue by erikcw** [django-extensions/django-extensions#895]
I just upgraded to 1.6.7 as part of a project wide upgrade from Django 1.7.* to 1.9.6.

When starting `shell_plus`, the console claims to have imported my models, as well as a few "Shell Plus User Imports", however, none of them seem to be in the namespace.

**Comment by erikcw** [comment]
Note that I'm on IPython 4.2.0.

**Comment by artcz** [comment]
+1, same problem here, also after upgrading to django 1.9.

**Comment by trbs** [comment]
Seems to work fine for me.

Please create a reproducible test case and reopen the (or create a new) ticket.
