### ISSUE TITLE
Drop support for Django 1.6 and 1.7

### ISSUE THREAD

**Issue by timgraham** [django-extensions/django-extensions#900]
These versions are no longer supported by the Django team and are insecure. I think anyone stuck on them can use an old version of django-extensions. Also, adding support for future versions of Django will require more effort as features deprecated in 1.8 are now removed in 1.10. Any objection?

I can probably submit a PR, if so desired.

**Comment by trbs** [comment]
I agree. If you could submit a PR for this please do.

(For reference if anybody reading this in the future; our official policy is to follow the Django policy so officially django-extensions does not support 1.7 anymore since 1 December 2015)

**Comment by timgraham** [comment]
https://github.com/django-extensions/django-extensions/pull/913 is ready to go.
