### ISSUE TITLE
python setup.py develop

### ISSUE THREAD

**Issue by filipefigcorreia** [django-extensions/django-extensions#92]
Shouldn't this work for django-extensions?
    python setup.py develop

It works in other projects, but when I run it with django-extensions I get the strangest error message:
    $ python setup.py develop
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

```
error: invalid command 'develop'
```

I've also looked at the contents of setup.py, and haven't spotted anything unusual.

**Comment by cccchelsea** [comment]
torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by maxuba** [comment]
> extensions

hi, do you solve this issue? how can i do with it , Thank you for help.

**Comment by maxuba** [comment]
> torch.utils.ffi is deprecated. Please use cpp extensions instead.
hi, do you solve this issue? how can i do with it , Thank you for help

**Comment by trbs** [comment]
Think these comments are not related to `django-extensions` :-)
