### ISSUE TITLE
TimeStampedModel wont match created and modified of new objects

### ISSUE THREAD

**Issue by vmenezes** [django-extensions/django-extensions#925]
When a `TimeStampedModel` object is created, `created` and `modified` fields won't match (usually milliseconds difference) and my understanding this is not the intended behavior(or plain wrong).
I believe the `save` method should write `modified` field with the same value of `created`.

Following a quick sample of the problem.

```
from django_extensions.db.models import TimeStampedModel

class Foo(TimeStampedModel):
  foo = models.IntegerField(null=True, blank=True)

---- ON SHELL ----
>>> new_foo = Foo.objects.create(foo=1)
>>> new_foo.created
datetime.datetime(2016, 6, 30, 16, 1, 43, 984512, tzinfo=<UTC>)
>>> new_foo.modified
datetime.datetime(2016, 6, 30, 16, 1, 43, 984602, tzinfo=<UTC>)
>>> new_foo.created == new_foo.modified # SHOULD BE TRUE
False
```

**Comment by trbs** [comment]
It would be especially weird if ```modified``` would be earlier then ```created``` due to them not using the same value when creating an object :)

**Comment by vmenezes** [comment]
@trbs sometimes is good to not by async.

**Comment by trbs** [comment]
We should also look this in light of the discussion there is around using ```auto_add``, ```auto_add_now```, ```default``` and overloading ```save(...)```.

Also if we decide to change this behavior we will get a schema migration, so we would need to do some planning and preferably make it so that there is an upgrade path and a deprecation of the old behavior over a couple of releases. (This might be far more work then the actual patch to change the behavior itself :) )
