### ISSUE TITLE
AutoSlugField.deconstruct does not match construction values

### ISSUE THREAD

**Issue by mvantellingen** [django-extensions/django-extensions#928]
I'll try to submit a PR later but in case i forget:

The deconstruct() call should return the same which were used to initalize the field. However the populate_from property is changed from create_slug() which causes the django migration checker to think that a migration is required.

See workaround solution here: https://github.com/django-oscar/django-oscar/commit/27cb08936252ae320423ecccc22b5658135c5b04

**Comment by trbs** [comment]
Is this still an issue ?
If so we would appreciate the PR :)
