### ISSUE TITLE
[minor] No link to specific issues in dumpscript command documentation

### ISSUE THREAD

**Issue by GabLeRoux** [django-extensions/django-extensions#929]
In dumpscript's doc:
https://github.com/django-extensions/django-extensions/blame/master/docs/dumpscript.rst#L47-L53

I was playing around with documentation and it specifies a few issues (looks like it's been written a while ago) and I don't think they're pointing to any valid issues here on github. Was there an older issue tracker, are there any details about this somewhere?

**Comment by trbs** [comment]
Good catch.. I have no clue what they refer too.. 
We should remove those issue numbers (and double check if they are actual issues anymore)

**Comment by navyad** [comment]
What it can't do (yet!)

 * Ideal handling of generic relationships (ie no *AutoField* references):
   issue 43
 * Intermediate join tables: issue 48
 * GIS fields: issue 72

Respective issues on gihub (All are closed) by issue number are following:
43: [https://github.com/django-extensions/django-extensions/pull/43](https://github.com/django-extensions/django-extensions/pull/43)
48: [https://github.com/django-extensions/django-extensions/pull/48](https://github.com/django-extensions/django-extensions/pull/48)
72: [https://github.com/django-extensions/django-extensions/pull/43](https://github.com/django-extensions/django-extensions/pull/72)


@trbs I think those issues are not there anymore, can you confirm on this ? Then i can go ahead to remove from doc.

**Comment by trbs** [comment]
The issue tickets are not there and not sure what they did refer too.
So they can be removed from the docs. (There is also an invalid reference at https://github.com/django-extensions/django-extensions/blame/master/docs/dumpscript.rst#L40 )

My guess is that the list of things ```dumpscript``` cannot do might be accurate although probably incomplete :)

So I'm not sure if removing it all together is the best thing to do....

**Comment by morenoh149** [comment]
so we should remove the `What it can’t do (yet!)` section correct? I can submit a PR for that.
And update `ContentType fields and generic relationships (but see issue 43)`

**Comment by trbs** [comment]
Yeah lets.

Thanks for taken the time for a pr !
I'll close this issue in favor of merging the PR.
