### ISSUE TITLE
runserver_plus no longer accepts IP:PORT parameter?

### ISSUE THREAD

**Issue by ssteinerx** [django-extensions/django-extensions#935]
Python 3.5.2, OS X 10.11.6, Django 1.10.0rc1, also happens in Docker container under boot2docker:

```
$ python manage.py runserver_plus 0.0.0.0:8000
usage: manage.py runserver_plus [-h] [--version] [-v {0,1,2,3}]
                                [--settings SETTINGS]
                                [--pythonpath PYTHONPATH] [--traceback]
                                [--no-color] [--ipv6] [--noreload] [--browser]
                                [--adminmedia ADMIN_MEDIA_PATH]
                                [--nothreading] [--threaded]
                                [--output OUTPUT_FILE] [--print-sql]
                                [--cert CERT_PATH] [--extra-file EXTRA_FILES]
                                [--reloader-interval RELOADER_INTERVAL]
                                [--pdb] [--ipdb] [--pm]
                                [--startup-messages STARTUP_MESSAGES]
                                [--nostatic] [--insecure]
manage.py runserver_plus: error: unrecognized arguments: 0.0.0.0:8000
```
RUNSERVERPLUS_SERVER_ADDRESS_PORT also seems to be ignored.

```
$ export RUNSERVERPLUS_SERVER_ADDRESS_PORT='0.0.0.0:6000'
$ env | grep RUNSERV
RUNSERVERPLUS_SERVER_ADDRESS_PORT=0.0.0.0:6000
$ ./manage.py runserver_plus
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with stat
Performing system checks...
System check identified no issues (0 silenced).
```

**Comment by trbs** [comment]
please check with the latest version on github

**Comment by ssteinerx** [comment]
That works!  When will the next point release be as this is a real showstopper in Docker containers where 127.0.0.1 != 0.0.0.0 at *all*.

**Comment by ssteinerx** [comment]
Has the issue with RUNSERVERPLUS_SERVER_ADDRESS_PORT being ignored also fixed?

**Comment by trbs** [comment]
Please test to see if ```RUNSERVERPLUS_SERVER_ADDRESS_PORT``` is still an issue and if so open a new issue (and PR ? :) for it.

As for a new release (and this is a general note) we really need two things:

1) better test coverage, so anybody that wants to assist with writing more and better tests is very much welcome !

2) more people can test the ```django-extensions``` github version and report back on any errors as well as it's stability.

With Django 1.10 now out I would really like to make a new release that supports it soon but I also don't want to break things.

**Comment by ssteinerx** [comment]
I'm hesitant to produce pull requests on projects that have a bunch pending.  It's very frustrating to go to the trouble, making sure it passes tests, etc. then see it languish until it is no longer a clean merge.  I'd much rather see pull requests either merged, or rejected and closed, than see a bunch of "pending" ones without resolution.  Not criticizing, just telling you what *I* look at when deciding whether to expend effort creating a pull request on a project.

**Comment by ssteinerx** [comment]
This one, in particular, gives me pause...#649 opened on Mar 25, 2015 by BertrandBordage .  Well over a year old without resolution.
