### ISSUE TITLE
graph_models doesn't display the models if there's no models module with django > 1.7

### ISSUE THREAD

**Issue by mdamien** [django-extensions/django-extensions#936]
In `modelviz.py`, you're using:

```python
        app = get_app(app_label)
        if not app:
            continue
        # do all the stuff to register the models in the graph
```

Except that `get_app` return `None` if the app has no models module

```python
def get_app(app_label):
    try:
        # django >= 1.7
        from django.apps import apps
    except ImportError:
        from django.db import models
        return models.get_app(app_label)
    else:
        return apps.get_app_config(app_label).models_module # here, you assume you want `.models_module` to exist
```

But `get_models_for_app(app_label)` returns all the models correctly.

So, the solution can be:

- This is my fault, I should just have a `models` module for each app, even if it's empty

or

- Just do ` get_models_for_app(app_label)` in `modelviz.py` to see if there are models for the app (and do a check to see if the app exist in `get_models_for_app`)

PS: I can do a PR if the second solution is choosen

**Comment by trbs** [comment]
Can you check with the github version ?
I think that code has changed a little bit.

**Comment by mdamien** [comment]
It's not working with the latest version too, in `modelviz.py`:

```python
    for app_label in app_labels:
        app = apps.get_app_config(app_label).models_module # check for models_module too
        if not app:
            continue
       ....
```

**Comment by trbs** [comment]
I fixed the issue with app_label arguments and removed getting the models_module.
So now the app variable is actually the django app object :)

Does this fix your problem ?
Also can you create a test for this in our test suite ?

**Comment by mdamien** [comment]
yup, problem has been fixed :+1: 

yup, gonna try to add a test for that

**Comment by trbs** [comment]
Thanks !
