### ISSUE TITLE
runjobs argument handling fails

### ISSUE THREAD

**Issue by jma127** [django-extensions/django-extensions#937]
It seems that runjobs does not work on python3, django 1.10. Specifically, it rejects any arguments with the error: "error: unrecognized arguments: hourly" (or daily, weekly, etc.)

Reverting 21aa884 seems to fix the issue locally.

**Comment by trbs** [comment]
seems the patch 21aa884 was incomplete and needs another ```add_argument``` line for the arguments.

**Comment by trbs** [comment]
The following commit on git master should solve it: a72e0265156b869a347f726091c1843eb588f1bc

Could you please test this patch ?

**Comment by jma127** [comment]
Looks good and seems to be working, thanks for the quick fix!
