### ISSUE TITLE
Multiple command argument in runscript broke on 1.7 upgrades

### ISSUE THREAD

**Issue by ddehghan** [django-extensions/django-extensions#939]
HI guys,

With 1.6.7 this way of passing multiple arguments to the run function used to work:

```
python manage.py runscript admin_util --script-args=my_function 1234 456 "hello"

def run(*args):
    print *args        # would print (1234, 456, "hello") 

``` 
But after upgrading to 1.7.0  we get this error:

usage: manage.py runscript [-h] [--version] [-v {0,1,2,3}]
                           [--settings SETTINGS] [--pythonpath PYTHONPATH]
                           [--traceback] [--no-color] [--email-notifications]
                           [--email-exception] [--fixtures] [--noscripts] [-s]
                           [--no-traceback]
                           [--script-args [SCRIPT_ARGS [SCRIPT_ARGS ...]]]
                           [args [args ...]] script [script ...]
manage.py runscript: error: unrecognized arguments: 4

So with the new release how are we supposed to pass multiple arguments via command line

Thanks in advance.

**Comment by trbs** [comment]
Also see https://github.com/django-extensions/django-extensions/issues/788#issuecomment-228459700

**Comment by trbs** [comment]
You should remove the ```=``` sign from the command:

```
$ cat scripts/admin_util.py

def run(*args):
    print args

$ ./manage.py runscript admin_util --script-args my_function 1234 456 "hello"
('my_function', '1234', '456', 'hello')
```

**Comment by ddehghan** [comment]
That worked. Thank you . You are awesome. :-) @trbs

**Comment by trbs** [comment]
Great and no problem, glad to help.

I also updated the documentation since the example there also used ```=```. Which works if there is only one argument but is misleading for multiple arguments.

If you have some time could you look at the documentation of ```runscript``` and see if there is room for improvement ?

**Comment by ddehghan** [comment]
Great.

I would be good to make the example into multiple command line arguments.

**Comment by trbs** [comment]
Would you be able to make pull request for that ? (or post text here so I can copy-past it into the docs)
