### ISSUE TITLE
Changelog doesn't include notes for 1.7.4

### ISSUE THREAD

**Issue by Ichimonji10** [django-extensions/django-extensions#959]
Even a simple statement like "this is a bugfix release, and nothing should have broken" helps. (Yes, I understand that semver says effectively the same thing. Still, I appreciate the reassurance, and I don't know for sure that this project uses semver.)

**Comment by trbs** [comment]
Yes sorry I forgot to add the changelog item for 1.7.4.

Should be in the repository now.

**Comment by Ichimonji10** [comment]
Thank you!
