### ISSUE TITLE
validate_templates still work?

### ISSUE THREAD

**Issue by tisdall** [django-extensions/django-extensions#966]
I was trying out different features and I can't seem to get `validate_templates` to work.  It runs through every template and gives the error "TypeError get_template() takes exactly 1 argument (2 given)" on every single one.

I'm using Django 1.6 with django-extensions 1.6.7 .  I also tried Django 1.5 with django-extensions 1.5.9 and it gave the same result.

I tried the `--traceback` arg and it just gave me the trace for the final "CommandError: XXX errors found" message.

**Comment by trbs** [comment]
Right now ```django-extensions``` requires ```Django``` 1.8 or higher. Older versions support older ```Django``` versions but they normally do not receive any updates.

Could you check with a recent version of ```Django``` and ```django-extensions``` ?
Feel free to reopen the issue if issue persist in the latest versions. 

(Please note that the ```django-extensions``` version numbers do not related to ```Django``` version numbers.)

**Comment by tisdall** [comment]
Unfortunately I'm stuck using older versions of Django at the moment.  I used versions of `django-extensions` that were supposed to still support the version of Django I was testing it with.  I don't expect anyone to fix older versions, but I found it odd that they didn't work at all so I thought maybe I was using it wrong...
