### ISSUE TITLE
runserver_plus command, pm (postmortem) mode does not work with python 3

### ISSUE THREAD

**Issue by eskhool** [django-extensions/django-extensions#970]
Issue is on Line 175 in management/commands/runserver_plus.py:
`print >>> sys.stderr, "Exception occured: %s, %s" % (exc_type, exc_value)`

This syntax does not work with Python 3. To make it work, we need to do:

```
from __future__ import print_function
....
.....
print("Exception occured: %s, %s" % (exc_type, exc_value), file=sys.stderr)

```

Should I send a PR?

**Comment by trbs** [comment]
Sorry for the extremely late reply.

Yes please send a PR to fix this if it's still necessary.
