### ISSUE TITLE
No tests for job scheduling management commands

### ISSUE THREAD

**Issue by YPCrumble** [django-extensions/django-extensions#972]
Hi - I really appreciate this module and use the jobs scheduling all the time. I noticed that there aren't any tests for `management/jobs.py` or `management/commands/runjobs.py`. Is this something that would be helpful to submit as a PR?

**Comment by trbs** [comment]
Definitely !

We would appreciate tests very much, likewise PR's for documentation and examples are just as welcome as features or bug fixes :-)

**Comment by trbs** [comment]
Merged PR, Many thanks for your hard work over the holidays on this :-)
