### ISSUE TITLE
runscript: working directory is manage.py location, not script location

### ISSUE THREAD

**Issue by Deleetdk** [django-extensions/django-extensions#974]
As per title, when I use `runscript` to run a script in e.g. `projectroot/app/scripts`, the working directory of this is `projectroot`, while it should be `projectroot/app/scripts`.

I run the script while being in the `projectroot` using a command like:

`python manage.py runscript my_script`

To replicate:

`my_script.py` placed in any app under `scripts`:

```
#imports
import os

#the script
def run(*args):
    print(os.getcwd())
```

**Comment by trbs** [comment]
This might to two fold ?

1) Make it clear in the documentation what the current behavior is.
2) Discussion on maybe changing the behavior.

For the later it seems changing the _cwd_ would be a breaking change... peoples script might rely on the current behavior for them. We could at least start by adding an CLI option (accompanied by option in settings.py) to set the _cwd_ to the scripts directory ?

Thoughts and PR's welcome :)

**Comment by Deleetdk** [comment]
You are right. This would be a creaking change for some scripts. However, it seems to me that the current default is counter-intuitive. A first step would be to add a CLI option, something like `--scriptpath`.

The reason script-path makes more sense than project root-path is that this makes scripts inside apps completely portable in the sense that it works even if one renames the app. This is not the case with the current setup, where one would have to rename the paths inside the scripts too.

Just an idea. :)

**Comment by trbs** [comment]
Think that's a great idea. We can add `--script-path` and have a `SCRIPT_PATH` setting in `settings.py` so that people do not have to specify it every time ?

Maybe in time we can make the `settings.SCRIPT_PATH` mandatory so old counter intuitive behavior is gone and people will have to think about this. (Or use some explicit and documented default, I'm okay with either...)

Could you submit a PR for this ?

**Comment by firegurafiku** [comment]
I would mind against the exact `SCRIPT_PATH` name: to me, it means the list of directories where script is looked up based on its short name, something like Unix `PATH` environment variable.

How about `--chdir-policy` option:
```
./manage.py --chdir-policy=each scripts/script.py app/scripts/script.py
```
where `--chdir-policy` value is one of the following:
* `none` — use current directory for all scripts
* `each` — perform chdir before each script invocation
* `root` — perform chdir to the directory  `manage.py`

If no option value is set, the policy should be controlled by `RUNSCRIPT_CHDIR_POLICY` setting, if it's absent, the default value `"each"` should be used.

**Comment by Deleetdk** [comment]
`chdir` was not a familiar or intuitive name to me, but I see that it's [a unix command to change working directory](http://pubs.opengroup.org/onlinepubs/009695399/functions/chdir.html). So the question is whether one wants an argument name that's intuitively meaningful (helps new users) or whether it should be consistent with unix (helps experienced users). Perhaps use whatever is most consistent with the already existing argument names. Either way is fine with me.

**Comment by trbs** [comment]
I have no strong preference. As an Unix user `chdir` is intuitive for me, but I agree for lots of other people it might not be. (We could also call it `--dir-policy`, thinking that `--working-directory-policy` is too long :) )

Also like the `policy` idea, I would add 1 more:
* `none` — use current directory for all scripts
* `each` — perform chdir before each script invocation
* `root` — perform chdir to the directory manage.py
* `custom` — perform chdir to the directory specified by `RUNSCRIPT_CHDIR` or `--chdir`

**Comment by domandinho** [comment]
Pull Request: https://github.com/django-extensions/django-extensions/pull/1113

**Comment by domandinho** [comment]
> I was thinking:
> 
> Should we also add a settings.RUNSCRIPT_DIR_POLICY ? so that users do not have to set --dir-policy every time they call runscript.
> 
> And maybe --chdir should just always override the working directory ?

Ad. 1 OK

Ad. 2 In my opinion we should remove 'custom' policy and change logic:

1. If --chdir is set, then use directory from this option.
2 Else if RUNSCRIPT_CHDIR is set then then use directory from this setting
3 Else if --dir-policy is set then compute directory basing on policy from this option
4. Else if RUNSCRIPT_CHDIR_POLICY is set then compute directory basing on policy from this setting
5. Else use 'none' policy.

Is it acceptable?

I will submit PR for this soon if this solution is OK.

**Comment by trbs** [comment]
Yeah I agree that would be even better.

Maybe switch 2 and 3 ? As using a cli option has the expectation to override default settings else.

**Comment by domandinho** [comment]
ok

**Comment by domandinho** [comment]
Pull Request #2 https://github.com/django-extensions/django-extensions/pull/1114

**Comment by trbs** [comment]
Thanks !
