### ISSUE TITLE
Docs: Installation Instructions

### ISSUE THREAD

**Issue by guettli** [django-extensions/django-extensions#975]
I think the nstallation Instructions can be simplified:

  http://django-extensions.readthedocs.io/en/latest/installation_instructions.html

1. Do you think easy_install is still done today? Why not remove this. I think pip is enough (here).

2. I think this is easier for new comers, then the 'git clone` and `ln -sf ...` command. 

```
pip install -e  git+https://github.com/django-extensions/django-extensions.git#egg=django-extensions
```

**Comment by trbs** [comment]
Yeah your right. Could you create a PR for this ?

**Comment by guettli** [comment]
I created a pull request: https://github.com/django-extensions/django-extensions/pull/976

**Comment by trbs** [comment]
merged 👍
