### ISSUE TITLE
Documentation for NOTEBOOK_ARGUMENTS is wrong

### ISSUE THREAD

**Issue by smerrill** [django-extensions/django-extensions#977]
In looking at the documentation for setting `NOTEBOOK_ARGUMENTS` in a Django settings file, it seems to imply that you should enter a set of full keys and their values, so I assumed that I would need to enter a setting for `--notebook-dir` like this:

```
NOTEBOOK_ARGUMENTS = [
    '--notebook-dir=/path/to/notebooks',
]
```

but after reading https://github.com/django-extensions/django-extensions/blob/af9f78c5935b61afaaadd2a989df2bddfab58f0b/django_extensions/management/commands/shell_plus.py#L209 I realized that I'd have to enter it like this for it to work:

```
NOTEBOOK_ARGUMENTS = [
    '--notebook-dir', '/path/to/notebooks',
]
```

Should the other examples be changed to reflect this syntax?

**Comment by trbs** [comment]
Yeah, Thanks !
I updated the example could you please check if this is correct now ?

If you can, would you be willing to look at the documentation about Notebooks in `shell_plus` and see if it can be improved further ?

(PR's are also much appreciated)
