### ISSUE TITLE
[graph_models] Depict association classes

### ISSUE THREAD

**Issue by filipefigcorreia** [django-extensions/django-extensions#98]
This is a feature-request for the graph_models extension: [Intermediary models](http://docs.djangoproject.com/en/dev/ref/contrib/admin/#working-with-many-to-many-intermediary-models) could be shown as [UML association classes](http://www.agilemodeling.com/style/classDiagram.htm#Figure2).

**Comment by camilonova** [comment]
We receive Pull Requests anytime, if you want to can contribute too. Thank you.
