### ISSUE TITLE
Automatic Model imports don't work!

### ISSUE THREAD

**Issue by randomshinichi** [django-extensions/django-extensions#981]
When I run shell_plus, it instantly prints out all the models it found in all my apps. Then it gives me these nice lines, which imply that the classes were really auto-imported, which is so impressive and reassuring:

```
Shell Plus Model Imports
from b2bpay.apps.transactions.models import Attachment
```

But they aren't! Why not? Why is it printing stuff out when it hasn't actually imported anything?

```
In [2]: Attachment
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-c74e9844aceb> in <module>()
----> 1 Attachment

NameError: name 'Attachment' is not defined
```

So I even defined SHELL_PLUS_POST_IMPORTS:

```
Shell Plus User Imports
from b2bpay.apps.onboard.models import *
from b2bpay.apps.wizard.models import *
```

But again, no class got imported.

**Comment by trbs** [comment]
Can you please create a repository which contains a reproducible case for this ?
Or try to find out why this is not working so we can create a solution.

**Comment by typeshige** [comment]
I have the same issue.  If I find out more, I'll write back.

**Comment by typeshige** [comment]
If I don't use ipython (shell_plus --plain), the auto imports work fine.

--bpython also works fine.

It's strange since I have another project with the same versions of extension, django and ipython and it works just fine.

**Comment by trbs** [comment]
Tried myself with ipython-4.2.0 and ipython-5.1.0 (on django-extensions-1.7.4) and there it seems to work.

Following @typeshige comments it might be hard to create an good standalone reproducible repo for this... Is there anybody that has this problem and can share the code ?

**Comment by gabn88** [comment]
Same problem here with ipython on a clean ubuntu 18.04 install. On my previous Ubuntu 16.04 everything was working fine. Now resolved to bpython, which does work!

**Comment by Madi7** [comment]
I've faced the same problem. Auto-imports used to work fine until today. --plain is still working though

**Comment by Madi7** [comment]
Though forget about ipython, I just tried bpython and it works fine plus looks awesome !

**Comment by trbs** [comment]
Sounds like there might be issues with specific versions of IPython..

If anybody could write a PR with unit test for this it would be much appreciated.

**Comment by rakyi** [comment]
Same problem here:

- Python 2
- ipython 5.7.0, ipython-genutils 0.2.0
- django 1.11.14
- django-extensions 2.1.0
