### ISSUE TITLE
Unable to generate svg file using Graph models.

### ISSUE THREAD

**Issue by MirkoHernandez** [django-extensions/django-extensions#984]
Using graph_models to create an svg image generates an error; this is the command used:
```shell
python manage.py graph_models -a -o app_models.svg
```
The resulting error is: 

libpath/shortest.c:324: triangulation failed
libpath/shortest.c:192: source point not in any triangle
Error: in routesplines, Pshortestpath failed

I had no problem running the same command with a png or svgz extension only with svg.

**Comment by trbs** [comment]
Thanks for the report but looking at the error this seems to be the result of failures in the underlying graphing library used, not `django-extensions` itself.

I tested with both `pygraphviz` and `pydot`:

```
$ ./manage.py graph_models -a -o test.svg --pygraphviz
$ ./manage.py graph_models -a -o test.svg --pydot
```

Please consider reinstalling/upgrading/recompiling the graph library your using and raise this issue with them if you continue to have problems.
