### ISSUE TITLE
Typeerror with runserver_plus exceptions

### ISSUE THREAD

**Issue by orf** [django-extensions/django-extensions#988]
Hey, I'm using `runserver_plus` with Python 3 and the latest Django.

Sometimes when an exception is triggered I get the following exception, triggered by the werkzeug debugger:

```
Error on request:
Traceback (most recent call last):
File "/usr/local/lib/python3.5/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
   File "/usr/local/lib/python3.5/site-packages/werkzeug/serving.py", line 181, in execute
     application_iter = app(environ, start_response)
   File "/usr/local/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 451, in __call__
     response = self.get_resource(request, arg)
   File "/usr/local/lib/python3.5/site-packages/werkzeug/debug/__init__.py", line 355, in get_resource
    return Response(f.read(), mimetype=mimetype)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/wrappers.py", line 769, in __init__
     mimetype = get_content_type(mimetype, self.charset)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/utils.py", line 225, in get_content_type
     if mimetype.startswith('text/') or \
 TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

This prevents me from using the werkzeug debugger console, but the exception page is displayed as usual. It only sometimes happens, other times it appears to work fine.

I can help debug and fix this, but I've got no idea how this could be triggered.

**Comment by trbs** [comment]
The `mimetype` variable is probably of type `bytes`. Why this would happen sometimes and not always is a little strange, probably different code paths.

It however looks like this is an error with `Werkzeug` not `django-extensions` ?

Could you run your app with Werkzeug directly and see if it happens as well ? (this will probably break statics)

```
import os
import sys
 
os.environ["DJANGO_SETTINGS_MODULE"] = "myproject.settings"
 
from django.core.wsgi import get_wsgi_application
 
app = get_wsgi_application()
 
if __name__ == '__main__':
    from werkzeug.serving import run_simple
    run_simple('', 8080, app)
```

If your sure this is `django-extensions` related and not a bug in `Werkzeug` feel free to reopen this ticket.

**Comment by orf** [comment]
It appears it's a bug in werkzeug : https://github.com/pallets/werkzeug/issues/636

That ticket is from 2014 though, so it's not going to be fixed :(

I opened the issue here because it would need a workaround in `runserver_plus` for it to function I think, and I'm guessing it's something to do with Django-exensions because werkzeug can't be that broken?

**Comment by trbs** [comment]
That ticket would suggest that it is still a bug in Werkzeug and not related to Django... looking at the debug tracebacks.

If there is a patch we can do I'm happy to merge that :)

**Comment by davidism** [comment]
Something you're using is doing `mimetypes.add_type(b"text/less", ".less")`, putting bytes in the type map. This doesn't make sense to me. It seems you should identify what dependency is doing this and fix that.
