### ISSUE TITLE
shell_plus without model bootstrapping

### ISSUE THREAD

**Issue by evenicoulddoit** [django-extensions/django-extensions#997]
I know this might sound off given the description `shell_plus` being:

> Like the 'shell' command but autoloads the models of all installed Django apps.

However, I'm wondering whether it's possible to bypass model auto-loading altogether. I understand the `SHELL_PLUS_DONT_LOAD` setting allows you to do this on a per-model basis, but my incentive for asking this question is more related to performance.

I currently use the vanilla `shell` command, and legacy IPython's startup features to bootstrap my model and helper methods. I'm not a great fan of this however, as the feature is removed in later versions of IPython, and the same imports are not made available when debugging a production environment.

I just came across the shell plus pre/post imports feature, which would solve our use case nicely. The only thing I'm not a fan of is that the automatic model bootstrapping process takes 5+ seconds, which is a bit of a pain when constantly dropping into a REPL during development. Using the `SHELL_PLUS_DONT_LOAD` option almost certainly wouldn't optimize this, as I imagine a great deal of the time is spend in the [`get_apps_and_models()`](https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/shells.py#L133) call.

Does it seem reasonable / would you support adding a option to prevent that call being made altogether? Perhaps a `*` value in `SHELL_PLUS_DONT_LOAD` or similar. Alternatively, I could just extend the vanilla shell and try to roll my own, Happy to provide solution and update docs?

**Comment by trbs** [comment]
Would be happy to accept a PR for this.

```--dont-load=*``` / ```SHELL_PLUG_DONT_LOAD=["*"]``` would be fine with me. (Something like ```--dont-load=all``` or ```--dont-load=any``` would be nice but potentially conflicts with packages.)

From the top of my head the patch would be a simple addition of something like the following to the top of the ```django_extensions/management/shells.py:def import_object``` function:

```
def import_objects(options, style):
    if "*" in options.get('dont_load'):
        return {}

    ...
```

Plus a few lines of documentation on this and a small test case would be nice :-)

**Comment by domandinho** [comment]
Pull Request: https://github.com/django-extensions/django-extensions/pull/1112

**Comment by trbs** [comment]
Thanks !
