### ISSUE TITLE
error when generating graph with either include or exclude set

### ISSUE THREAD

**Issue by tshabs** [django-extensions/django-extensions#998]
In python 2:

`anagement/modelviz.py", line 95, in generate_graph_data
    if relation['target'] in nodes:
TypeError: 'NoneType' object has no attribute '__getitem__'
`

In python 3:

`nt/modelviz.py", line 95, in generate_graph_data
    if relation['target'] in nodes:
TypeError: 'NoneType' object is not subscriptable`

For now I have a fix by adding an if in line 95 to check if relation is None (PR to follow).

**Comment by GabLeRoux** [comment]
Thanks for this, I confirm it works, will wait for `django-extensions==1.7.6`.

I needed `graph_model` quickly so I did this and then it worked;
```bash
pip uninstall django-extensions
pip install git+https://github.com/django-extensions/django-extensions#egg=django-extensions
```

**Comment by trbs** [comment]
New release should be out shortly
